### ISSUE TITLE
Entry of age and year (only one, not both)

### ISSUE THREAD

**Issue by ashreves** [episphere/quest#100]
The questionnaire allows entry of an age and a year for some questions on the first pass. After clicking 'back' and tried this again, it worked as it supposed to, just allowing one or the other. Can programmers confirm where this has been instituted and check why it works sometimes but not others?

Sed SKINCANC3

**Comment by ruggz13** [comment]
Not sure what the question is? The one or the other works as tested

**Comment by ashreves** [comment]
@ruggz13 Not sure why this isn't appearing as an error now, it definitely was during our testing

**Comment by ruggz13** [comment]
Can we close this @danielruss @ashreves ?
