### ISSUE TITLE
[Sex=intersex or other] logic issue

### ISSUE THREAD

**Issue by ashreves** [episphere/quest#105]
Missing questions for SEX=Intersex. Was not given SEX2 at all. Was missing response options in later question. 

Did not get option for Finasteride, which I should have based on SEX=INTERSEX or OTHER

**Comment by danielruss** [comment]
1) I think there is an issue getting SEX from the user profile into quest -- this is a questionnaire  user problem (simpletest ,a proxy for the PWA, in this case )
2) it may also be an engineering issue...  If moduleParams.previousResults is being filled/read appropriately.

**Comment by ruggz13** [comment]
Resolved...
