### ISSUE TITLE
Siblings section long pause

### ISSUE THREAD

**Issue by ashreves** [episphere/quest#108]
The pause after siblings is really long. I understand this is because it is jumping over the 23 of 25 siblings I didn't have, but as a user, it made me think it had frozen and so I tried to go back and then forward. If we can't shorten the gap can we add a circular thing to indicate the computer is processing.

**Comment by ruggz13** [comment]
Fixed...Tested it as well. @ashreves

**Comment by ashreves** [comment]
Didn't have an issue with this the first time I tested it, but depending on responses, I seem to get stuck.

If all my siblings had cancer, it works fine.

If I try to say that a sibling did not have a cancer, it gets stuck.

**Comment by ruggz13** [comment]
Are you clearing your results each time you try a different path?

**Comment by ruggz13** [comment]
@ashreves I just tried it and there is no pause for any path I try

**Comment by ashreves** [comment]
@ruggz13 
I just cleared my results and tried again. 

There is a very long pause on the screen that reads "You told us that you have 1 sibling, including full and half-siblings. If this is not correct, please select the “Back” button to update your response. If this is correct, please select the “Next” button to move forward."

The pause lasts several minutes, testing Chrome on a PC.

**Comment by ashreves** [comment]
@ruggz13 Here's a screen recording so you can see the issues that I am having:

https://drive.google.com/file/d/1FGgLqZs2_2OcHf54D-3OxijPxdSe7SB0/view

**Comment by ruggz13** [comment]
Fixed VPN workaround
