### ISSUE TITLE
CHILDCANC3A logic incorrect

### ISSUE THREAD

**Issue by ashreves** [episphere/quest#109]
Had a glitch. I only said "bladder" for CHILDCANC2, but was given follow-up questions for all cancers on the list. I went back and answered only bladder again and then the skip pattern worked. Not sure what the issue was, but there was certainly a glitch.

**Comment by ruggz13** [comment]
tree.previous clearing too soon see #86 @danielruss

**Comment by danielruss** [comment]
#86 appears to be fixed.  Keep an eye on this, Still may be clearing children too soon.

**Comment by ruggz13** [comment]
Will keep an eye on it...Reopen if needed
