### ISSUE TITLE
free response box larger

### ISSUE THREAD

**Issue by ashreves** [episphere/quest#118]
The free response text box should be larger so participants can see whole box before submitting.

See WORK3

**Comment by danielruss** [comment]
Nick, Any idea what is causing the Textarea elements to be so small??

**Comment by ruggz13** [comment]
WORK3 isn't a text area, it is an input type text. Should it be changed to a text area? @danielruss @ashreves

**Comment by ashreves** [comment]
@ruggz13 @danielruss Not sure what the difference between the two types are, but I do think it should be large enough to capture a short sentence without going out of view.

**Comment by ruggz13** [comment]
The difference between the two are that one is a set height and width (input type text) and the other can be adjusted to whatever height and width you would like (text area). Currently the free response in WORK3 is set to an input type text. It can be switched to a text area if inclined to do so @ashreves

**Comment by ruggz13** [comment]
See EMPLYRSRVCE1 for example of text area

**Comment by danielruss** [comment]
Ok, I see.  There are 2 issues that I am conflating.  1) text box  (input[type="text"];work4) is too small.  2) textarea (textarea;EMPLRYSRVCE1) is too narrow.  

For case 1:  (which is the focus of this issue), I can handle as quest user, no input from Nick needed.  For case 2: Nick needs to allow me to pass arguments into the textarea element. ( I think this is another issue, but I cant find it)

I will fix WORK4, EMPLYR1, WORK7, and EMPLYR2.

UPDATE. EMPLYRSRVCE1 and EMPLYRSRVCE2 can now be strected.  But if Nick give me access to the arguments, I can set the default size.

**Comment by danielruss** [comment]
input boxes are wider.
