### ISSUE TITLE
Bold text needed

### ISSUE THREAD

**Issue by ashreves** [episphere/quest#122]
Entire question text should not be in bold but specific words therein should be in bold, see the questionnaire word document. Currently, the entire questions appear in bold. This is not just a style issue; is necessary for accuracy of responses.

See BLOODCLOT. It is important to have the words "first" and "blood clots (deep vein thrombosis, pulmonary embolism)" in bold

**Comment by ruggz13** [comment]
fixed all unbolded words and added bolded words
