### ISSUE TITLE
Module 2: If/Go to

### ISSUE THREAD

**Issue by meekk1** [episphere/quest#124]
An examples is in Module 2:

Work Activities - - [IF WORK= 00, GO TO INTROSITTING]

**Comment by danielruss** [comment]
@meekk1  In this example you want to display the WORKACT grid if WORK=1.  Following the example in the WIKI

|grid|id=LALAL displayif=equals(WORK,1)|....|

This was actually the grid we used as a test case, so I have a working example for this (without the displayif though)

**Comment by danielruss** [comment]
|grid|id="TESTGRID1"|During the past 12 months, about how much time do you usually spend doing these activities while you are at work? When thinking about your answers, please think about the time you spend at your job, not counting time traveling to and from work. If you exercise during your workday (such a going on walks during breaks or working out on lunch breaks), please include those activities.|
 [ [Q1] Sitting with small arm movements (for example, desk or computer work, light assembly, driving, etc.);
 [Q2] Standing with some walking (for example, as a store clerk, filing, making copies, walking to/from meetings, working on an assembly line, etc.);
 [Q3] Walking and carrying materials weighing less than 50 pounds (for example, delivering mail, waiting tables, light construction, janitorial work, etc.);
 [Q4] Walking and heavy manual work often working with materials weighing over 50 pounds (for example, digging and shoveling, chopping wood, laying bricks, stacking hay, or other heavy manual labor, etc.);
 ] | "(0:None)
 (1:Less than 30 min)
 (2:30 min) 
 (3:45 min) 
 (4:1 hr) 
 (5:1 to 2.9 hrs) 
 (6:3 to 4.9 hrs) 
 (7:5 to 6.9 hrs) 
 (8:7 to 8.9 hrs)
 (9:9 hrs or more)|

**Comment by danielruss** [comment]
Let me know if you have any problems with this

**Comment by meekk1** [comment]
Thanks, but what about [IF WORK= 00, GO TO INTROSITTING]

What is the syntax to go to another section (in this case INTROSITTING)

**Comment by danielruss** [comment]
That is the next question.  If you hide WORKACT, INTROSITTING is the next question

**Comment by meekk1** [comment]
I see. Thanks.
