### ISSUE TITLE
Module 2: If/Exclude

### ISSUE THREAD

**Issue by meekk1** [episphere/quest#125]
Module 2 in Household Chores, Caring for Others, and Shopping:

[IF WORK =01, FILL “outside of work” IN HOUSE1. **IF WORK = 00, EXCLUDE IN HOUSE1.]**

**Comment by danielruss** [comment]
This should be a standard |displayif=equals(WORK,0)|outside of work|

let. me know if this works

**Comment by meekk1** [comment]
that works
