### ISSUE TITLE
Module 2: Displayif for Grid responses

### ISSUE THREAD

**Issue by meekk1** [episphere/quest#126]
Module 2 example:

[ONLY DISPLAY ITEMS IN HOUSE2 THAT =/= “NEVER” OR NON-RESPONSE IN HOUSE1]

**Comment by hzhao392** [comment]
@meekk1 @ruggz13 please discuss the details of this

**Comment by hzhao392** [comment]
being worked on along with https://github.com/episphere/quest/issues/191

**Comment by meekk1** [comment]
@hzhao392 I'm having several issues with this section. I created a gist and detailed each issue in this document. Thanks.

https://gist.github.com/meekk1/a2e18f640547b74dbb4b114918b49b7f

**Comment by meekk1** [comment]
related to https://github.com/episphere/quest/issues/130

**Comment by hzhao392** [comment]
[Module.2.Displayif.for.Grid.responses.docx](https://github.com/episphere/quest/files/5405885/Module.2.Displayif.for.Grid.responses.docx)

Response to this, some of them are not currently supported

**Comment by meekk1** [comment]
How to do display if on HOUSE2 for grid responses from HOUSE1 that do not equal NEVER? Do grid columns like “NEVER” or “Every day” need variables to reference them later?

**Need to add properties grid database values.**
