### ISSUE TITLE
Module 3 - Skip logic issue

### ISSUE THREAD

**Issue by joshid-ims** [episphere/quest#127]
2.	|__|__| #Days smoked in past 30 days  -> CIG9A
When executed, it shows as:

 
![image](https://user-images.githubusercontent.com/64986739/85291267-48d8fd00-b468-11ea-9650-0c69af5fc10a.png)

 
![image](https://user-images.githubusercontent.com/64986739/85291291-50000b00-b468-11ea-8280-50316e7240fa.png)

This is ok if both go to the same question but will not work if they direct to different questions.

**Comment by danielruss** [comment]
I think you need to add a very complex DISPLAYIF to questions CIG9B, CIG9D, and CIG9C (note that my order is correct)

displayif=or( equals(CIG4,1),  
                       or(  and(or(equals(CIG4,2),or(equals(CIG4,3),equals(CIG4,5)),equals(CIG5,2) ),
                              and(or(equals(CIG4,2),or(equals(CIG4,3),equals(CIG4,5)),
                                     and(equals(CIG5,3),equals(CIG8C,1)
                                     ) 
                           )
                     )

Sorry about the complexity.  I tried to indent to make it easier. I'll try to decode it for you. 

1.  Either CIG4=1 or... case2. [ case 2 is the or ( and...,and...)
2.  either CIG4=2 or  CIG4=3 OR CIG4=5 AND CIG5=2. [this is the and( ...,equals(CIG5,2)]. OR
3.  either CIG4=2 or  CIG4=3 OR CIG4=5 AND CIG5=3 AND. CIG8C=1

let me know if you are having trouble with it.

**Comment by danielruss** [comment]
@joshid-ims did this answer your question?
