### ISSUE TITLE
Module 3- If-then-else syntax

### ISSUE THREAD

**Issue by joshid-ims** [episphere/quest#128]
3.	Can you please add syntax of if-then-else  statements in WiKi?

[IF CIG5 = 01 or NO RESPONSE, fill “smoke” and “do”
IF CIG5 = 02 or 03, fill “smoked” and “did”]

[CIG9A?] On days that you smoke|displayif=Or(equals(CIG5,2), equals(CIG5,3))|d|, - this does not work

**Comment by danielruss** [comment]
Thank you @joshid-ims  checking it out

**Comment by danielruss** [comment]
Hi @joshid-ims ,
   The documentation is correct, however, I think there is a bug in the code.  

I was able to reproduce your error, but first, the function is "or" not "Or", 

In your example there is whitespace in between the comma and the second equals in the or:

`|displayif=or(equals(CIG5,2), equals(CIG5,3))|d|`
When I remove the space, it works.  However, this is a bug as the space should not matter.  

Here is a minimal working example for your bug...

`
[CIG5] enter a number |__|__|

[CIG9A?] On days that you smoke|displayif=or(equals(CIG5,2),equals(CIG5,3))|d|  this does not work

[END,end]
`
Nick should be able to get this up and running quickly...

**Comment by joshid-ims** [comment]
[IF CIG5 = 01 or NO RESPONSE, fill “smoke” and “do”
IF CIG5 = 02 or 03, fill “smoked” and “did”]

I still do not know how to script the code for do/did.

**Comment by joshid-ims** [comment]
Another complex logic I am struggling with is

IF (CIG4 = 01) OR ((CIG4 = 02, 03, OR 04) AND CIG5 = 02 AND CIG7B = 01) OR ((CIG4 = 02, 03, OR 04) AND CIG5 = 03 AND CIG8C = 01), GO TO CIG10
ELSE, GO TO CIG9B

**Comment by danielruss** [comment]
|displayif=equals(isDefined(CIG5,1),1)|smoke||displayif=or(equals(isDefined(CIG5,1),2),equals(isDefined(CIG5,1),3))|smoked|

**Comment by danielruss** [comment]
Can you open that next question as a new issue?

**Comment by ruggz13** [comment]
Conditional IF added to the wiki
