### ISSUE TITLE
Module 2: Piped text from Grid responses

### ISSUE THREAD

**Issue by meekk1** [episphere/quest#130]
Module 2 example:

[Piped text instructions for HOUSE2:
If only 1 of HOUSE1A - HOUSE1E =/= 01, fill “this” and “activity” and “this activity”
If >1 of HOUSE1a – HOUSE1E =/= 01, fill “these” and “activities” and “each activity”]

**Comment by danielruss** [comment]
Have you tried the conditional text?
|displayif=equals(id,1)|this||displayif=greaterThan(id,2)|

note: HOUSE1A-HOUSE1E is not a valid id. 
also the syntax might be...
|displayif=equals(difference(HOUSE1A,HOUSE1E),1)|this||displayif=greaterThan(HOUSE1A,HOUSE1E,1)|

**Comment by danielruss** [comment]
Let me know if this resolves you problem

**Comment by meekk1** [comment]
I've tried both ways with no luck. It allows me to fill out the grid but once I press next, the HOUSE2 question does not appear. SIDENOTE: < #NR-> LAWN1 > is showing up on every page

![image](https://user-images.githubusercontent.com/64271614/85320657-653d5f80-b491-11ea-9e05-9eefe0dd704f.png)

**Comment by danielruss** [comment]
can you make a gist containing your markdown.  

goto to https://gist.github.com/; copy/paste your markdown; send me the link

**Comment by meekk1** [comment]
https://gist.github.com/meekk1/a37a52d2eb05a16940d515667c872ae3

**Comment by danielruss** [comment]
did you see my response in the gist?

**Comment by danielruss** [comment]
@ruggz13 Grids cannot handle conditional text.  The issue is that the regex for a grid has 

|grid|PART1|PART2|PART3|PART4| where each part cannot have a pipe.   If you have conditional text, it's format is |displayif...|.   

Maybe in a grid, make conditional text another character that after you make the grid you convert into a pipe?

**Comment by danielruss** [comment]
similar to #126

**Comment by hzhao392** [comment]
@meekk1 @ruggz13 please discuss the details of this

**Comment by meekk1** [comment]
this was the gist Daniel was helping me with back in June: https://gist.github.com/meekk1/a37a52d2eb05a16940d515667c872ae3

**Comment by meekk1** [comment]
@hzhao392 Can conditional text like display if statements for "this" or "these" be incorporated into grids? Back in June, Daniel said is wasn't possible yet.

This gist has the whole section in it: https://gist.github.com/meekk1/a2e18f640547b74dbb4b114918b49b7f

**Comment by meekk1** [comment]
@hzhao392 The whole section is linked in the gist above.
2 issues here - - 
a. If no response for HOUSE1, HOUSE2 should be skipped and user should be taken directly to LAWN1. But since Grids can't be skipped, HOUSE2 should have a displayif to only display if HOUSE1 has been answered.

b. If/fill for grid responses - [Piped text instructions for HOUSE2:
If only 1 of HOUSE1A - HOUSE1E =/= 01, fill “this” and “activity” and “this activity”
If >1 of HOUSE1a – HOUSE1E =/= 01, fill “these” and “activities” and “each activity”]

I tried your suggestion of doing it like this: displayif=or(equals(SEX,1),equals(SEX,3))]Finasteride

With these 2 parameters, HOUSE2 doesn't render at all. HOUSE2 grid renders with just the columns.

`[HOUSE2, displayif=equals(HOUSE1A,1)] On the days that you did |displayif=or(equals(HOUSE1A,1)equals(HOUSE1E,1))|this||displayif=or(equals(HOUSE1A,2)equals(HOUSE1E,2))|these| household or shopping |displayif=or(equals(HOUSE1A,1)equals(HOUSE1E,1))|activity||displayif=greaterThan(HOUSE1A,HOUSE1E,2)|activities|, about how much time per day did you spend doing |displayif=or(equals(HOUSE1A,1)equals(HOUSE1E,1))|this activity||displayif=or(equals(HOUSE1A,2)equals(HOUSE1E,2))|each activity|?`

![image](https://user-images.githubusercontent.com/64271614/96619088-bb9d9c00-12d3-11eb-9b73-07c86c3d4c5e.png)

**Comment by hzhao392** [comment]
[grid_answer_id.docx](https://github.com/episphere/quest/files/5411014/grid_answer_id.docx)

@meekk1 please take a look at the sample input and the display if condition attached. The grid answers are formed slightly differently. Since it is an array the rows will be A, B, C, D like you mentioned. However the columns will need to attach _ and the column number starting with 0. The screenshot should give you a better understanding

**Comment by meekk1** [comment]
This is still an issue:
a. If no response for HOUSE1, HOUSE2 should be skipped and user should be taken directly to LAWN1. But since Grids can't be skipped, HOUSE2 should have a displayif to only display if HOUSE1 has been answered.

Which is this portion: `[HOUSE2, displayif=equals(HOUSE1A_0,1)] On the days that you did`
The display if statement is referencing HOUSE1 in its entirety, not just an individual row, right? If that is true, should the display if statement be something like `[HOUSE2, displayif=equals(HOUSE1,1)] On the days that you did` or `[HOUSE2, displayif=equals(grid_HOUSE1,1)] On the days that you did`
--But neither of those work

For b. If/fill for grid responses - [Piped text instructions for HOUSE2:
If only 1 of HOUSE1A - HOUSE1E =/= 01, fill “this” and “activity” and “this activity”
If >1 of HOUSE1a – HOUSE1E =/= 01, fill “these” and “activities” and “each activity”]

It looks a little bit better here: https://gist.github.com/meekk1/a2e18f640547b74dbb4b114918b49b7f
HOUSE2 renders with fill “these” and “activities” and “each activity”. But I'm having trouble rendering for the opposite (“this” and “activity” and “this activity”)

**Comment by meekk1** [comment]
@ashreves Hi Alaina, can this be the potential solution for this issue?

To avoid putting additional time into creating logic for: 

Piped text instructions for HOUSE2:
If only 1 of HOUSE1A - HOUSE1E =/= 01, fill “this” and “activity” and “this activity”
If >1 of HOUSE1a – HOUSE1E =/= 01, fill “these” and “activities” and “each activity”

Can the text read:

**[HOUSE2] On the days that you did [these] household or shopping [activities], about how much time per day did you spend doing [each activity]?**
