### ISSUE TITLE
Module 3 - Flow of logic

### ISSUE THREAD

**Issue by joshid-ims** [episphere/quest#131]
For:

How many days have you used e-cigarettes or other vaping devices for nicotine or tobacco in your entire life?
(1) 10 or less ->  CIGAR1
(2) 11—49 -> CIGAR1
(3) 50—99
(4) 100 or more
<#NR ->  CIGAR1>

It always goes to CIGAR2 and not to CIGAR1. Maybe because of displayif statement?

[CIGAR1, displayif = equals(TOBACCO,3)?] The next questions are about your use of cigars, cigarillos, or little filtered cigars. Some of the most popular brands include Macanudo, Romeo y Julieta, Black and Mild, Swisher Sweets, Prime Time, and Cheyenne. 

How many cigars, cigarillos, or little filtered cigars have you smoked in your entire life? 
(1) 10 or less -> CHEW1
(2) 11—49 -> CHEW1
(3) 50—99
(4) 100 or more
<#NR -> CHEW1> 

[CIGAR2?] How old were you when you first smoked cigars, cigarillos, or little filtered cigars? 
(Or, if it is easier to remember the year, enter that here.) 
|__|__| Age first smoked cigars, cigarillos, or little filtered cigars
|__|__|__|__| Year first smoked cigars, cigarillos, or little filtered cigars
<#NR -> CIGAR3>

**Comment by danielruss** [comment]
The logic that the questionnaire developers use (i.e. using displayif's) is not one that I love with quest.  As I suggested in the #129, use the "arrow logic" to send to this question.  

Note: if you use my suggestion, ECIG1 becomes. 

How many days have you used e-cigarettes or other vaping devices for nicotine or tobacco in your entire life?
(1) 10 or less
(2) 11—49 
(3) 50—99 -> ECIG2
(4) 100 or more -> ECIG2

If you select 1 or 2, it goes to the next item in the question queue, which could be CIGAR1 or maybe CURRSM.  The added bonus is that if you jump to. CURRSM you dont have to go through all the questions in order and decide whether or not to display.  This btw is why loops are soooo slooooow....

**Comment by danielruss** [comment]
@joshid-ims did I answer your question?

**Comment by joshid-ims** [comment]
Daniel,

 The next question is ECIG2. So with your suggestion, no matter what user selects, it will always go to ECIG2. Which is not right.

**Comment by danielruss** [comment]
In question [TOBACCO]. we asked about what you smoke. (CIGS,ECIGS,PIPE,...).  Let's say you selected ECIG and PIPE.  If you set up TOBACCO like I suggested,  you should have a queue that conatains

ECIG1, PIPE1, and CURSM

So you go to ECIG1 next. The queue now looks like [PIPE1, CURSM]  using my logic above, if you select 1 or 2,  the next question would be  PIPE1.  If you select 3 or 4, ECIG2 is added to the queue and you now have [ECIG2, PIPE1, and CURSM].
