### ISSUE TITLE
Module 2: If/ fill for more than 2 responses

### ISSUE THREAD

**Issue by meekk1** [episphere/quest#133]
EXERC - - If EXEREC2A-EXEREC4O = 1 SEASON, FILL [season] FOR EXEREC3A-EXEREC4O
IF EXEREC2A-EXEREC4O = 2 SEASONS, FILL [seasons] FOR EXEREC3A-EXEREC4O
IF NO RESPONSE TO EXEREC2A-EXEREC4O, FILL [seasons] FOR EXEREC3A-EXEREC4O

**Comment by danielruss** [comment]
As I mentioned in #129, I hope the logic you choose is the "question with follow up questions" and not just use the displayif syntax.

This simplifies to if EXEREC2A has multiple choices or no response, display an "s".

Nick,  I don't think we have a knownFunction for length or numberOfChoices selected.  Up to you how to handle this case.

**Comment by ruggz13** [comment]
[EXEREC2A] In which season(s) did you walk or hike for exercise? Select all that apply.
[1]Winter
[2]Spring
[3]Summer
[4]Fall

[EXEREC3A] During the season|displayif=or(greaterThan(numberOfChoicesSelected(EXEREC2A,0),1),equals(numberOfChoicesSelected(EXEREC2A,0),0))|s| in the past 12 months that you walked or hiked for exercise, about how often did you do this activity?
(1)Once a month or less
(2)2-3 days a month
(3)1-2 days a week
(4)3-4 days a week
(5)5-6 days a week
(6)Everyday

**Comment by ruggz13** [comment]
numberOfChoicesSelected takes two arguments. The first argument is the ID of the question you want to count how many of the choices are selected. The second arguments can be any number (it is not used, but the syntax asks for a second argument). It will return the number of current selected responses for the given question.
