### ISSUE TITLE
Module 2: Minutes drop down in 5 min increments

### ISSUE THREAD

**Issue by meekk1** [episphere/quest#135]
[SLEEP1A] What time do you usually go to bed on [the nights before workdays/most days]? Please tell us the time you usually get into your bed, not the time you usually fall asleep. Select your answer using the drop-downs below.

**HH:MM AM/PM**
	NO RESPONSE  GO TO SLEEP1D

[IF SLEEPSCHA=01, FILL “nights before workdays”. IF SLEEPSCHA=00, NON-RESPONSE, FILL “most nights”]	
**[“Minutes” drop-down category displayed in 5-minute increments]**

**Comment by danielruss** [comment]
@ashreves I'm not sure what the questionnaire authors meant.  Do they want from 12AM-12:05AM, 12:05-12:10 ...  through daytime ... though night time ... 11:55PM-12:00AM? 288 different choices?

**Comment by danielruss** [comment]
never mind @ashreves  I understand now

**Comment by danielruss** [comment]
Nick,  I don't think we have a regex for a dropdown.  I know we have state.  But this is minutes,  
0-4,5-9,10-14,55..59 minutes.  How would a user provide the "options" for a select. And yes, we need to make sure it updates the value of the question/inserted into the LF....

**Comment by hzhao392** [comment]
@ashreves  please follow up with Michelle

**Comment by ashreves** [comment]
@ruggz13 After talking with Michelle and Neal, we agree that 5-minute intervals and drop-down menus might be over complicating things. 

For this item and other questions about time in Module 3, please change the format to whatever way is easiest for participants to complete. We do want time on a 12-hour scale with AM and PM, but we are okay with picking from a drop-down, fill in the blank, or another type of question type. 1 minute increments are fine.

**Comment by danielruss** [comment]
stale issue ... closing
