### ISSUE TITLE
Module 4: Images

### ISSUE THREAD

**Issue by meekk1** [episphere/quest#136]
Example:
![image](https://user-images.githubusercontent.com/64271614/85293217-0a910d00-b46b-11ea-9e1c-b7aaf23c7a23.png)

**Comment by danielruss** [comment]
The syntax is in the wiki.  |image|URL|height,width|    note:  the URL should be to the image in github.  let me know if you need help getting the photo out of the word file and into github.

example from Module 1.
|image|episphere.github.io/quest/images/FemaleBaldness-update.png|300,500|

**Comment by meekk1** [comment]
I'm guessing this is the url:
![image](https://user-images.githubusercontent.com/64271614/85293217-0a910d00-b46b-11ea-9e1c-b7aaf23c7a23.png)

And how do I find out the size?

**Comment by ruggz13** [comment]
You can set whatever size you want the image to be (in pixels). Make sure the URL does not include https://, as noted in the wiki

**Comment by danielruss** [comment]
the image should just be the picture on the right.
