### ISSUE TITLE
Module 4: Looping syntax

### ISSUE THREAD

**Issue by meekk1** [episphere/quest#139]
[HOMEADD1] Looping for user to input address up to 11 times

**Comment by danielruss** [comment]
\<loop max=11\>
   [Q1] ....
\</loop\>


This is in the wiki.  Waiting to hear back on #143 and similar to #144

**Comment by hzhao392** [comment]
Will follow up with IMS and see if it renders properly @meekk1

**Comment by meekk1** [comment]
This does not render properly. Below is the beginning of my markup and screenshot. As you can see in the screenshot, after the HOMEADD1 question "What is the full street address of the place where you live now?", a text field is given for the user to enter text. This shouldn't happen since the user needs to fill out multiple text fields for the addresses. This issue occurs for all questions in this looping example. 

City and State are both identical but City is text and State renders as numerical. Country doesn't give a line to write text. The loop also does not work as intended. 

https://gist.github.com/meekk1/7e2473078e3aa3fbff786ceaea7385d7

![image](https://user-images.githubusercontent.com/64271614/93928767-d7b81880-fce8-11ea-9ceb-be4c2dce0346.png)

**Comment by hzhao392** [comment]
We will check if this is related to https://github.com/episphere/quest/issues/147

**Comment by meekk1** [comment]
current gist: https://gist.github.com/meekk1/7e2473078e3aa3fbff786ceaea7385d7

@hzhao392 I'm having a few issues here:

a. displayif statements for each address iteration is needed to avoid having to do a loop OR you could ask the user after each address iteration something like:
`[TEST3_1] Do you have additional addresses to enter?
(1) Yes -> HOMEADD1_1_2
(2) No -> HOMEADD4_1`

--This extra question works in Quest to take the user to the next address iteration if they select Yes or to take them to the address summary if they select No. **Do you want this to have a displayif for each address iteration or a question like is shown above?**

b. Input fields that include an id like `|__|__|id=STNUM|Street number` doesn't follow the numeric or free text information in the wiki: 
Numeric : 
![image](https://user-images.githubusercontent.com/64271614/96739606-f6fca100-138d-11eb-9ff8-938f7a62b2a0.png)

Free Text: |__| - Pipe, underscore, underscore, pipe, indicates a free text response that is limited to a single line. Note, length of line is indeterminate unless otherwise specified.
![image](https://user-images.githubusercontent.com/64271614/96738578-dda72500-138c-11eb-8e77-840ba91b9d85.png)

c. There's an extra input field that shows after every question. This is a numeric field so the user can't put their full address even if they wanted to.
![image](https://user-images.githubusercontent.com/64271614/96739104-6de56a00-138d-11eb-98fb-c7c0324b9e75.png)

**Comment by meekk1** [comment]
Gist to ask user if they have more addresses to enter: https://gist.github.com/meekk1/cd8c9d46f67ced24f42e03de2f51221e

**Comment by hzhao392** [comment]
@ashreves Krystal brings up a good solution, instead of looping the address question 11 times, can we ask them if they have another address after each entry. If they do then we proceed with the next address. If they don't, we skip to the end

The sample markup looks something like this:

[HOMEADD3_1?] Please provide the cross streets that make up the intersection that is nearest to this address: 
|__|id=STRNAME1| Full Street name #1
|__|id=STRTNAME1| Full Street name #2
(77) Don't know

[TEST3_1] Do you have additional addresses to enter?
(1) Yes -> HOMEADD1_1_2
(2) No -> HOMEADD4_1

[HOMEADD1_1_2?] Please provide the cross streets that make up the intersection that is nearest to this address:
|__|id=STRNAME2|Full Street name #1
|__|id=STRTNAME2| Full Street name #2
(77) Don't know

[TEST3_2] Do you have additional addresses to enter?
(1) Yes -> HOMEADD1_1_3
(2) No -> HOMEADD4_1

[HOMEADD4_1?] Here is a summary of the information you gave us for this location:

**Comment by meekk1** [comment]
Instead of a loop, maybe we can ask the user after every address if they had another entry? This would continue for up to 11 times.
If they have another entry, they are taken to the next address iteration. If not, they are taken to the address summary.
![image](https://user-images.githubusercontent.com/64271614/96889804-f8dd6780-1454-11eb-975b-a8915f7ec2cb.png)

**Comment by ashreves** [comment]
@meekk1 @hzhao392 So as far as functionality goes, this would be no different for the users? Would anything about the order of questions change?

**Comment by meekk1** [comment]
That is something to consider. 

I think this question below should probably be moved up and asked right after HOMEADD1(where the user lives now)
```
[HOMEADDOTH?] Within the past 20 years, have you lived anywhere else for two years or longer?
(1) Yes -> HOMEADD1_1_1
(2) No -> HOMEADDSUM
< -> HOMEADDSUM >
```
And then after each address entry, the user will be asked if they have more entries to add.

HOMEADD2 and HOMEADD3 are only supposed to be asked if the user skips certain fields in HOMEADD1 so those two questions will need displayif statements. But overall functionality would remain the same.

**Comment by hzhao392** [comment]
@ashreves 

Alaina, @meekk1 is saying the The order of questions is like this:
The current address is asked. 
Then HOMEADDOTH is asked. " Within the past 20 years, have you lived anywhere else for two years or longer?"
If yes then address2 is asked
Then do you have additional address to enter
If yes, then address3 is asked
Then do you have additional address to enter
If yes, then address4 is asked
Then do you have additional address to enter
etc, up to 11 times.

**Comment by danielruss** [comment]
stale issue ... closing
