### ISSUE TITLE
Module 4: Loop until No is selected

### ISSUE THREAD

**Issue by meekk1** [episphere/quest#141]
[REPEAT HOMEADD4 AND HOMEADDOTH UNTIL RESPONDENT SELECTS NO AT HOMEADDOTH. SHOW HOMEADD1 – HOMEADD3 UP TO 11 TIMES]

**Comment by danielruss** [comment]
you can use the standard loop syntax.  However, in question HOMEADDSUM. you may break out of the loop.  use <loop max=11>
