### ISSUE TITLE
Module 4: If/ repeat

### ISSUE THREAD

**Issue by meekk1** [episphere/quest#143]
Syntax for FOR ALL RESPONSE OPTIONS: IF LAST ADDRESS PROVIDED, GO TO INTROSH. IF NOT LAST ADDRESS PROVIDED, REPEAT HOMEWTR1 – HOMEWTR3 FOR EACH ADDRESS PROVIDED.

![image](https://user-images.githubusercontent.com/64271614/85296414-5a71d300-b46f-11ea-91dd-e53eb2b8e639.png)

**Comment by danielruss** [comment]
@ashreves Is it possible to move the water question into the loop with the address.  So, ask address, then move in, (move out if not first address), then water question, then goto next address.  It would be difficult to synchronize the questions.  We have questions HOMEADD1_1, which is HOMEADD1 for the first address ... HOMEADD1_5 for the 5th address.  If they are in different loops, it would be difficult to have HOMEWTR3_2 know that HOMEADD1_2 matches in the markdown.

**Comment by ashreves** [comment]
@danielruss I understand what you are saying, but out content experts specifically wanted the order as is. They felt strongly that it was easier for people to recall and accurately recall all of their addresses if they do that first and not loop through the other questions intervening. These questions were designed based on patterns that have worked in their prior residential history surveys.

**Comment by hzhao392** [comment]
Will discuss with IMS

**Comment by hzhao392** [comment]
How does address from previous question get added in this question, and possibly multiple questions from loops

**Comment by ashreves** [comment]
@hzhao392 The question text should look like this...

![image](https://user-images.githubusercontent.com/54043164/94695056-75bc6c00-0303-11eb-9ca7-c263e5afef06.png)


Reference the NORC Qualtrics module if you are interested in seeing a preview of what we were looking for.

**Comment by hzhao392** [comment]
@meekk1 lets try to render this question set without a loop first, if we can render it, we will then clone the question up to 10 more times. This way we are not adding additional functionalities to the loop that does not exist yet
