### ISSUE TITLE
Module 1 - Can still enter age older than current age for medical conditions

### ISSUE THREAD

**Issue by ashreves** [episphere/quest#145]
For medical conditions, can still a year older than current age. Please refer to age limits on word document

Error message currently reads that values must be equal or less than 72, regardless of current age.

**Comment by danielruss** [comment]
updated markdown.  All medical conditions have max age of the current age.

**Comment by robertsamm** [comment]
Can we do the same for sibling and child age of cancer diagnoses? Currently able to input an age of cancer diagnosis that is greater than the value put for sibling/child current age or age at death.
