### ISSUE TITLE
STATE markdown needs to handle id

### ISSUE THREAD

**Issue by danielruss** [episphere/quest#146]
@ruggz13 when I use the   |state|id=ADD1_STATE|. It doesn't handle the id properly.

Please fix the renderer

**Comment by ruggz13** [comment]
syntax as of right now is |state|ID|. Can be changed to |state|id=ID| @danielruss

**Comment by danielruss** [comment]
Would be better that |state|id=ID|. That way we can sneak in other arguments as needed.

**Comment by ruggz13** [comment]
Changed state to have options. Syntax |state|id=ID| now
