### ISSUE TITLE
ids for input elements in loops aren't mangled

### ISSUE THREAD

**Issue by danielruss** [episphere/quest#147]
Hi @ruggz13 

if you have an input field with an id inside of a loop, the id is not mangled with the loop index.

<loop max=3>
[ADD1]
 |__|__|id=STREET_NUMBER| street number 
</loop>
[END,end] la la la

Every instance of the  input tag has the same id.

**Comment by ruggz13** [comment]
So id=STREET_NUMBER should be STREET_NUMBER_#loopindex?

**Comment by danielruss** [comment]
yes, but hold on a sec.  There is a rub.  

\<loop max=3\>
[ADD1]
 |\__|__|id=ADD1_STREET_NUMBER| street number 
\</loop\>
[END,end] la la la

THEN ADD1 becomes ADD1_1_STREET_NUMBER ????

**Comment by hzhao392** [comment]
@ruggz13 please discuss with @danielruss

**Comment by danielruss** [comment]
@hzhao392  here is the example

<loop max=3>
[HI] Hi there |__|__|id="hi_num"|
</loop>

**Comment by danielruss** [comment]
Quest now looks at all |__| id="xxx"| (also textboxes/numbers) and gets the id for loop mangling.  We still need to be care with Id naming e.g. if the question id is HI, dont call other variables HI_THERE because you may be bad mangling of variable names

<loop map=3>
   [HI] Hi there |__|__| id="hi_num"|
</loop>

should now work....
