### ISSUE TITLE
Module 1- WEIGHTHIS look odd, question text on prior page

### ISSUE THREAD

**Issue by ashreves** [episphere/quest#148]
![Weight q](https://user-images.githubusercontent.com/54043164/85330744-f406a800-b4a2-11ea-8535-f39e06d3fe66.PNG)

See WEIGHTHIS

**Comment by ruggz13** [comment]
Would this be better as a grid? @ashreves

**Comment by danielruss** [comment]
No, grids cant handle input type="number"

I have  

a. 18 years old |__|__|__|id=WEIGHTHIS1 min=0 max=999|

b. 25 years old |__|__|__|id=WEIGHTHIS2 min=0 max=999|

c. 35 years old |__|__|__|id=WEIGHTHIS3 min=0 max=999|

|displayif=greaterThanOrEqual(isDefined(AGE,age),45)|d. 45 years old | 
|__|__|__|id=WEIGHTHIS4 displayif=greaterThanOrEqual(isDefined(AGE,age),45) min=0 max=999|

|displayif=greaterThanOrEqual(isDefined(AGE,age),55)|e. 55 years old | 
|__|__|__|id=WEIGHTHIS5 displayif=greaterThanOrEqual(isDefined(AGE,age),55) min=0 max=999|

however, it loses the soft-edits.

**Comment by danielruss** [comment]
We need a way to have soft edits on the input elements as opposed to just the questions.

**Comment by danielruss** [comment]
The page looks right, but there is no soft edit. @ruggz13

**Comment by ruggz13** [comment]
No soft edit because there is no '?' can add that now... @danielruss

**Comment by ruggz13** [comment]
Added it, see if it is the desired output

**Comment by ashreves** [comment]
@ruggz13 I think that this looks better and will be easier for participants to answer. 

Can you add a soft edit if any of the spaces are left blank?

**Comment by ruggz13** [comment]
I believe that the soft edit is already in place @ashreves

**Comment by ashreves** [comment]
@ruggz13 I just tried it on mobile and it isn't working.

**Comment by ruggz13** [comment]
I just tried on mobile as well. If you leave all blank, the soft edit will pop up. If you answer just one, you can move to the next question. @ashreves

**Comment by ashreves** [comment]
@ruggz13 can we add a soft edit if you leave any of the fields blank?

**Comment by ruggz13** [comment]
Would you want them to be required? @ashreves If so, it will pop up saying you need to answer this

**Comment by ashreves** [comment]
@ruggz13 Yes, we want a soft edit not a hard edit here. Similar to the messages that appear on most other questions.

**Comment by ruggz13** [comment]
@ashreves you will need to answer these responses if they are "required" to go to the next question. They will not be able to be left blank

**Comment by ruggz13** [comment]
See #156

**Comment by ashreves** [comment]
@

**Comment by ruggz13** [comment]
Now there should be a soft edit popping up that says the number of blank questions unanswered. This will probably help with the question regarding module 4 @ashreves

**Comment by ruggz13** [comment]
Going to close for now. Can reopen if needed @ashreves
