### ISSUE TITLE
Module 1 - Issue with going back on medical condition questions and getting asked all possible age of diagnoses questions

### ISSUE THREAD

**Issue by robertsamm** [episphere/quest#153]
There is an issue where I answered the module up to STD questions then went back to the beginning of the medical questions using back button. When I did so I was asked questions about age of diagnosis for medical conditions I did not say that I had. 

For example, for cardiovascular diseases I only said I had cholesterol and arrythmia. After answering those two I went back and was asked age I was diagnosed with B-12, stroke, etc.

**Comment by danielruss** [comment]
I think this had to do with the tree clearing its children when you back up.  I fixed the tree and I can no longer reproduce this error.
