### ISSUE TITLE
Module 1 - In some places able to unclick answers but in others not, needs to be fixed so all can be unclicked

### ISSUE THREAD

**Issue by robertsamm** [episphere/quest#155]
All answers need to be unclickable so that if participants change their mind about answering a particular question they can go back and unclick the answer they originally chose. This works in some places but not others. 

For example, cannot unclick answer for OVERHEALTH and others.

**Comment by ruggz13** [comment]
Checkboxes (select more than one) are clickable and can be de-selected. Radio buttons (select only one) are unable to be de-selected. @danielruss

**Comment by danielruss** [comment]
Yeah, radio buttons are not uncheckable.  hmm....   don't have a great solution.  instead of input type=radio. use button type=button add a listener that unchecks buttons with the same name, like we do with XOR.  No a big fan of that solution though.  

Can't the user just select prefer not to answer?

**Comment by danielruss** [comment]
As a user of quest, I cannot fix this. so not a questionnaire user issue.  This needs to be worked out by engineering/management

**Comment by ruggz13** [comment]
This is a question for management

**Comment by ashreves** [comment]
@ruggz13 We'd really like users to be able to unclick radio buttons if possible.

**Comment by ruggz13** [comment]
I'm gonna go ahead and say no to this one. Radio buttons are only supposed to be able to be clicked once and only one selected at once. You would have to change all of the core quest mechanics to add this feature and change the markdown for it as well

**Comment by ashreves** [comment]
@ruggz13 I understand what you're saying, if it's a limitation then I suppose there is nothing that we can do about it. 

@MiaGaudet what do you think?

**Comment by ashreves** [comment]
@miagaudet just bumping this thread

**Comment by hzhao392** [comment]
We still need to decide on solution for this

**Comment by hzhao392** [comment]
Possibly clear button next to optional radio question

**Comment by hzhao392** [comment]
@ashreves @robertsamm  the reset button has been implemented for each question, please take a minute to test

**Comment by ashreves** [comment]
@hzhao392 The resent button seems to work. 

However, I am still not sure that this is the best way to address the issue. Will the button appear as is for participants? Is it still not possible for participants to double click a response to deselect?

**Comment by hzhao392** [comment]
Hi @ashreves The reset button will appear as is like the back and next buttons. radio buttons are not designed to be deselected. What I did was reset the entire form to get it to clear out the selection. You can find some more information on deselecting it here:

https://ux.stackexchange.com/questions/13511/why-is-it-impossible-to-deselect-html-radio-inputs

**Comment by hzhao392** [comment]
I forgot to add, right now the reset button is shown in all questions, I can add a condition where it only shows up in questions with radio buttons

**Comment by danielruss** [comment]
stale issue ... closing
