### ISSUE TITLE
Module 1 - WEIGHT - Suggest a minimum weight to prevent implausible values

### ISSUE THREAD

**Issue by robertsamm** [episphere/quest#156]

**Comment by danielruss** [comment]
This is a comment for the questionnaire development team. @robertsamm @ashreves  Happy to set a minumum weight if you tell me what to set it to.

**Comment by miagaudet** [comment]
let's make a soft edit for less than 70 lbs and no edits to the upper end.

**Comment by ruggz13** [comment]
So set the minimum weight to 70lbs? @miagaudet

**Comment by miagaudet** [comment]
@ruggz13 no, not a minimum but a soft edit for <70lbs that states "Is this weight correct?"

**Comment by ashreves** [comment]
@miagaudet I agree with Mia, a custom soft edit would be helpful here

**Comment by ruggz13** [comment]
Custom soft edit is now in place. Check it out @ashreves @miagaudet

**Comment by ashreves** [comment]
@ruggz13 I just tested this soft edit and it did not work.

**Comment by ruggz13** [comment]
I just tested it as well and if you enter in a weight that is less than 70, it pops up a soft edit saying is this weight correct/incorrect @ashreves

**Comment by ashreves** [comment]
@ruggz13 This soft edit is not working.

**Comment by ashreves** [comment]
@ruggz13 This soft edit works when I am not on VPN, but does not work when I am on VPN (testing Chrome-PC)

**Comment by ruggz13** [comment]
Fixed VPN workaround

**Comment by ruggz13** [comment]
Fixed VPN workaround
