### ISSUE TITLE
Module 1 - HAIRFEM - Fix partial box around image

### ISSUE THREAD

**Issue by robertsamm** [episphere/quest#157]
There is a partial box around the hairloss image that only has 3 sides, so looks incomplete.

<img width="585" alt="Mod1Test_HAIRFEM_06232020" src="https://user-images.githubusercontent.com/67074735/85454412-e6b4f080-b56a-11ea-822b-8a92020de139.PNG">

**Comment by ruggz13** [comment]
Need to receive correct and final image for rendering

**Comment by danielruss** [comment]
fix to #163 will correct this issue.
