### ISSUE TITLE
Module 1 - Issue with asking age and year for mother and father cancers for some cancers

### ISSUE THREAD

**Issue by robertsamm** [episphere/quest#158]
See MOMCANC3 and DADCANC3. Some of the cancer options asked only age of diagnosis for parents. All cancer diagnoses age questions should have both age and year options as a response.

**Comment by danielruss** [comment]
@robertsamm I cannot reproduce the error you had.  However, if you selected that your mom has died, or if you don't know if she is alive, or just don't respond,  then you should not see the year of cancer diagnosis.

This might be a feature not a bug.  Please confirm.  Feel free to close the issue, or let me know how you got to the error.

**Comment by robertsamm** [comment]
@danielruss I was unable to reproduce the error either. Thanks!
