### ISSUE TITLE
Module 1 - Issue with selecting 'I know he/she had cancer. But don't know what type' & a known cancer

### ISSUE THREAD

**Issue by robertsamm** [episphere/quest#159]
See MOMCANC2 / DADCANC2 and MOMCANC3W / DADCANC3V. If I select only 'I know he/she had cancer. But don't know what type' then I get the appropriate follow up question that asks for age of cancer diagnosis for unknown cancer. However, if I select both 'I know he/she had cancer. But don't know what type' and another known cancer (e.g. bladder cancer) then I only get the follow up question of age at diagnosis for known cancer.

**Comment by danielruss** [comment]
MOM and Dad unknown cancers now work.
