### ISSUE TITLE
Module 1 - EMPLYRSRVC - There's text that says '->work4' under text box that should not be there

### ISSUE THREAD

**Issue by robertsamm** [episphere/quest#160]
See below

<img width="865" alt="Mod1Test_EMPLYRSRVCE1_06232020" src="https://user-images.githubusercontent.com/67074735/85456580-15cc6180-b56d-11ea-8101-1c3e501b8e84.PNG">

**Comment by ruggz13** [comment]
See #110

**Comment by danielruss** [comment]
@ruggz13 I fixed this yesterday by adding a new regex pattern in replace2.  Since this was an old error,I didn't know Amelia was going to add it.
