### ISSUE TITLE
Module 1 - Mobile - Too many taps/clicks necessary for one action

### ISSUE THREAD

**Issue by robertsamm** [episphere/quest#162]
When going through the module on my mobile device browser every time I had to click/tap 'next' or 'back' I had to hit it twice instead of just once. Also every time I clicked/tapped on a text box (e.g. for age) I had to click it 4+ times before my keypad would pop up in order for me to type a response. Also tried pressing and holding and that took too long too.

**Comment by ruggz13** [comment]
The reason is because the next and back button are too close to the bottom of the browser and it thinks that you are trying to pull up the browser tools. Will look into putting more space below the next and back buttons

**Comment by ruggz13** [comment]
See #171

**Comment by ruggz13** [comment]
Looks like this is just an iPhone issue. Not much we can do since it is a web app @robertsamm @ashreves

**Comment by ashreves** [comment]
@ruggz13 I understand. 

@robertsamm Can you see if the change fixed your issue?

**Comment by robertsamm** [comment]
@ashreves Yes, it looks like the change fixed my issue. Thanks!

**Comment by ruggz13** [comment]
Great! Closing
