### ISSUE TITLE
Module 1 - Mobile - Hair pattern image does not fit on the screen

### ISSUE THREAD

**Issue by robertsamm** [episphere/quest#163]
See FEMHAIR and MALEHAIR. On mobile devices the image does not automatically shrink to fit the screen.

**Comment by ashreves** [comment]
The question text did not appear in an intuitive way. I think we talked about having text appear beside images? If not, we need to have this discussion.

**Comment by danielruss** [comment]
I have the all the images from the documents that were send out back in march.  All the female and male are equal sized, although the female pictures are smaller than the male pictures.  We can adjust the questions.

**Comment by danielruss** [comment]
@ashreves  @robertsamm  I updated all the images, when you have a sec.  Please check.

**Comment by ashreves** [comment]
@danielruss is there a way to quickly get to that question? Or do we need to click through the module

**Comment by danielruss** [comment]
Give me a sec...  I'll give you url...

**Comment by danielruss** [comment]
https://episphere.github.io/quest/?questionnaires/hair.txt

**Comment by danielruss** [comment]
related to #157

**Comment by robertsamm** [comment]
@danielruss Yes, I think it looks great this way. Thanks! 
@ashreves your thoughts?

**Comment by ashreves** [comment]
Yes, this looks better.
