### ISSUE TITLE
Module 1- PC, MHGROUP9, gaps in reponses

### ISSUE THREAD

**Issue by ashreves** [episphere/quest#165]
I answered the questionnaire as an sex=INTERSEX OR OTHER and there were large gaps still present in the answer responses to the MHGROUP9 question.

**Comment by danielruss** [comment]
Too many <br>'s.   handle the spacing with CSS not <br>?

**Comment by ruggz13** [comment]
Same as #123

**Comment by ruggz13** [comment]
Fixed, I went through and tested some questions. More testing would be appreciated @ashreves
