### ISSUE TITLE
Module 1- Logic error in SIBCANC2, showing all cancer types as follow up

### ISSUE THREAD

**Issue by ashreves** [episphere/quest#167]
If I select only 'brain' for SIBCANC2 hit next, then enter date for SIBCANC3C, then hit next, and then go back to SIBCANC3C andthen go foward, I am asked follow up question for all cancer types.

**Comment by danielruss** [comment]
I think this is a duplicate of #153.  I cannot reproduce this error.  If you see it again, let us know.
