### ISSUE TITLE
Module 1- PC, text entry box size on EMPLYRSRVCE1 free response

### ISSUE THREAD

**Issue by ashreves** [episphere/quest#168]
I can stretch to make the box larger, but can only make it taller.

I would prefer to have a large box that didn't need to be stretched or a box that can be stretched at the corner and maintain height and width ratio.

![tall box](https://user-images.githubusercontent.com/54043164/85471135-0570b280-b57e-11ea-8d75-6795fc3bfec1.PNG)

**Comment by ruggz13** [comment]
Can now resize the width and the height for text area
