### ISSUE TITLE
Module 1- SSN auto format

### ISSUE THREAD

**Issue by ashreves** [episphere/quest#169]
If possible, SSN field should autoformat to include dashes when numbers are typed. See SOCIALSECUR1 and following.

**Comment by ruggz13** [comment]
SSN now autoformats to enter in dashes. Response will include these dashes

**Comment by ashreves** [comment]
@ruggz13 SSN auto format not showing up on iPhone-Firefox. It appears grey in the field but as soon as I start typing, the dashes disappear. The numbers should automatically fill the format if possible.

**Comment by ashreves** [comment]
Same issues with phone number and email in later questions asking about alternate contact information.

**Comment by ruggz13** [comment]
So when you enter the SSN click out of the box or click next, it will automatically change to dashes. If you entered number then click next, click back to see that it is saved with the dashes @ashreves

**Comment by ruggz13** [comment]
What is the issue with Phone Numbers and Email? @ashreves

**Comment by ashreves** [comment]
@ruggz13 Is there a way to add the dashes as numbers are typed? That's what most internet forms do. If that is not possible, can we have the preferred format faintly in the field as participants type over it? It is difficult as a user because it isn't clear what type of format is expected after you start typing. 

Phone number are the same issue with dashes.

I'd assume emails is an issue with @ and .com (or .other). But actually email address are the biggest issue because expected format is never given and warning message just says  "Enter an email address"

**Comment by ruggz13** [comment]
SSN is fixed as it is typed @ashreves

**Comment by ruggz13** [comment]
I can change Phone Numbers to do the same as well. What would you like the grayed out placeholder of the phone number to be? @ashreves 

Same thing with the email address

**Comment by ashreves** [comment]
@ruggz13 phone should be replaced as typed as you did with SSN.

For email, you should specify formatting similar to what Bhaumik did for the user profile

**Comment by ruggz13** [comment]
SSN and Phone #'s automatically updated. Not sure what Bhaumik did for the user profile @ashreves

**Comment by ashreves** [comment]
@ruggz13 SOCIALSECU has the old error message on iPad. Please change to a more similar issue to SOCIALSEC1

**Comment by ruggz13** [comment]
Not sure what is being asked @ashreves

**Comment by ruggz13** [comment]
I think you wanted the shortened version of SSN to be like SSN. Changed it so it has the new formatting of error message. @ashreves
