### ISSUE TITLE
Module 1- Mobile, buttons too close to native Safari navigation

### ISSUE THREAD

**Issue by ashreves** [episphere/quest#171]
![IMG_2857](https://user-images.githubusercontent.com/54043164/85474169-466ac600-b582-11ea-9a9d-a6e339600a63.PNG)

**Comment by ashreves** [comment]
Sometimes, the back and next buttons were very close to the native safari navigation buttons, You could not scroll down to make the page longer. It was easy to accidentally navigate away from the web page.

**Comment by ruggz13** [comment]
@ashreves added some space, check how it is now

**Comment by ashreves** [comment]
@ruggz13 I clicked through a few questions and I do think that it looks better.

**Comment by ruggz13** [comment]
Ok closing this

**Comment by ashreves** [comment]
Similar issues occurred when testing iPad with Chrome and device is horizontal. 

Would be better if there was additional space between 'back' and 'next' buttons and bottom of screen.

![image](https://user-images.githubusercontent.com/54043164/93811572-58f6a900-fc1e-11ea-8ecb-70a3f4ff35bc.png)

**Comment by hzhao392** [comment]
Will be resolved in PWA
