### ISSUE TITLE
Module 1- CHILD, SIB autofill to 0 does not trigger soft edit

### ISSUE THREAD

**Issue by ashreves** [episphere/quest#172]
CHILD and SIB autofills to 0. if you do not edit the 0, it lets you hit 'next' without triggering a soft edit.

can the autofill be blank and ask for a response if nothing is entered?

**Comment by ruggz13** [comment]
In the word doc, if you do not enter any SIB or CHILD it says to autofill 0

**Comment by ashreves** [comment]
@ruggz13 Hm. I see what you mean. I still think that there should be a soft edit if they never edit the field. 

@miagaudet What do you think?

**Comment by miagaudet** [comment]
@ashreves I agree a soft edit seems appropriate.

**Comment by ruggz13** [comment]
What would the soft edit wording be? @ashreves @miagaudet

**Comment by ashreves** [comment]
@ruggz13 So looking at it now, I can see that it already has a check since you have to confirm you answer on the next page. 

I suppose what I don't like about it is that you have to backspace the prefilled 0 to enter your value.

**Comment by ashreves** [comment]
@ruggz13 I see that you closed the issue, but the problem about having to backspace has not been fixed. 

Is there a way we can get around having to backspace over the 0 to enter a value?

**Comment by ashreves** [comment]
@hzhao392 I am going to reopen this issue due to my last comment.

**Comment by ashreves** [comment]
lreated to this, but There is currently a hard edit on CHILD and SIB that do not allow you to move forward unless an answer is given. 
If  you do not fill out these questions, you should be able to skip forward with a soft error message.

**Comment by ruggz13** [comment]
@ashreves @hzhao392 pushed a fix in Quest and updated the markup for it. Tested it as well and everything seems to work fine

**Comment by danielruss** [comment]
stale closed
