### ISSUE TITLE
Module 1- Mobile, Hit back after EMPLYRSRVCE, brought to blank screen

### ISSUE THREAD

**Issue by ashreves** [episphere/quest#174]
After EMPLYRSRVCE error showed up, I tried to select 'next' but couldn't. I then selected 'back' to change a response and was left with a blank screen. 

There were no buttons so I refreshed the page and was brought back to the beginning of the questionnaire.

**Comment by danielruss** [comment]
I think this may be related to #153 and #167.  I can't reproduce.  Will run test again tomorrow.

**Comment by danielruss** [comment]
Still works for me.  I think this is fixed.
