### ISSUE TITLE
Device testing needed

### ISSUE THREAD

**Issue by ashreves** [episphere/quest#175]
Amelia tested with an iPhone6s, I tested with an iPhone 11. 

There were clear differences in how the questionnaire appeared on our different phones. Although both phones were updated with the latest operating system, the variation could be due to screen size. 

Eventually, we will also need to test using Android phones and various types of tablets.

**Comment by danielruss** [comment]
I have an android (moto z3).  Happy to test on it.  I'm not sure who should this should be assigned to???

**Comment by ashreves** [comment]
@danielruss Is there a way to display the mobile view on a computer? The Qualtrics survey was able to show both views so it was faster to test. If this is just a Qualtrics tool, I understand.

**Comment by ruggz13** [comment]
If you are using Chrome, you can open up the developer tools and you can toggle the device toolbar in the top left corner of the dev tools. It looks like a mobile phone and an iPad button

**Comment by miagaudet** [comment]
Also, I am working on ordering tablets based on DevOps recommendations.

**Comment by hzhao392** [comment]
@ashreves can we close and add this to PWA

**Comment by danielruss** [comment]
stale closed
