### ISSUE TITLE
Module 1- Clunky on mobile

### ISSUE THREAD

**Issue by ashreves** [episphere/quest#176]
Overall, the module was clunky on my mobile device. The text was hard to read and I found it really easy to lose my place in the question.

I know that style will be more on the UI/UX person, but since since most of our participants will use a tablet or phone instead of a computer, it would be great if any small improvement could be made now.

This also applies to future programming of questions with grids and images.

**Comment by danielruss** [comment]
@ashreves I agree.  Maybe we should discuss styling as a group.  There may be some stuff we can do without the UI/UX person.  Let's not expect them to be super-person and fix all our problems.

**Comment by ashreves** [comment]
@danielruss I think a discussion would be helpful.

**Comment by hzhao392** [comment]
@ashreves can we close this and move to PWA
