### ISSUE TITLE
Module 3: Click or hover on word to see informational text

### ISSUE THREAD

**Issue by meekk1** [episphere/quest#178]
Module 3: Marijuana

Not able to click/hover on regular basis to view informational text. Also text after informational text shows up within the same box.
![image](https://user-images.githubusercontent.com/64271614/85890852-2cb4c300-b7bc-11ea-9a66-4401f296142d.png)

[SMMAR3?] How old were you when you started smoking marijuana on a regular basis? |popup|Informational Text|Regular Basis|We understand that the meaning of "regular basis" might be different for different people. When you answer this question, please think about what "regular basis" means to you.

(Or, if it is easier to remember the year, enter that here.) 
|__|__| Age started smoking marijuana on a regular basis 
|__|__|__|__| Year started smoking marijuana on a regular basis
[1] Never smoked on a regular basis 
< #NR -> SMMAR4> 

related to https://github.com/episphere/quest/issues/21

**Comment by danielruss** [comment]
@ruggz13  is fixing some of our spacing issues so the look make change.  The following code works for me:

https://gist.github.com/danielruss/dd4cffa61f54af73d3d92e8f7ab49194

**Comment by meekk1** [comment]
Ok, thanks. That turns regular basis into a button but nothing happens when I click it.

**Comment by danielruss** [comment]
you dont see a popup window

**Comment by danielruss** [comment]
<img width="719" alt="Screen Shot 2020-06-26 at 3 07 48 PM" src="https://user-images.githubusercontent.com/3767675/85892443-eca30f80-b7be-11ea-8e9a-bd87f37efc73.png">

**Comment by meekk1** [comment]
No, I copied your gist. I click it and nothing happens.
![image](https://user-images.githubusercontent.com/64271614/85892647-4dcae300-b7bf-11ea-88ef-8484781fbc34.png)

**Comment by meekk1** [comment]
it works with this
![image](https://user-images.githubusercontent.com/64271614/85893745-7227bf00-b7c1-11ea-9984-e03152f8054f.png)

Closing
