### ISSUE TITLE
Module 3- Unfolding Age Range questions

### ISSUE THREAD

**Issue by joshid-ims** [episphere/quest#179]
Is this the correct way of unfolding questions?

1. [CIGLIFEA_UPTP17] On days that you smoked when you were age [X] [to age Y], about how many cigarettes did you smoke per day? 
Age [X] to age [Y / 17] |__|__| #CIGARETTES PER DAY 

[CIGLIFEA_18TO24] On days that you smoked when you were age [X] [to age Y], about how many cigarettes did you smoke per day? 
Age [X/18] to age [Y / 24] |__|__| #CIGARETTES PER DAY

[CIGLIFEA_25TO29] On days that you smoked when you were age [X] [to age Y], about how many cigarettes did you smoke per day? 
Age [X/25] to age [Y / 29] |__|__| #CIGARETTES PER DAY

[CIGLIFEA_30TO39] On days that you smoked when you were age [X] [to age Y], about how many cigarettes did you smoke per day? 
Age [X/30] to age [Y / 39] |__|__| #CIGARETTES PER DAY

[CIGLIFEA_40TO49] On days that you smoked when you were age [X] [to age Y], about how many cigarettes did you smoke per day? 
Age [X/40] to age [Y / 49] |__|__| #CIGARETTES PER DAY

[CIGLIFEA_50TO59] On days that you smoked when you were age [X] [to age Y], about how many cigarettes did you smoke per day? 
Age [X/50] to age [Y / 59] |__|__| #CIGARETTES PER DAY

[CIGLIFEA_60TO69] On days that you smoked when you were age [X] [to age Y], about how many cigarettes did you smoke per day? 
Age [X/60] to age [Y / 69] |__|__| #CIGARETTES PER DAY

[CIGLIFEA_70ANDABOVE] On days that you smoked when you were age [X] [to age Y], about how many cigarettes did you smoke per day? 
Age [X/70] and older |__|__| #CIGARETTES PER DAY

[CIGLIFEB_UPTP17] On days that you smoked when you were age [X] [to age Y], about how many cigarettes did you smoke per day? 
Age [X] to age [Y / 17] |__|__| #CIGARETTES PER DAY 

[CIGLIFEB_18TO24] On days that you smoked when you were age [X] [to age Y], about how many cigarettes did you smoke per day? 
Age [X/18] to age [Y / 24] |__|__| #CIGARETTES PER DAY

[CIGLIFEB_25TO29] On days that you smoked when you were age [X] [to age Y], about how many cigarettes did you smoke per day? 
Age [X/25] to age [Y / 29] |__|__| #CIGARETTES PER DAY

[CIGLIFEB_30TO39] On days that you smoked when you were age [X] [to age Y], about how many cigarettes did you smoke per day? 
Age [X/30] to age [Y / 39] |__|__| #CIGARETTES PER DAY

[CIGLIFEB_40TO49] On days that you smoked when you were age [X] [to age Y], about how many cigarettes did you smoke per day? 
Age [X/40] to age [Y / 49] |__|__| #CIGARETTES PER DAY

[CIGLIFEB_50TO59] On days that you smoked when you were age [X] [to age Y], about how many cigarettes did you smoke per day? 
Age [X/50] to age [Y / 59] |__|__| #CIGARETTES PER DAY

[CIGLIFEB_60TO69] On days that you smoked when you were age [X] [to age Y], about how many cigarettes did you smoke per day? 
Age [X/60] to age [Y / 69] |__|__| #CIGARETTES PER DAY

[CIGLIFEB_70ANDABOVE] On days that you smoked when you were age [X] [to age Y], about how many cigarettes did you smoke per day? 
Age [X/70] and older |__|__| #CIGARETTES PER DAY
 And so on.....

2. [ECIGLIFEA_UPTO17?] On days that you used e-cigarettes or other vaping devices for nicotine or tobacco when you were age X to age Y, what is the total amount of time you used them per day? 
(1) 15 minutes or less
(2) 15 minutes to 30 minutes
(3) 30 minutes to 1 hour
(4) 1 to 2 hours	
(5) More than 2 hours

[ECIGLIFEA_18TO24?] On days that you used e-cigarettes or other vaping devices for nicotine or tobacco when you were age X to age Y, what is the total amount of time you used them per day? 
(1) 15 minutes or less
(2) 15 minutes to 30 minutes
(3) 30 minutes to 1 hour
(4) 1 to 2 hours	
(5) More than 2 hours

[ECIGLIFEA_25TO29?] On days that you used e-cigarettes or other vaping devices for nicotine or tobacco when you were age X to age Y, what is the total amount of time you used them per day? 
(1) 15 minutes or less
(2) 15 minutes to 30 minutes
(3) 30 minutes to 1 hour
(4) 1 to 2 hours	
(5) More than 2 hours

[ECIGLIFEA_30TO39?] On days that you used e-cigarettes or other vaping devices for nicotine or tobacco when you were age X to age Y, what is the total amount of time you used them per day? 
(1) 15 minutes or less
(2) 15 minutes to 30 minutes
(3) 30 minutes to 1 hour
(4) 1 to 2 hours	
(5) More than 2 hours

[ECIGLIFEA_40TO49?] On days that you used e-cigarettes or other vaping devices for nicotine or tobacco when you were age X to age Y, what is the total amount of time you used them per day? 
(1) 15 minutes or less
(2) 15 minutes to 30 minutes
(3) 30 minutes to 1 hour
(4) 1 to 2 hours	
(5) More than 2 hours

[ECIGLIFEA_50TO59?] On days that you used e-cigarettes or other vaping devices for nicotine or tobacco when you were age X to age Y, what is the total amount of time you used them per day? 
(1) 15 minutes or less
(2) 15 minutes to 30 minutes
(3) 30 minutes to 1 hour
(4) 1 to 2 hours	
(5) More than 2 hours

[ECIGLIFEA_60TO69?] On days that you used e-cigarettes or other vaping devices for nicotine or tobacco when you were age X to age Y, what is the total amount of time you used them per day? 
(1) 15 minutes or less
(2) 15 minutes to 30 minutes
(3) 30 minutes to 1 hour
(4) 1 to 2 hours	
(5) More than 2 hours

[ECIGLIFEA_70ANDABOVE?] On days that you used e-cigarettes or other vaping devices for nicotine or tobacco when you were age X to age Y, what is the total amount of time you used them per day? 
(1) 15 minutes or less
(2) 15 minutes to 30 minutes
(3) 30 minutes to 1 hour
(4) 1 to 2 hours	
(5) More than 2 hours

[ECIGLIFEB_UPTO17?]On days that you used e-cigarettes or other vaping devices for nicotine or tobacco when you were age [X] [to age Y], what is the total amount of time you used them per day? 
(1) 15 minutes or less
(2) 15 minutes to 30 minutes
(3) 30 minutes to 1 hour
(4) 1 to 2 hours	
(5) More than 2 hours

[ECIGLIFEB_18TO24?] On days that you used e-cigarettes or other vaping devices for nicotine or tobacco when you were age X to age Y, what is the total amount of time you used them per day? 
(1) 15 minutes or less
(2) 15 minutes to 30 minutes
(3) 30 minutes to 1 hour
(4) 1 to 2 hours	
(5) More than 2 hours

And so on....

**Comment by ruggz13** [comment]
Looks good to me @joshid-ims . Just take out the original questions and keep the new ones you created

**Comment by joshid-ims** [comment]
What do you mean by 'original question'?

**Comment by ruggz13** [comment]
I meant just take out the numbers 1. and 2.

**Comment by hzhao392** [comment]
@joshid-ims @ruggz13 please discuss if this is still applicable
