### ISSUE TITLE
Grids need to handle skip patterns (#NR)

### ISSUE THREAD

**Issue by ruggz13** [episphere/quest#180]
See Module 2 WORKACT

**Comment by ruggz13** [comment]
One of the Modules has a skip logic if a certain answer is selected in the grid. I'm not sure which module it is, but the original issue was that the syntax of grids did not allow for the " -> QUESTIONID" syntax of skip to's. @hzhao392

**Comment by hzhao392** [comment]
i've added displayif conditions in the grid rendering, so instead of skipping, the grid will be displayed based on the displayif condition
