### ISSUE TITLE
Module 3 - Typo?

### ISSUE THREAD

**Issue by joshid-ims** [episphere/quest#181]
**[SECSMLF2 – SECSMLIF2H]** Thinking about your typical adult life, about how often were you around the tobacco smoke of others, for example in your home, work, or school when you were age [X] to age [Y]? 
□ Every day, at least 2 hours each day
□ Every day, less than 2 hours each day
□ Most days of the week
□ A few days per week
□ One day per week
□ A few days per month
□ One day per month
□ A few days per year	
□ Never

Should [SECSMLF2 – SECSMLIF2H] be [SECSMLF2A – SECSMLIF2H]  instead?

**Comment by ashreves** [comment]
@joshid-ims Yes, that is a typo. It should be [SECSMLF2A – SECSMLIF2H]

**Comment by miagaudet** [comment]
@joshid-ims, were you able to resolve the issue with Alaina's confirmation of the typo? Should I have @ruggz13 close this ticket?

**Comment by joshid-ims** [comment]
Yes, it can be closed. Thanks!
