### ISSUE TITLE
Module 4: Multiple Piped responses or Fill

### ISSUE THREAD

**Issue by meekk1** [episphere/quest#182]
There are a few examples of this in Module 4 where addresses from several questions need to be piped OR if there was no response "this address" should be displayed. How should this be done?

![image](https://user-images.githubusercontent.com/64271614/86408156-6b4af180-bc84-11ea-9792-9e1df76651f9.png)

**Comment by meekk1** [comment]
Gist snippet:
https://gist.github.com/meekk1/be4878eaae8a4163f8607bf8de2b5496

**Comment by danielruss** [comment]
stale closed
