### ISSUE TITLE
Module 3 - CIGLIFE questions

### ISSUE THREAD

**Issue by meekk1** [episphere/quest#184]
We've completed the age range for CIGLIFE as much as we could but came across an issue.

The age of CIGLIFEA shows as 0 to17. I think it’s supposed to show as the age the user started to 17 such as “. . .when you were age 13 to 17”. How can we change this?

https://gist.github.com/meekk1/f33afe05cb5d44ab3cab9e4c8cd2976b

**Comment by ruggz13** [comment]
X should be the value of 13 in your example. I believe the value X should come from the value of CIG3

**Comment by meekk1** [comment]
> X should be the value of 13 in your example. I believe the value X should come from the value of CIG3

Yes, I think so. But how should that be shown in the displayif statement?

**Comment by ruggz13** [comment]
We're having an internal discussion on it right now. If X is a year it must be calculated into an age to be used in the age range. Hold on for a bit on this one while we try and come up with a fix for this

**Comment by ashreves** [comment]
I'm working with Neal Freedman to address this issue.

**Comment by ashreves** [comment]
@ruggz13 I talked with Neal and we have a new plan for how to proceed. For module 3 questions that ask about age/year, we'd like to eliminate the year option and only ask about age. That should fix the problem with the logic in the grids.

We'd like to make the same changes to other age/year questions in module 3 (e.g. marijuana, alcohol). 

Please let me know if you have any questions.

**Comment by hzhao392** [comment]
@ruggz13 please take a look and close if this is done

**Comment by hzhao392** [comment]
Organize age or similar questions into one screen instead of multiple screens, the goal is to make the input easier for the user. Perhaps use grid.

**Comment by meekk1** [comment]
> Organize age or similar questions into one screen instead of multiple screens, the goal is to make the input easier for the user. Perhaps use grid.

Which questions should be within the grid?

**Comment by hzhao392** [comment]
I spoke with @ashreves  this morning. The goal for these kind of questions is to have them on one page display. We can use it either as multiple questions on one page or have them in a grid. I will look into if grids are possible
