### ISSUE TITLE
Module 3 - After CIGLIFE can't continue

### ISSUE THREAD

**Issue by meekk1** [episphere/quest#185]
After the age range questions the NEXT button doesn't work.

**Comment by hzhao392** [comment]
@ruggz13 please take a look

**Comment by meekk1** [comment]
I checked again to see if this renders properly. CIGLIFE questions used to work but the NEXT button to go to the following section did not. Now CIGLIFE questions don't render at all. It just goes to the next section. Any reason why it would stop working?

https://gist.github.com/meekk1/541c00785e78afadbeb954eb130a573c

**Comment by hzhao392** [comment]
@meekk1 I'm able to get to CIGLIFEA with the following answers. Let me know if your having problems understanding the JSON.

{"AGE":"55","TOBACCO":["1"],"CIG1":"4","CIG2":"21","CIG3":{"CIG3_AGE":"21"},"CIG4":"1","CIG9A":"50","CIG9B":"2","CIG9D":"55","CIG9C":"50","CIG10":"1","CIG11":"1"}

**Comment by meekk1** [comment]
It was a spacing issue. Closing.
