### ISSUE TITLE
Number inputs must have MIN and MAX attributes

### ISSUE THREAD

**Issue by ruggz13** [episphere/quest#186]
Number inputs must have appropriate mins and max in the markdown

**Comment by meekk1** [comment]
Word docs don't have min or max for number inputs so I'm unsure how to define these attributes.

**Comment by ruggz13** [comment]
Min and Max is in the Wiki under Numeric Responses. Word docs do not have any specifications, but the Excel Sheet does. 

Module 2 Excel: [https://nih.app.box.com/file/646505731736](url)
Module 3 Excel: [https://nih.app.box.com/file/646477714462](url)
Module 4 Excel: [https://nih.app.box.com/file/646497936415](url)

Let me know if you don't have access to these @meekk1
