### ISSUE TITLE
Module 3 - Need to be able to calculate age from a year

### ISSUE THREAD

**Issue by stealthv** [episphere/quest#187]
In module 3 there are questions where the user can enter a specific age  - or the year - they began or ended smoking. The problem is that we then need to use this information later when determining which age ranges to show. If they enter a year there needs to be someway to convert that to an age using the user's current age.

Any thoughts on how to best handle this? Optimally this gets stored into a variable that we can then use multiple times without having to recalculate it each time.

If we could specify arbitrary javascript to run we could do it but that probably opens the door to other problems.

**Comment by stealthv** [comment]
seems like you may already be working on this https://github.com/episphere/quest/issues/184#issuecomment-658890035

**Comment by ruggz13** [comment]
> seems like you may already be working on this [#184 (comment)](https://github.com/episphere/quest/issues/184#issuecomment-658890035)

Yup, already started a convo about this!

**Comment by ruggz13** [comment]
In Module 3, all age/year questions will now only ask for age, so there is no need to calculate the age. Just use the answer given

**Comment by ashreves** [comment]
@ruggz13 Can you please edit the instructions before each section (tobacco, marijuana, and alcohol).

Please delete the phrase "or the year"
