### ISSUE TITLE
Module 4 - Piped response from multiple choice question

### ISSUE THREAD

**Issue by meekk1** [episphere/quest#190]
How should answers from multiple choice questions be piped into a following question such as:

[DRINKSWTR1] In a typical week, which of these beverages do you make with tap water from your home? Select all that apply.
	A cup of coffee
	A cup of hot tea
	A glass of iced tea
	Any other beverage or soup made with your tap water (such as fruit juice made from concentrate and beverages made from powder)
	Other: Please describe [text box]
	NO RESPONSE  GO TO NUMBATHS

[DRINKSWTR2F] In a typical week, about how often do you use tap water from your home to make [insert response from DRINKSWTR1/other beverages]?

**Comment by ruggz13** [comment]
It should be {$VARNAME} but I see that it is not working properly. Looking into it now

**Comment by ruggz13** [comment]
Actually, I miss-understood the issue. All you have to do for [DRINKSWTR1] is add an ID to the text box. Simply,  [text box: ID]. Then in the [DRINKSWTR2F], it should be In a typical week, about how often do you use tap water from your home to make {$ID}. (whichever ID you called it). @meekk1
