### ISSUE TITLE
Module 3 - Display If according to 2 year span from specified age range

### ISSUE THREAD

**Issue by meekk1** [episphere/quest#191]
These age range questions are formatted differently than the others:

[SECSMLF2 AGE RANGE: IF RESPONDENT'S CURRENT AGE IS 2 YEARS OR LESS FROM THE BOTTOM OF THE SPECIFIED AGE RANGE, THEY SHOULD NOT BE GIVEN THE QUESTION AND INSTEAD ROUTED TO SECSM.]
□ NON-RESPONSE TO ANY AGE GROUP THAT ISN’T THE LAST  GO TO NEXT ITEM IN SECSMLF2 SERIES
□ NON-RESPONSE TO THE LAST RELEVANT AGE GROUP  GO TO SECSM
[SECSMLF2 – SECSMLIF2H] Thinking about your typical adult life, about how often were you around the tobacco smoke of others, for example in your home, work, or school when you were age [X] to age [Y]? 
□ Every day, at least 2 hours each day
□ Every day, less than 2 hours each day
□ Most days of the week
□ A few days per week
□ One day per week
□ A few days per month
□ One day per month
□ A few days per year	
□ Never

□ Age [X] to age [Y / 17]
□ Age [X / 18] to age [Y / 24]
□ Age [X / 25] to age [Y / 29]
□ Age [X / 30] to age [Y / 39 / current age]
□ Age [X / 40] to age [Y / 49 / current age]
□ Age [X / 50] to age [Y / 59 / current age]
□ Age [X / 60] to age [Y / 69 / current age]
□ Age [X / 70] and older

**Comment by ashreves** [comment]
@ruggz13 @meekk1 

This is a grid question with ages as the rows and frequency on the columns. Similar to the other smoking grid, the participants should check one response on each row. 

For the age categories, participants should only see rows that are relevant to their current age. If a participants current age is two years or less from the bottom of the range, they should not be asked about that age range. 

For example, if a participant is age 51, they just entered the age range for 50-59. It would not make sense to ask them about smoking exposure over the range of years since they only just entered their 50's. Similarly, if a participant is 52, we will not ask them about the 50-59 age category. However, if a participant is 56, they qualify to be asked about their in their 50's, but the category should adjust accordingly and become 50-56 instead of 50-59.

**Comment by freedmanne** [comment]
Thanks!

**Comment by meekk1** [comment]
> @ruggz13 @meekk1
> 
> This is a grid question with ages as the rows and frequency on the columns. Similar to the other smoking grid, the participants should check one response on each row.
> 
> For the age categories, participants should only see rows that are relevant to their current age. If a participants current age is two years or less from the bottom of the range, they should not be asked about that age range.
> 
> For example, if a participant is age 51, they just entered the age range for 50-59. It would not make sense to ask them about smoking exposure over the range of years since they only just entered their 50's. Similarly, if a participant is 52, we will not ask them about the 50-59 age category. However, if a participant is 56, they qualify to be asked about their in their 50's, but the category should adjust accordingly and become 50-56 instead of 50-59.

Thanks Alaina! You mentioned the other smoking grid. Can you tell me what you're referring to? For other age range questions in Module 3, we didn't "code it like grids. The way we currently have it, users will only view the age range question that is relevant to them. I think Module 3 only specifies grids once and that's for ALCLIFE.

**Comment by ashreves** [comment]
@ruggz13 @meekk1 

Sorry, I'm referring to the second hand smoking grid. It's mentioned in issue #192

**Comment by hzhao392** [comment]
@meekk1 Krystal, I've added the displayif logic for child rows in the grid. You can use the following input as a sample. Question 2 and 3 will have dependencies for displayif if the first answer is set to 1

[SEX] Later questions in this survey will ask about surgeries and medical procedures. We want to make sure that you are asked the right questions. 
Please select the body parts that you were born with.
[1] Penis
[2] Testes
[3] Prostate
[4] Vagina
[5] Cervix
[6] Uterus
[7] Ovaries
[8] Fallopian Tubes

|grid|id="grid_SECSM"|People in Household|[ [SECSMA,displayif=equals(SEX,1)] Birth to 5 years of age; [SECSMB] Ages 6 to 10; [SECSMC] Ages 11 to 14; [SECSMD] Ages 15 to 17;]|(1:Every day, at least 2 hours each day
) (2:Every day, less than 2 hours each day
) (3:Most days of the week) (4:A few days per week) (5:One day per week) (6: A few days per month) (7: One day per month) (8:  few days per year) (9: Never)|

[HRMED2?] What medication did you use to treat thinning hair or hair loss? Select all that apply.
[1] Rogaine, Minoxidil, or Ioniten
[2,displayif=equals(SEX,1)]Finasteride
[3] Other: Please describe [text box]

**Comment by meekk1** [comment]
> @meekk1 Krystal, I've added the displayif logic for child rows in the grid. You can use the following input as a sample. Question 2 and 3 will have dependencies for displayif if the first answer is set to 1
> 
> [SEX] Later questions in this survey will ask about surgeries and medical procedures. We want to make sure that you are asked the right questions.
> Please select the body parts that you were born with.
> [1] Penis
> [2] Testes
> [3] Prostate
> [4] Vagina
> [5] Cervix
> [6] Uterus
> [7] Ovaries
> [8] Fallopian Tubes
> 
> |grid|id="grid_SECSM"|People in Household|[ [SECSMA,displayif=equals(SEX,1)] Birth to 5 years of age; [SECSMB] Ages 6 to 10; [SECSMC] Ages 11 to 14; [SECSMD] Ages 15 to 17;]|(1:Every day, at least 2 hours each day
> ) (2:Every day, less than 2 hours each day
> ) (3:Most days of the week) (4:A few days per week) (5:One day per week) (6: A few days per month) (7: One day per month) (8: few days per year) (9: Never)|
> 
> [HRMED2?] What medication did you use to treat thinning hair or hair loss? Select all that apply.
> [1] Rogaine, Minoxidil, or Ioniten
> [2,displayif=equals(SEX,1)]Finasteride
> [3] Other: Please describe [text box]

I tried to render this and for the first question, whether I select body parts or don't select any, the first option "SECSMA" which shows the display if statement doesn't show either way.
![image](https://user-images.githubusercontent.com/64271614/95602663-3983bc80-0a23-11eb-930d-49cdc2cee49f.png)

Also, still working on the SECSMLF2 AGE RANGES. I just want to confirm whether display if in grids works or not.

**Comment by hzhao392** [comment]
The display if for the first row of SECSMA will only show if you select [1] Penis in the SEX question. If you do not select [1] Penis then it will not show.

**Comment by meekk1** [comment]
Right, it doesn't display [Penis] even when it's selected.

**Comment by hzhao392** [comment]
Will ping you on gitter for a call later today

**Comment by meekk1** [comment]
https://gist.github.com/meekk1/9621f40d6278f70aee375539d2a1eead

**Comment by meekk1** [comment]
I've updated my gist: https://gist.github.com/meekk1/9621f40d6278f70aee375539d2a1eead

And I think I have it working except for adjusting the child row according to the age the user entered. For instance, if the user is 56, the row should become 50-56 instead of 50-59. Not sure how to do that.

**Comment by hzhao392** [comment]
@meekk1 I dont think we have the ability to place variable or fucntions in a question yet. This is a limitation that applies to all questions and not just grids. If the grid issue is resolved can you close the tickets related to them? I can create a new ticket as a enhancement item for variable and function rendering as a part of the question

**Comment by meekk1** [comment]
Closing, since grids are functional
