### ISSUE TITLE
Module 3 - Format of SECSM

### ISSUE THREAD

**Issue by meekk1** [episphere/quest#192]
[SECSM – SECSMD] During each of these age ranges, how many people in your household smoked tobacco (such as cigarettes, cigars, or pipes) in your presence? Please do not include yourself.
□ None
□ One
□ Two
□ Three
□ Four
□ Five or more

□ Birth to 5 years of age
□ Ages 6 to 10
□ Ages 11 to 14
□ Ages 15 to 17

□ NON-RESPONSE TO ANY AGE GROUP THAT ISN’T THE LAST  GO TO NEXT ITEM IN SECSM SERIES
NON-RESPONSE TO THE LAST RELEVANT AGE GROUP  GO TO MARIJUANA SECTION

**Comment by ashreves** [comment]
@ruggz13 @meekk1 

This is a grid question. I've included a screen shot of NORC's Qualtrics model where they did a mockup. 

![image](https://user-images.githubusercontent.com/54043164/94476060-f6615800-019d-11eb-8e8f-1aea33ccceca.png)


Let me know if you have any other questions, but I think this should clarify the format.
