### ISSUE TITLE
Module 3 - Age range displayif with grid

### ISSUE THREAD

**Issue by meekk1** [episphere/quest#193]
ALCLIFE1 questions include displayif grid with age ranges:

<ALCLIFE2 - ALCLIFE4: DISPLAY ONLY ROWS THAT INCLUDE AT LEAST 1 AGE THAT FALLS BETWEEN START AGE (ALCOHOL4) AND [STOP AGE (ALCOHOL6) OR CURRENT AGE (if current drinker)]>
<FILL FOR X: IF ROW CONTAINS START AGE (ALCOHOL4), USE AGE FROM (ALCOHOL4); ELSE USE LOWER BOUND OF ROW>
<FILL FOR Y: IF ROW CONTAINS STOP AGE (ALCOHOL6)/CURRENT AGE, USE AGE FROM (ALCOHOL6)/CURRENT AGE; ELSE USE UPPER BOUND OF ROW>
<IF ROW HAS ONLY 1 AGE THAT FALLS BETWEEN START AGE (ALCOHOL4) AND STOP AGE (ALCOHOL6)/CURRENT AGE, DO NOT DISPLAY “to age Y”>
<IF ALCLIFE2 = 07, SKIP ALCLIFE3 AND ALCLIFE4 FOR AGE GROUP AND GO TO ALCLIFE2 FOR NEXT AGE GROUP. IF LAST RELEVANT AGE GROUP, GO TO SUN EXPOSURE SECTION.>

	NO RESPONSE (ANY)  GO TO NEXT APPLICABLE ITEM IN SERIES. IF LAST APPLICABLE ITEM IN SERIES, GO TO SUN EXPOSURE SECTION.

[ALCLIFE1] The next questions ask about how much you drank alcohol at different times in your life.

**Comment by hzhao392** [comment]
@meekk1 should be resolved with https://github.com/episphere/quest/issues/191

**Comment by meekk1** [comment]
@hzhao392 For this one, variables are an issue here but also on the word doc it seems like each age range has grid type questions within a main grid. Not sure if this is possible or how to get started with it.

This is how the word doc looks:
![image](https://user-images.githubusercontent.com/64271614/96289797-a3680d00-0fb3-11eb-8cc8-f9c2b430f8a0.png)

**Comment by hzhao392** [comment]
@ashreves this is a big concern. The requirement is asking us to place questions with in grids. There is no way of doing that right now and would be a major undertaking.  Also this will have very bad UI if we render all of that information within a grid. We need to discuss of an alternative to doing this.

**Comment by ashreves** [comment]
@hzhao392 @meekk1 

Per our discussion today, please delete question ALCLIFE3. We will divide this single grid into two grids, one for ALCLIFE2 and one for ALCLIFE4.

Please add response options to ALFLIFE2. The full list should read:
Didn't drink
A few times per year
A few times per month
Once per week
A few times per week
Once per day
2-3 times per day
4-5 timer per day
6 or more times per day

**Comment by danielruss** [comment]
stale ... closed
