### ISSUE TITLE
Module 1 - Blank Page on Microsoft Edge

### ISSUE THREAD

**Issue by robertsamm** [episphere/quest#195]
Module 1 is not working on Microsoft Edge web browser. I am able to see the first screen and input name, age, and sex but when I hit submit all I get is a blank page instead of entering in to the questionnaire. Tested on 3 PCs.

**Comment by ruggz13** [comment]
Can you try updating your Edge? @robertsamm

**Comment by robertsamm** [comment]
@ruggz13 It looks like I have the latest version of Edge.

**Comment by ruggz13** [comment]
@bhaumik55231 Tested it on Edge as well and he has a PC, but no issues @robertsamm

**Comment by robertsamm** [comment]
@ruggz13 I'm still getting a blank screen after hitting submit. I've tried it on both my work and personal PC. and @ashreves said she tried it on her PC and is also getting the blank screen. I've tried clearing past results and disconnecting from the VPN as well.

**Comment by ruggz13** [comment]
@robertsamm the most updated version of Edge is 84.0.522.52

**Comment by ruggz13** [comment]
If you're using the most updated version it works...Closing
