### ISSUE TITLE
Decisions for Age/Year questions 

### ISSUE THREAD

**Issue by ashreves** [episphere/quest#197]
There are two separate age/year issues: in-questionnaire calculations and inconsistent data output. 

To streamline calculations, we will simplify age/year questions in module 3 to only ask about age. @ashreves will update the questionnaire word document (for submission to the IRB) and @ruggz13 will update the markdown. 

We will leave age/year questions as is for modules 1, 2, and 4, with plans to evaluate after the initial study period. There are no action items for these questions right now.

**Comment by ruggz13** [comment]
These changes were already made correct?

**Comment by ashreves** [comment]
@ruggz13 Yes, I think you have already made the changes. As discussed at the last prep meeting, we wanted to document decisions on GitHub.

**Comment by hzhao392** [comment]
@ashreves closing this for now as it can still be documented as a closed issue
