### ISSUE TITLE
iPhone/Firefox- display of warning messages

### ISSUE THREAD

**Issue by ashreves** [episphere/quest#198]

**Comment by ashreves** [comment]
The range checks seem too tight on the iPhone's firefox browser. It looks like the font is too close to the top  of the pop up window. 
![IMG_3146 (1)](https://user-images.githubusercontent.com/54043164/89535815-f0b24c00-d7c4-11ea-80f6-0cdf0aac1cba.PNG)

**Comment by ashreves** [comment]
@ruggz13 After further testing, I've found the same warning message issue on other browsers (safari, chrome) on the iPad.

Since most of our participants will likely be using tablets to complete the questionnaire, it is important to fix this.

**Comment by ruggz13** [comment]
This is an iPad issue, not a FireFox issue @ashreves

**Comment by ruggz13** [comment]
Custom validations are now complete. I have been doing a rough testing of it throughout Module 1. If @ashreves or @robertsamm could do another test run of Module 1 that would be great. Not going to close this yet just in case more bugs come up

**Comment by ashreves** [comment]
I just tested on iPad with Firefox. These error messages work better.

**Comment by ashreves** [comment]
The error messages look better. I will reopen this issue if we find any other errors.
