### ISSUE TITLE
iPad/Safari- Issues typing SSN

### ISSUE THREAD

**Issue by ashreves** [episphere/quest#199]
The SSN is not easy to type on iPad. When the warning message pops up to indicate incorrect format, you can not simply type and enter more numbers. To move forward, I had to delete the whole text box and start typing again.

Screen recording: https://drive.google.com/file/d/1UFwP1oPeekM7c1yQDLdTHVUcvAaKq5bT/view

**Comment by ruggz13** [comment]
Try it now @ashreves

**Comment by ruggz13** [comment]
Fixed SSN...closing
