### ISSUE TITLE
parse numeric template

### ISSUE THREAD

**Issue by jonasalmeida** [episphere/quest#2]
Just an excuse to start the project tracking of issues ...
[![Screen Shot 2019-12-02 at 4 03 24 PM](https://user-images.githubusercontent.com/204769/69995914-f7464080-151e-11ea-985c-f6f95a94bce7.png)](https://episphere.github.io/quest/?questionnaries/demo.txt)

**Comment by ruggz13** [comment]
Would it be better to have an input box with a tick mark to add value of age (i.e. |__#| as an input field) or give two fields to add a digit to, to give value of age (i.e [2][4], [5][2]...and so on)

**Comment by jonasalmeida** [comment]
what about a generic pattern between ||, like |###-##-####| for SSN, which would also allow |(###)-###-####| and |##/##/####| etc? Just a thought. I tend to look for solutions that require the minimum possible number of neurons on the part of the domain users, i.e. the minimum number of generic paterns

**Comment by FrogGirl1123** [comment]
I kind of like the flexibility of  # option for indicating different formats of numeric entry, but I don't know  if there are any obstacles in getting the markup to render using that method.
