### ISSUE TITLE
iPad/safari- font size

### ISSUE THREAD

**Issue by ashreves** [episphere/quest#200]
![textsizeipad](https://user-images.githubusercontent.com/54043164/89538372-771c5d00-d7c8-11ea-9e00-679be0d2b5b3.PNG)

**Comment by ashreves** [comment]
The text for questions are small on the iPad. The answer options seem sufficient, but I had to bring the device close to my face to read some question test because it was too small. Since our study population is older, we want to make sure they can see question text easily.

**Comment by ruggz13** [comment]
This will be a job for the Questionnaire User on how it is rendered into the PWA.
