### ISSUE TITLE
iPad/safari- back/next button

### ISSUE THREAD

**Issue by ashreves** [episphere/quest#201]
When iPad is flipped in horizontal position, the back and next buttons are too close to the bottom of the screen. It is difficult to click on them. Please add more space after the buttons so they are not flush with the bottom. 
![buttontooclose](https://user-images.githubusercontent.com/54043164/89538730-ed20c400-d7c8-11ea-9d6f-1d41fce512c5.PNG)

**Comment by ruggz13** [comment]
This was similar to #171  @ashreves

**Comment by ruggz13** [comment]
Fixed...closing
