### ISSUE TITLE
iPad/Safari- age entry field too small

### ISSUE THREAD

**Issue by ashreves** [episphere/quest#202]
The age entry fields are very small on the iPad. It was difficult to click the exact middle of the field to be able to start typing. If you have bigger fingers, you would likely find this very frustrating. Please make the entry box for ages larger. 
![agefields](https://user-images.githubusercontent.com/54043164/89539021-4557c600-d7c9-11ea-96a7-83d08c93ba0a.PNG)

**Comment by ruggz13** [comment]
The size of the entry is based off of the min/max attributes. If the min/max is a two digit number, it will only allow for two digits, thus being a smaller box @ashreves

**Comment by ruggz13** [comment]
Try it now

**Comment by ruggz13** [comment]
...closing
