### ISSUE TITLE
Module 1- Range checks not working for some questions

### ISSUE THREAD

**Issue by ashreves** [episphere/quest#203]
For some questions, I got error messages but was still able to proceed although my answer did not meet the requirements. I found this issue testing on the iPad with Chrome.

I found this issue on these questions:
SKINCANC3, TRICH, SIBCANC3I, CHILDCANC3D

@ruggz13 I did not do a systematic review of all questions as I was only conducting high level testing. This error could be an issue for other parts of the questionnaire. 

![image](https://user-images.githubusercontent.com/54043164/93811789-ad018d80-fc1e-11ea-99a4-540c7f32ef9a.png)

**Comment by ruggz13** [comment]
I can't seem to replicate it either in Quest nor in Simple Test @ashreves

**Comment by ashreves** [comment]
@ruggz13 
I retested and found that the issue does not occurSKINCANC3, TRICH. I must have coped it wrong from my notes. My apologies. 

However, the issue still occurs for SIBCANC3I, CHILDCANC3D. It looks like it is an issue with the looping in family history.

**Comment by hzhao392** [comment]
@ruggz13 Can you test SIBCANC3I, CHILDCANC3D I just tested the two and they seem ok to me. If they are ok with you then lets have a call with @ashreves and see how this renders for her

**Comment by robertsamm** [comment]
@ruggz13 @hzhao392 I am also reproducing the same error as @ashreves on the MOMCANC3, DADCANC3, SIBCANC3, and CHILDCANC3 questions. 

However, I noticed it only occurs if you were able to enter an age for the previous MOMAGE/DADAGE/SIBAGE/CHILDAGE question and are then offered both year and age in the CANC3 questions. If you were not able to put an age for the person in the previous question then you are only offered to input age in the CANC3 questions and the error does not occur.

**Comment by ruggz13** [comment]
@ashreves @robertsamm @hzhao392 Was just able to replicate it. Looking into it right now

**Comment by ruggz13** [comment]
> @ashreves @robertsamm @hzhao392 Was just able to replicate it. Looking into it right now

Just pushed a fix. Should be working now

**Comment by ashreves** [comment]
@ruggz13 Looks like it is working now. closing the issue.
