### ISSUE TITLE
Module 1- Range on SHORTER2

### ISSUE THREAD

**Issue by ashreves** [episphere/quest#204]
The upper range for SHORTER2, "How much shorter are you now than when you were in your 20s and 30s? If you are not sure, please make your best guess.  |__|__| Inches" is 99 inches. This seems like a high value.

I suggest we change this to a lower number that is more probable because it was easy to tap 55 instead of 5 on the iPad.

Or, we could add "are you sure" for any value with double digits. 

![image](https://user-images.githubusercontent.com/54043164/93812063-1c777d00-fc1f-11ea-8b01-5c3a35eed3bb.png)

**Comment by ruggz13** [comment]
<img width="1223" alt="Screen Shot 2020-09-21 at 3 53 13 PM" src="https://user-images.githubusercontent.com/16128549/93814548-a9700580-fc22-11ea-9698-23f652fbaad5.png">

**Comment by hzhao392** [comment]
@ashreves we need to decide the upper range for this

**Comment by ashreves** [comment]
@ruggz13 Please change the range to 10 or less, allow for decimals.

**Comment by hzhao392** [comment]
@ashreves Please take another look. I've updated the code so the arrows will not go past the maximum and minimum values so you will not see negatives. The input box does allow decimals but you will have to manually input them from the keyboard. The up and down arrows are for integers only and its the behavior of html5.

**Comment by hzhao392** [comment]
@ashreves We should revisit allowing decimals in these fields. The problem is if we allow decimal here we allow for it in other places since they share the same input type. For example, now the Age field will allow decimals as well. I think if there is no pressing reason we should leave it as whole numbers.

**Comment by ruggz13** [comment]
@hzhao392 you can add html directly to the markdown. In case you don't want to add step to all input types, you can add it directly to the plain text.

**Comment by danielruss** [comment]
stale ... closed
