### ISSUE TITLE
Module 1- error messages are unfriendly

### ISSUE THREAD

**Issue by ashreves** [episphere/quest#205]
I think we might want to adjust the wording on these error message. I don't find the messaging to be very user friendly.

![image](https://user-images.githubusercontent.com/54043164/93812867-306fae80-fc20-11ea-9105-0ffc215dcb6b.png)

![image](https://user-images.githubusercontent.com/54043164/93812814-23eb5600-fc20-11ea-833b-197fec486fcf.png)

**Comment by ruggz13** [comment]
The first message of the range and all messages with the red lettering are the default messages that are used in HTML. I can change them if needed. The second popup window message can also be changed but that is up to the user of the questionnaire.

**Comment by ashreves** [comment]
I wasn't saying how they appear was unfriendly, but that the text itself is not user friendly. 

For example, I didn't like seeing "value must be..." showing up when I was typing my answer. It felt too much like programming jargon than a questionnaire error message.

From some side conversations, I think we will deal with this later when we make final content edits and have more UI/UX guidance.

I will close this issue for now, but I think we should keep it on our radar for the future.

**Comment by ashreves** [comment]
@hzhao392 error message for SOCIALSECU2 is not showing up correctly on iPad.

**Comment by ruggz13** [comment]
@ashreves fixed error message.

**Comment by ashreves** [comment]
This looks fixed.
