### ISSUE TITLE
Module 1- Daddeath can enter value and don't know

### ISSUE THREAD

**Issue by ashreves** [episphere/quest#206]
For DADDEATH I was able to enter an age of death and select DON'T KNOW.

I was not able to unselect DON'T KNOW option.

Participants should only be able to provide one answer and should be able to deselect DON'T KNOW.

**Comment by ruggz13** [comment]
In the Word Doc, it was a radio button. I can change it to a check box that can be selected/deselected if needed @ashreves

**Comment by ashreves** [comment]
@ruggz13 Similar to other questions asking about age/year, you should only be able to select one or the other. Participants can either enter an age of death or they can select do not know.

**Comment by ruggz13** [comment]
@ashreves check now if this is the right functionality

**Comment by danielruss** [comment]
stale ... closed
