### ISSUE TITLE
Module 1- Typo CHILDAGE

### ISSUE THREAD

**Issue by ashreves** [episphere/quest#207]
Question reads "How old is your [he/she/your child] today?"

Question should read "How old is [he/she/your child] today?"

**Comment by hzhao392** [comment]
@ruggz13 this is coming directly from Jonas's repository right? so we just need to update it there

**Comment by ruggz13** [comment]
Yup, two second fix @hzhao392

**Comment by ruggz13** [comment]
Fixed
