### ISSUE TITLE
SSN brings up qwerty keyboard instead of numeric - Module 1

### ISSUE THREAD

**Issue by robertsamm** [episphere/quest#208]
I noticed on the ipad that SOCIALSECUR1 brings up a qwerty/alphabet keyboard instead of numeric while the ALTCONTACT2 phone number questions automatically bring up a numeric keyboard. Could we have the SOCIALSECUR1 do the same so it's easier for participants to type in their SSN?

**Comment by ruggz13** [comment]
@robertsamm The telephone input actually brings up a numeric telephone keyboard such as you are typing in a phone number. I can make it so it automatically switches to the number section of a qwerty keyboard, but not a 10 key keyboard like the telephone input

**Comment by ashreves** [comment]
@ruggz13 if you can't do a number keyboard like the phone, I suppose bringing up the number section of qwerty is better than nothing. 

However, it would be much easier on participants if numeric keyboard was possible.

**Comment by hzhao392** [comment]
@ashreves @robertsamm SSN will take number pad on mobile now, please test. PR https://github.com/episphere/quest/pull/214

**Comment by ashreves** [comment]
@hzhao392 This works.
