### ISSUE TITLE
Active Recruitment Token Issue

### ISSUE THREAD

**Issue by ggulotta** [episphere/quest#213]
I can successfully create a token through the getParticipantToken API endpoint. However, when I attempt to log in for the first time using that token with the URL https://episphere.github.io/connectApp/?token=<token\>, a new participant is generated. However, that participant now has a completely new token--not the one created through the API. 

I'm currently attempting to test our active recruitment workflow.

**Comment by hzhao392** [comment]
@ggulotta hi, George, did you mean to put this in https://github.com/episphere/connect ? this project is for the questionnaire and not recruitment
