### ISSUE TITLE
SSN not hiding numbers

### ISSUE THREAD

**Issue by naiyume** [episphere/quest#223]
tried 
|SSN|
|SSN|pattern=#|
|SSN|pattern=|

None of the above seem to be masking the numbers at the moment

**Comment by hzhao392** [comment]
Brian, the SSN numbers are not being hidden right now because there is only one question and it is difficult for the users to make sure the number they put in is correct if it is hidden. I am going to leave this as is right now unless we get more people to request the SSN be hidden.

**Comment by danielruss** [comment]
stale issue ... closing
