### ISSUE TITLE
Module 1- Add question SEX

### ISSUE THREAD

**Issue by ashreves** [episphere/quest#226]
Please add question [SEX] after LANG and before GEN. Questions that previously routed to GEN should not route to SEX as it is the beginning of the sex and gender section. 

Question should appear as follows:
[SEX] Later questions in this survey will ask about surgeries and medical procedures, including to the sex organs you were born with. We want to ask questions that will make sense for you. 

What was your biological sex assigned at birth? 

Female -> GO TO GEN 
Male -> GO TO GEN 
Intersex or other -> GO TO SEX2 

NO RESPONSE -> GO TO GEN

**Comment by ashreves** [comment]
Likewise, please remove the intro text from SEX2.

SEX2 should now read:

SEX2] Please select the body parts that you were born with.

**Comment by hzhao392** [comment]
Swapping MALE and FEMALE so MALE=1 and FEMALE=2

**Comment by danielruss** [comment]
stale ... closed
