### ISSUE TITLE
Module 4 - Skip logic after numeric text not working

### ISSUE THREAD

**Issue by joshid-ims** [episphere/quest#228]
For Tobacco section, for all #6 questions, for e.g. 

[ECIG6,displayif=equals(TOBACCO,2)?] How many of the <b>past 30 days</b> have you used e-cigarettes or other vaping devices for nicotine or tobacco?
#Days used e-cigarettes or other vaping devices in past 30 days |__|__|min=1 max=30| -> ECIG9A
<#NR ->ECIG9A>

Does not work. It displays " ->ECIG9A " after the numeric box and does not proceed to 9A. 

[ECIG6,displayif=equals(TOBACCO,2)?] How many of the <b>past 30 days</b> have you used e-cigarettes or other vaping devices for nicotine or tobacco?
#Days used e-cigarettes or other vaping devices in past 30 days |__|__|min=1 max=30| 
<-> ECIG9A

This works but then it does not ask users, if there is no response, that if they want to answer or continue without answering. So if users did not answer by mistake, they will not be able go back and answer (I guess). Is that ok or this will need a fix?

**Comment by hzhao392** [comment]
Hi Deepti:

Try to add code in gist links, github comments will remove some characters from codes

<-> ECIG9A>
is fine, since it goes to ECIG9A regardless of the answer. The back button should work also since each question is added on a stack and the back will just roll the question back. 

Example:
https://gist.github.com/hzhao392/d689220e499c243ccfbf37da624ef84f

**Comment by joshid-ims** [comment]
Thanks!

**Comment by hzhao392** [comment]
Also your "answer or continue without answering" trigger is misplaced 

This is your question [ECIG6,displayif=equals(TOBACCO,2)?]

The question mark or exclamation mark needs to be right next to the question ID like so  [ECIG6?,displayif=equals(TOBACCO,2)]

**Comment by joshid-ims** [comment]
Ok, I will change that. Thanks!

**Comment by hzhao392** [comment]
@joshid-ims Deepti can we close this?

**Comment by joshid-ims** [comment]
Yes. Thanks!
