### ISSUE TITLE
Module 4: CHILDADD

### ISSUE THREAD

**Issue by meekk1** [episphere/quest#229]
Quest doesn't have a way of knowing which address previously entered is the address the user wants to enter for their child address. Previous addresses are supposed to be shown here:
![image](https://user-images.githubusercontent.com/64271614/99689336-dbe88400-2a54-11eb-802f-c14d180b53f4.png)

But even if the user selects this option, Quest won't know which previous address the user would like to select.

I added another question that lists all previous addresses entered and allows the user to select which one is their child address.
![image](https://user-images.githubusercontent.com/64271614/99689690-4b5e7380-2a55-11eb-82f5-f28beb6c91bd.png)

https://gist.github.com/meekk1/091d8a9e13e2d0e6111ecd0f51dba7f3

Is this a valid fix for this? Or is there a better way?

**Comment by hzhao392** [comment]
Krystal, you can get CHILDTEST to render right? and you just need CHILDADD4 to render based on the selection of CHILDTEST?
If so the value of CHILDTEST is the same as the ADDRESS values that they picked. For example if CHILDTEST = 3 then you are displaying {$STNUM3} {$FULLST3} {$APT3} {$CITY3}, {$ST3} {$ZIP3} {$COUNTRY3}

**Comment by meekk1** [comment]
Yes, CHILDTEST renders. I'm having some trouble with CHILD4 though. 

I thought this should work but it doesn't:
![image](https://user-images.githubusercontent.com/64271614/99713488-5f649e00-2a72-11eb-8050-a5840aa0ea5e.png)

**Comment by hzhao392** [comment]
Great, can we close this?

**Comment by meekk1** [comment]
Sure, I'll keep CHILDTEST in there.
