### ISSUE TITLE
Validataion/ranges

### ISSUE THREAD

**Issue by FrogGirl1123** [episphere/quest#23]
Prevent submission of answers that are outside the specified range (see issue #18 for how range is specified) for integer responses.

**Comment by FrogGirl1123** [comment]
We also need a way to indicate types of validation besides straight forward numeric ones.
For example when a year or age is given for a diagnosis, the year or age must be within the DOB and current date.
Let me know if you think this should be a separate issue.

**Comment by danielruss** [comment]
Validation is a big topic.  Most of the validation is on the questionnaire user.  If year of birth is a requirement, it needs to be better fleshed out.  Otherwise it is too "connect"-specific.

**Comment by ruggz13** [comment]
All age verifications should be fixed now
