### ISSUE TITLE
Parsing error with optional text

### ISSUE THREAD

**Issue by stealthv** [episphere/quest#232]
I noticed what seems like a parsing error when using optional text for a piped result:

Example markup
```
[TEST]
Leave both fields blank
Field 1|__|__|id=FIELD1|
Field 2|__|__|id=FIELD2|

[RESULT]
{$FIELD1:optional text}
{$FIELD2:optional text}
```

Result:
<img width="392" alt="Screen Shot 2020-12-11 at 1 50 32 PM" src="https://user-images.githubusercontent.com/394603/101942639-d98ecb00-3bb7-11eb-9843-f42f7d4806fb.png">

**Comment by hzhao392** [comment]
Hi Bran, the for piping results look like this, 

`[TEST]
Leave both fields blank 
Field 1|__|__|id=FIELD1|
Field 2|__|__|id=FIELD2|

[RESULT]
{$FIELD1} optional text
{$FIELD2} optional text`

if you want the optional text to be driven by field1 and field2 you need to add a displayif condition

**Comment by stealthv** [comment]
@hzhao392 okay, is the wiki out of date?

> Piped response can take optional text. Just add a : after the ID (e.g. {$A1:this is optional text}. If there is no value given for the id, the optional text will appear instead.

from https://github.com/episphere/quest/wiki#piped-response

Note, the form I was using does work when it is only one field.

**Comment by hzhao392** [comment]
You're right, it is buggy right now. The regex is incorrectly picking up multiple fields instead of one by one. I'm going to label this as a bug.

**Comment by hzhao392** [comment]
@stealthv Fixed, let me know if you see anything wrong with it

**Comment by stealthv** [comment]
Seems to work correctly now. Thanks!
