### ISSUE TITLE
Module 2 - tag displaying when last option is a text box

### ISSUE THREAD

**Issue by cyrjeant** [episphere/quest#236]
We are unsure of how this is happening, but we notice that the tag for where the user would be directed to is being displayed and it should not be - note the "HORMED2_9" at the bottom of the image.  We note this for every question that has a text box as the last option, but don't know if the text box really has anything to do with it.

![image 3](https://user-images.githubusercontent.com/64271080/103226836-f981f680-48fa-11eb-9ef4-01d7d58c1c26.png)

**Comment by hzhao392** [comment]
Thanks @cyrjeant , this is in a loop right? I think it has something to do with the way question_id is being rendered in a loop

**Comment by stealthv** [comment]
@hzhao392, this is not in a loop. It seems to be caused by using a jump after a radio button with an attached field.
Here is a simple example:
```
[START]
All options should lead to the end but Option 3 doesn't
(1)Option 1 -> END
(2)Option 2 -> END
(3)Option 3 |__| -> END

[MIDDLE]
************************
You should not be here!
************************

[END]
This is the end
```

**Comment by hzhao392** [comment]
@stealthv Thanks Bran, this was just fixed, your sample is now working. The extra -> text has been removed as well.

**Comment by stealthv** [comment]
Thanks!
