### ISSUE TITLE
Piped text with methods

### ISSUE THREAD

**Issue by hzhao392** [episphere/quest#238]
Hi Alaina,

Quest currently does not support piping methods/functions/calculations as text. So in the following display, we cannot calculate CURRENT YEAR – 20. Can we remove that text from the section? We can put in a piped method feature once we get a developer from IDIQ.

```
[INTROSH] Now we are interested in time you have spent in seasonal or vacation homes. We want to know about any homes where you have spent a total of 24 months or more over the past 20 years (that is, since CURRENT YEAR – 20). Living somewhere for a few months each year counts if the total time adds up to 24 months or more.
```

**Comment by hzhao392** [comment]
We will not be doing the calculations in this iteration of quest. Perhaps done with IDIQ

**Comment by danielruss** [comment]
stale issue ... closing
