### ISSUE TITLE
Rendering issue with displayif in a textfield

### ISSUE THREAD

**Issue by stealthv** [episphere/quest#239]
The demo site: https://episphere.github.io/quest/ seems to ignore a 'displayif' used on textfield when it is on the page currently being rendered.

Not a huge deal but things like this do make it difficult to evaluate if markup is working like it is supposed to or if certain things are even possible. If I were to try to first example I would just assume displayif is not supported in a textfield.

------------

Example 1
```
[Q1]
You should not see a textfield on this page
|__|id=TEST displayif=equals(1,2)|
```
This will always show a textfield but it shouldn't

--------------

Example 2
```
[Q1]
Cick next

[Q2]
You should not see a textfield on this page
|__|id=TEST displayif=equals(1,2)|
```
This will seem to work correctly but if you are on the second page and cause it to re-render (by moving the cursor around in the markup section or altering the markup slightly) the textfield will appear.

---------------

**Comment by hzhao392** [comment]
Thanks @stealthv we are trying to bring on another team of developers for Quest, we will be looking to fix this once that team is on board

**Comment by danielruss** [comment]
stale ... closed
