### ISSUE TITLE
Module 2- MENSHIS missing intro text

### ISSUE THREAD

**Issue by ashreves** [episphere/quest#241]
Missing introduction language completely. Should have text that reads "[INTROWH] This section asks about your menstrual history, any pregnancies that you have had, and your use of hormone medications. When you are asked to give an exact date, age, or number, it is okay to make your best guess if you are not sure. Menstrual History[MENSHIS] First, we have some questions about your menstrual period." before question. 

Same for Sex=2. Missing INTROWH section before MENSHIS.

**Comment by stealthv** [comment]
The missing text should be back and shown separately from the first question.

**Comment by ashreves** [comment]
Fixed, closing issue.
