### ISSUE TITLE
Module 2 - Clock functionality

### ISSUE THREAD

**Issue by ashreves** [episphere/quest#244]
Clock functionality is not implemented and there is no clear format for answers.

I could enter 800, 8, 8.22229 without any error messages.

**Comment by hzhao392** [comment]
@ashreves which question is this for?

**Comment by ashreves** [comment]
@hzhao392 This was true for all questions that ask about time. Specifically, SLEEP1A is one of these questions.

**Comment by hzhao392** [comment]
@ashreves ok this is going to have to fall under an enhancement

**Comment by hzhao392** [comment]
I was wrong, TIME is already implemented as a feature for Quest

@stealthv please use |TIME| as laid out in the wiki https://github.com/episphere/quest/wiki

**Comment by stealthv** [comment]
@hzhao392 it seems that there is a problem with using the time widget along with a question that prompts the user for an answer. Even if you enter a time the user is shown the Response Requested dialog.

Example:
```
[Q1?]
Please enter a time
|time|

[END]
All Done
```

**Comment by hzhao392** [comment]
@stealthv this is fixed, please wait a few minutes for it to build and take another look

**Comment by ashreves** [comment]
@stealthv @hzhao392 I do not think that this is working. Here is what SLEEP1A looks like. There is no way to enter hours or minutes separately?
![image](https://user-images.githubusercontent.com/54043164/108566620-b594e780-72d4-11eb-837a-8bb7fc63b36d.png)

**Comment by stealthv** [comment]
@ashreves Sorry for any confusion, @hzhao392 was just letting me know that an underlying bug was fixed. Now we can update the markup to use the time widget.

**Comment by stealthv** [comment]
@ashreves This should be using the time widget now
