### ISSUE TITLE
Module 2- Piped text CHOLHTN2 –CHOLHTN6

### ISSUE THREAD

**Issue by ashreves** [episphere/quest#246]
Piped text for CHOLTN2-CHOLHTN6 not used, instead fills in answer from CHOLTN for MED. It makes the question look lengthy/wordy because it lists all of the possible medication names from previous question.

piped text:
if 01 selected fill [MED] = "statins/cholesterol or lipid lowering drugs and 
if 02 selected fill [MED] = "anti-hypertensive medication/drugs used to treat hypertension (high blood pressure)”]

**Comment by ashreves** [comment]
![image](https://user-images.githubusercontent.com/54043164/105544250-c0099480-5cc8-11eb-85b6-920f37b86732.png)

**Comment by stealthv** [comment]
should look better now

**Comment by ashreves** [comment]
@stealthv This looks better. However, the same problem exists for other medications like ACIDSUP. Please make sure all medications have the correct piped text in follow-up questions.

**Comment by ashreves** [comment]
This looks okay. Closing issue.
