### ISSUE TITLE
Module 2- Women’s Reproductive Health looping issue

### ISSUE THREAD

**Issue by ashreves** [episphere/quest#253]
There is an issue with looping in the women's reproductive health section.

If you answer never had a menstrual period (MENSHIS = I have never had a menstrual period), never pregnant (PREG = No), never used fertility drugs (FERT1 = No), you get placed back into the loop asking about menstrual health questions, starting at (MENSHIS2).

See screen recording here: https://drive.google.com/file/d/1uQWriB-i5N1wM6KGQugJHrvNzCp4W8A4/view

**Comment by hzhao392** [comment]
@stealthv you should probably have the question in two radio buttons, the first one will have the input for age and then the redirect to MENSHIS2_1 the second one will be no menstrual period with the redirect to PREG

you can replicate it with this:
https://gist.github.com/hzhao392/ca89db86b87254525d6aff25050f5914

**Comment by stealthv** [comment]
This should work as expected now

**Comment by ashreves** [comment]
@stealthv Seems to work now. Closing issue.
