### ISSUE TITLE
Module 2- LAWN1 logic

### ISSUE THREAD

**Issue by ashreves** [episphere/quest#255]
Able to have both "I did not do any of these activities" and any of the other responses selected. The "I did not do any of these activities" should clear the other responses.

**Comment by hzhao392** [comment]
@ashreves Can we remove the last option? Since this is a checkbox you are by default able to select one. If not then you use radio buttons but then you cannot select more than one answer. I think the last option does not make any sense here especially as the question is a has a soft require.

**Comment by ashreves** [comment]
@hzhao392 We do need the last option for LAWN1. Some participants might not do any of the activities, so we want to give them to option to answer that.

Doesn't similar functionality exist for medical conditions in module 1? See MHGROUP3 in Module 1.

**Comment by hzhao392** [comment]
Hi Alaina, yes we can do this. However, the answer ID for "I did not do any of these activities" must be 99. Is this ok?

**Comment by ashreves** [comment]
@hzhao392  This is a data question for @FrogGirl1123. The response isn't the same as prefer not to answer so I'm not sure 99 makes sense.

**Comment by FrogGirl1123** [comment]
@ashreves Thank you for tagging  me on this.  @hzhao392 I haven't posted an issue yet about the fixes that need to be made to the coding for answers like this.  I was a little confused about questions like this until I reviewed them with Alaina.  I'm planning to review these this week and will post an issue as soon as I do.  Please reach out if you have any questions.

**Comment by hzhao392** [comment]
@FrogGirl1123 sure, we spoke about issues like this in prep. Currently 99 is hardcoded to clear other selections, we talked about doing the similar clear for 77 or 88 as well

**Comment by danielruss** [comment]
stale ... closed
