### ISSUE TITLE
Module 2- WORKACT logic issue

### ISSUE THREAD

**Issue by ashreves** [episphere/quest#256]
According to logic, [DISPLAY WORKACT SECTION, IF WORK= 01]  [IF WORK= 00, GO TO INTROSITTING]. 

When testing using WORK= 00, was still asked this question.(I also tried with WORK=2 since I wasn't sure how it was originally coded in quest and still got the question)

**Comment by hzhao392** [comment]
@stealthv 
missing |grid,displayif=equals(WORK,1)| on the grid

**Comment by stealthv** [comment]
Fixed

**Comment by ashreves** [comment]
@stealthv I don't think that this is working.

**Comment by ashreves** [comment]
Working now. Closing issue.
