### ISSUE TITLE
Module 2- piped text SLEEPSCHA

### ISSUE THREAD

**Issue by ashreves** [episphere/quest#260]
Intro text to SLEEPSCHA is missing piped text for SEX=2.

According to logic, [DISPLAY IF SEX = 02, OR IF SEX = 03 AND SEX2 = 06 OR 07] "If you are currently pregnant or have been pregnant in the last year, please think about the time before you got pregnant."

**Comment by stealthv** [comment]
@ashreves I could not duplicate the problem. If you are still seeing this in the latest version please let me know what you are using in the Previous Results section.

**Comment by ashreves** [comment]
@stealthv This is still not working.

I am using this in previous results:
{"firstName":"Alaina","AGE":"55","SEX":["2"],"WORK":["1"]}

**Comment by stealthv** [comment]
@ashreves Could this be an issue with the browser again? It seems to be showing up for me
<img width="540" alt="Screen Shot 2021-02-12 at 1 06 37 PM" src="https://user-images.githubusercontent.com/394603/107805368-45fe8580-6d33-11eb-940f-f05670a5bb18.png">

**Comment by ashreves** [comment]
@stealthv Yes, I think the comments I made last night were browser issues.

**Comment by ashreves** [comment]
@stealthv Seems to be working. Closing issue.
