### ISSUE TITLE
Module 2- grid text not consistent SLHABIT1

### ISSUE THREAD

**Issue by ashreves** [episphere/quest#261]
Grid text on rows is centered for some rows and flush left for some rows. Please be consistent if possible.  

![image](https://user-images.githubusercontent.com/54043164/105545825-820d7000-5cca-11eb-87eb-d099d0ae5eaf.png)

**Comment by hzhao392** [comment]
@ashreves do you want everything to be just left aligned instead?

**Comment by ashreves** [comment]
@hzhao392 Sure, I just wanted the first column to be consistent down each row.

**Comment by hzhao392** [comment]
@ashreves ready to test

**Comment by ashreves** [comment]
@hzhao392 This is much better. I will close the issue.
