### ISSUE TITLE
Module 2- grid logic SLHABIT3

### ISSUE THREAD

**Issue by ashreves** [episphere/quest#262]
If row is left unanswered, a follow-up prompt should appear to ask participants to answer the question. Currently, if no items in a grid are selected, participants can easily move to next question without any prompting.

**Comment by hzhao392** [comment]
Bran,
https://github.com/episphere/quest/wiki/Grids
for soft and hard modals
You can add soft or hard edits to grids by adding ! or ? at the like so |grid!|

**Comment by stealthv** [comment]
@ashreves This should be fixed as of the update early this morning.

**Comment by ashreves** [comment]
Fixed. Closing issue.
