### ISSUE TITLE
Module 2- logic issue SLEEP1A, SLEEP1F, SLEEP2A, and SLEEP2F

### ISSUE THREAD

**Issue by ashreves** [episphere/quest#263]
Able to put any number for the time. Hours should be limited to 12. Blank AM/PM field should prompt follow up, but not be entirely required. Follow logic on Excel specs documentation.

**Comment by stealthv** [comment]
Like #264 it seems this should probably also use the `|time|` input as mentioned in #244

**Comment by stealthv** [comment]
This has been updated to use the time widget
