### ISSUE TITLE
Module 2- SHIFTWORK2 and SHIFTWORK5 logic

### ISSUE THREAD

**Issue by ashreves** [episphere/quest#264]
Able to put any number for the time. Hours should be limited to 12. Blank AM/PM field should prompt follow up, but not be entirely required. Follow logic on Excel specs documentation.

**Comment by stealthv** [comment]
It seems this should probably use the `|time|` input as mentioned in #244 
Then the am/pm options would not be needed since that is part of the time widget.

**Comment by stealthv** [comment]
This has been updated to use the time widget
