### ISSUE TITLE
Module 2- Soft edits missing (eg. age limitations)

### ISSUE THREAD

**Issue by ashreves** [episphere/quest#267]
Various questions in this module are missing logic associated with age. Please review spreadsheet's "SOFT EDIT" column to see logic. Ex. Create unique soft prompt that indicates the entered age must be equal to or less than current age + 2 as indicated in AGE or on enrollment form.

**Comment by hzhao392** [comment]
@ashreves this is similar to https://github.com/episphere/quest/issues/238 we cannot do method calculations in Quest as such it will be a enhancement for future releases

**Comment by ashreves** [comment]
@hzhao392 I see. How was this issue addressed for age question in Module 1 where age was the response for various medical conditions?

**Comment by hzhao392** [comment]
@ashreves strangely enough there is a difference function in module1 that will do a subtraction. I can add a sum function that does the addition

**Comment by hzhao392** [comment]
@stealthv You can use this age calculation to define the max
Age |__|__|min=0 max=sum(isDefined(AGE,99),2)|

**Comment by stealthv** [comment]
@ashreves Just to clarify, by a 'soft edit' do you mean that you want the user to be prompted if the value is outside of the range but not required to fix it to move on?

**Comment by ashreves** [comment]
@stealthv I'm not sure that I am using the hard/soft distinction correctly.

If the question is left blank, a soft edit asking them to answer should appear. If they decide not to answer after prompting, they should be able to skip.

If the question is answered (anything in blank), it must be answered within the possible range. They should not be able to enter an answer outside of the range.

Let me know if you need more clarification.

**Comment by stealthv** [comment]
@ashreves Thanks, that clears things up for me.

**Comment by hzhao392** [comment]
@ashreves, I thought this was a issue with the age ranges? Thus the age max=sum(isDefined(AGE,99),2) that I entered. If the age is outside of the range you will get an red error message so you will not be able to even click the next button. So I dont think this has anything to do with the "Soft Edit" prompt/

**Comment by stealthv** [comment]
The fields should all have the correct min/max logic now.

**Comment by ashreves** [comment]
@stealthv Did you apply logic for age limits to 99 or as an Acceptable range: 0 - 72? Based on the Excel sheet the range should be 0-72. I tested a few age questions and was able to put age as 79 and even 100.

**Comment by stealthv** [comment]
@ashreves I did. Some of the ranges specified allowing the current age+2 as the maximum but otherwise it should be limited to the current age and younger.

**Comment by ashreves** [comment]
@robertsamm and I will retest next week.

**Comment by ashreves** [comment]
Seems to be working, closing issue.
