### ISSUE TITLE
Module 2- logic MENSHIS

### ISSUE THREAD

**Issue by ashreves** [episphere/quest#268]
Able to put both an age at first menses AND select "I have never had a menstrual period". Should only be able to select one or the other. When both are selected clicking next moves the person straight to the PREG section. 

Was also unable to deselect "never had" except with the reset answer button. The reset answer button, however, did not erase the age I put in for the question.

**Comment by stealthv** [comment]
This has been fixed

**Comment by ashreves** [comment]
Fixed. Closing issue.
