### ISSUE TITLE
Module 2- logic HORMED4

### ISSUE THREAD

**Issue by ashreves** [episphere/quest#269]
Issue with logic. 

If I put an age for HORMED4 that is lower than my age for HORMED2, I get an error message. If I delete my entry and retype a new age that is older than HORMED2, I am not able to move forward. I can only move to the next question if I delete my response entirely and leave the response field blank.

**Comment by hzhao392** [comment]
@stealthv Are the HORNMED questions supposed to have a min value? It's not specified in the requirements. There are 9 similar conditions in the HORNMED questions
```
Age |__|__|id=COMPILL_LAST minval=isDefined(COMPILL_AGE,0) max=isDefined(AGE,age)|
```

**Comment by stealthv** [comment]
This has been fixed with the latest update

**Comment by ashreves** [comment]
@stealthv I just tried to test this, but was not able to get the reproduction section to render, even when I had SEX=2. I will test this when it is rendering again.

**Comment by ashreves** [comment]
@robertsamm and I will retest next week.

**Comment by ashreves** [comment]
@stealthv I was able to put an age in HORMED4 that is lower than my age for HORMED. I should only be able to enter an age equal to or greater than my age in HORMED2 if possible.

**Comment by danielruss** [comment]
stale ... closed
