### ISSUE TITLE
How do we allow users to indicate response text?

### ISSUE THREAD

**Issue by FrogGirl1123** [episphere/quest#27]
What is our default response text for soft and hard edits and end of the survey messaging?  Do we want to allow users to specify the text for soft and hard edits as they can for informational buttons? If so how?

**Comment by danielruss** [comment]
End of survey is a question with no next button and possibly no back.  The question text is the "informational message"

**Comment by FrogGirl1123** [comment]
@danielruss This is not the end of survey issue, this is the" how do investigators indicate the text they would like to have in soft or hard edit responses"

**Comment by danielruss** [comment]
Currently, there are 2 type of popups.  The first is an informational popup, like in the intro in module 1.  That is coded like this:  |popup|title|message| or |popup|message|, where the word "popup" is required, the "title" is optional user-supplied text, and "message" is required user-supplied text.  The second is message that pops up if the user doesn't answer a required/requested question (soft/hard edit)

**Comment by danielruss** [comment]
The soft/hard edits are not user configurable (yet?).

**Comment by danielruss** [comment]
Awaiting @FrogGirl1123 response before closing.

**Comment by ruggz13** [comment]
Right now, only soft edits are customizable
