### ISSUE TITLE
Module 2- questions missing PREG10-13

### ISSUE THREAD

**Issue by ashreves** [episphere/quest#273]
These questions appear to be missing in the module. I should have gotten them if I put PREG5=01,02, or 03. None of these selections displayed these questions. Instead it goes from PREGSUMMARY straight to FERT1

**Comment by hzhao392** [comment]
@stealthv because PREG5 is in a loop, you cannot use displayif=or(equals(PREG5,1),or(equals(PREG5,2),equals(PREG5,3)

Use PREG5_1_1 instead

**Comment by stealthv** [comment]
This should be working correctly now.

**Comment by ashreves** [comment]
@stealthv This is still not working.

**Comment by stealthv** [comment]
Hmmmm… it seems to work for me, please retest

**Comment by ashreves** [comment]
@stealthv retested and still not working.

**Comment by danielruss** [comment]
... stale issue...  closing
