### ISSUE TITLE
Module 2- Missing piped text PRESHOR3-6

### ISSUE THREAD

**Issue by ashreves** [episphere/quest#279]
Piped text not displayed.
Piped text: FILL [MED] = [text from PRESHOR2] OR, if no text entered at PRESHOR2, fill [the other type of prescription hormone]]

**Comment by hzhao392** [comment]
Hi Alaina, can you take another look at this? I just went through the questionnaire and when I got to this question I was able to get the pipe to render. If you cannot get it to render can you please let me know the steps so I can replicate.

Also, if you just copy and paste this section of the questionnaire it will render the pipe as well.
```
[PRESHOR?] Have you ever taken any other type of prescription hormones?
(1) Yes -> PRESHOR2
(2) No -> SECTION3
< #NR -> SECTION3 >

[PRESHOR2?] What other type of prescription hormones did you take? |__|id=otherPreHor|
< -> PRESHOR3 >

[PRESHOR3?] How old were you when you <b>first</b> used <b>{$otherPreHor}</b>?

Age |__|__|min=0 max=99|
< -> PRESHOR4 >

[PRESHOR4?] Are you currently using <b>{$otherPreHor}</b>?
(1) Yes -> PRESHOR6
(2) No -> PRESHOR5
< #NR -> PRESHOR5 >

[PRESHOR5?] How old were you when you <b>last</b> used <b>{$otherPreHor}</b>?

Age |__|__|min=0 max=99|
< -> SECTION3 >

[PRESHOR6?] In total, how many months or years have you used <b>{$otherPreHor}</b>?

#Months |__|__|id=preshor2Month min=0 max=99|OR
#Years |__|__|id=preshor2Year min=0 max=99|
< -> SECTION3 >

[SECTION3]<b>Physical Activity</b>
```

**Comment by ashreves** [comment]
@hzhao392 I just tested it again. It works if you type something into the field in PRESHOR2. If you leave PRESHOR2 blank, it does not fill in fill [the other type of prescription hormone].

**Comment by hzhao392** [comment]
If otherPreHor is empty, since it is optional, use this text instead "the other type of prescription hormone"

**Comment by stealthv** [comment]
This has been fixed in the latest update

**Comment by ashreves** [comment]
@stealthv I just tried to test this, but was not able to get the reproduction section to render, even when I had SEX=2. I will test this when it is rendering again.

**Comment by ashreves** [comment]
@stealthv Seems to work. Closing issue.
