### ISSUE TITLE
Looping does not "mangle" ids for displayed variable substitution

### ISSUE THREAD

**Issue by danielruss** [episphere/quest#281]
If you have a loop and you define a variable, you cannot display that variable in the loop.

see: 
https://episphere.github.io/quest/?#https://danielruss.github.io/questtest/MyFirstModule.txt

go to the loop (answer that you like dogs to save time)...  say you have two kids,  for the first kid, when the module asks if you have kidname has a peanut allergy, it works.  The second time through the loop, it gives the name of the first child.

**Comment by hzhao392** [comment]
I dont think this ever worked, I asked IMS to use displayif instead of loops. This will need to be addressed by IDIQ.

**Comment by danielruss** [comment]
I loop all variable defined via (id="xxx") within and mangle the names.
