### ISSUE TITLE
Module 1- Remove SSN from module

### ISSUE THREAD

**Issue by ashreves** [episphere/quest#283]
We have moved SSN to a separate module.

The questions SOCIALSECUR1 and SOCIALSECUR2 should be removed from Module 1. 

Skip pattern from PPLHOUSE should now go to INTROCNT.

**Comment by ashreves** [comment]
Just wanted to connect this with the issue that @brotzmanmj just added.

The is related to  quest/connect#272

**Comment by danielruss** [comment]
stale ... closed
