### ISSUE TITLE
Module 3 - Age ranges inconsistent 

### ISSUE THREAD

**Issue by ashreves** [episphere/quest#284]
Ranges on the age questions are very inconsistent. Some of them have requirement for age ranges and some do not.

Please make sure all age issues have ranges as described on the Excel file.

**Comment by stealthv** [comment]
I have updated Module 3 to match what is specified in the XML file.

I did want to point out that some fields have a range of 1-99 while some other very similar fields have a range of 1-999. Not sure if this is a typo or on purpose so I just wanted to point it out.

Also, for the time being while testing Module 3 please use 'AGE' instead of 'age' in the previous results. Once #285 is resolved we should be able to update Module 3 to support either.

**Comment by ashreves** [comment]
@stealthv Have you found places were ranges for age were 999? I just reviewed the Excel file and it looks like questions asking about product use had limits of 999, not age questions. 

I just tested one example (SMMAR2) and I was able to enter an age older than my current age. I was tested using 'AGE,' but it did not give me a soft edit. Please make sure age limits exist for all other questions as specified on the Excel sheet.

**Comment by stealthv** [comment]
@ashreves The fields I mentioned that had ranges of 1-999 were not age range fields (sorry I wasn't clear about that). I was just noticing that some of the product use fields had ranges of 1-99 while others had ranges of 1-999.  For example CIGAR9A has a range of 1-99 while CIGAR9C has a range of 1-999. They seem like the same question so I just wanted to point it out in case it was an error.

**Comment by stealthv** [comment]
@ashreves Also, could you re-check that you were using the latest markup. SMMAR2 should be fine.
Here is the markup from module3.txt
```
[SMMAR2?,displayif=equals(MARIJUANA,1)] How old were you when you <b>first</b> smoked marijuana?

Age first smoked marijuana |__|__|id=FIRSTSMMAR_AGE min=0 max=isDefined(AGE,age)|< -> SMMAR3>
```
And here is screenshot when I try it out
<img width="540" alt="Screen Shot 2021-02-12 at 10 38 56 AM" src="https://user-images.githubusercontent.com/394603/107788878-e8603e00-6d1e-11eb-8dfe-233ad2ea47b1.png">

**Comment by ashreves** [comment]
@robertsamm and I will retest next week.

**Comment by ashreves** [comment]
This seems to be working now. Closing issue.
