### ISSUE TITLE
Unable to use previous results as piped text

### ISSUE THREAD

**Issue by stealthv** [episphere/quest#285]
If you try to use previous results as piped text an exception occurs in the javascript and you end up with a blank page. Using the previous results in functions seems to work as expected.

### Example
Previous Results:
```
{"AGE":"55"}
```
Markup:
```
[START]
Let's review

[Q1]
You are {$AGE} years old.

[END]
Thanks
```

**Comment by hzhao392** [comment]
Hi Bran, this was an existing ability, but was never captured in the Wiki. I just added this to the Wiki, please give this a try.

Piped input response
{$u:ID} – This allows for piped variable from inputs into quest. For example: ```{"AGE":"55"}`` is the input value. To display this please use ```[Q1] You are {$u:AGE} years old.```

**Comment by stealthv** [comment]
Ok, that does seem to work. Thanks!

**Comment by danielruss** [comment]
@hzhao392  The {$u:} notation was initially supposed to be the user profile data.  Now whether it comes from the user profile or another module is irrelevant. I meant to remove the notation, because it is we should be using {$xx}.

**Comment by stealthv** [comment]
Reopening because I believe there is a bug. If you try to use more than one of these in a question it causes an exception. I think this is because the regex in replace2.js is not global.

### Example
Previous Results:
```
{"age":"12"}
```

Markup:
```
[START]
Click NEXT to begin

[Q1]
AGE is {$u:AGE}

[Q2]
age is {$u:age}

[Q3]
AGE is {$u:AGE}
age is {$u:age}

[END]
All Done
```

We need this functionality in module 3. There are several places where we need to show the user's age. Therefore it needs to check and show 'AGE' if defined otherwise show 'age'. Since the markup to do this must include multiple {$u:} statements it fails.

**Comment by stealthv** [comment]
@hzhao392 Just a heads up that I re-opened this issue in case you weren't notified.

**Comment by hzhao392** [comment]
@stealthv this is fixed now for two or more user inputs
