### ISSUE TITLE
Module 2- Intro text missing INTROWH

### ISSUE THREAD

**Issue by ashreves** [episphere/quest#286]
I think INTROWH is missing.

Did not appear for SEX=2

**Comment by stealthv** [comment]
@ashreves I looked at the markup and it should be showing for SEX=2 or (SEX=3 and SEX2=6 or 7). I'm assuming this is related to the testing issues you encountered last week.

**Comment by ashreves** [comment]
@stealthv It is rendering now, but has a bar at the end of the text

![image](https://user-images.githubusercontent.com/54043164/108565001-ffc89980-72d1-11eb-9924-def39ad18f18.png)

**Comment by robertsamm** [comment]
@stealthv The INTROWH is still not rendering for SEX=3 and SEX2=6. Did not test with SEX2=7.

Tested with: 
{"firstName":"Amelia","AGE":"55","SEX":["3"],"SEX2":["6"], "GEN":["3"],"WORK":["1"]}
{"firstName":"Amelia","AGE":"55","SEX":["3"],"SEX2":["6"], "GEN":["2"],"WORK":["1"]}

**Comment by robertsamm** [comment]
Still missing INTROWH for SEX=3 and SEX2=male sex organs. Tested with: {"firstName":"Amelia","AGE":"55","SEX":["3"],"SEX2":["6"], "GEN":["3"],"WORK":["1"]}

Moving to triage.

**Comment by robertsamm** [comment]
@hzhao392 I am still not seeing INTROWH for SEX=3 and SEX2=6 or 7 (female sex organs). It is actually skipping past the rest of the women's health section (except for INTRONONCISWOM and HORNONCISWOM) and the testosterone questions and going straight to the physical activity section.

**Comment by danielruss** [comment]
stale ... closed
