### ISSUE TITLE
Module 2 - EXEREC2H- check capitalization on piped text

### ISSUE THREAD

**Issue by ashreves** [episphere/quest#289]
Capitalization not correct on piped text for "yoga, Pilates, or tai chi"

This affects EXEREC2H, EXEREC3H, and EXEREC3H.

![image](https://user-images.githubusercontent.com/54043164/108568763-a9ab2480-72d8-11eb-8bd3-d6d1eb3ea381.png)

**Comment by stealthv** [comment]
@ashreves This is the capitalization that is in the Word document we have. I'm assuming you would each name to be capitalized like they are in EXEREC1? - Yoga, Pilates, or Tai Chi

**Comment by ashreves** [comment]
@stealthv Yes, capitalize please.

**Comment by danielruss** [comment]
stale ... closed
