### ISSUE TITLE
Module 2- #pills & #units, can enter value and "don't know"

### ISSUE THREAD

**Issue by ashreves** [episphere/quest#291]
In several places, I was able to enter values and also select "don't know." If one is filled, the other should be cleared before moving towards the next question.

See PAINREL3, CHOLHTN3,  ACIDSUP3, and INSULIN3. Please make sure all similar question are corrected too.

![image](https://user-images.githubusercontent.com/54043164/108569110-4ff72a00-72d9-11eb-9726-a7594018b566.png)

**Comment by stealthv** [comment]
These are now presented as 2 options so that you can only choose one or the other

**Comment by ashreves** [comment]
Fixed. Closing issue.
