### ISSUE TITLE
Module 2 - Addtl intro text for INTROM2 missing

### ISSUE THREAD

**Issue by robertsamm** [episphere/quest#296]
The additional intro text is missing for SEX=3 AND SEX2=6. Intro text below.

[DISPLAY ADDITIONAL INTRO TEXT BELOW IF SEX = 02 OR IF SEX = 03 AND SEX2 = 07 or 06] You will also be asked some questions about your reproductive health. These questions will mostly focus on your menstrual periods, pregnancies, and if you have used any hormonal medications.

Tested with:
{"firstName":"Amelia","AGE":"55","SEX":["3"],"SEX2":["6"], "GEN":["2"],"WORK":["1"]}
{"firstName":"Amelia","AGE":"55","SEX":["3"],"SEX2":["6"], "GEN":["3"],"WORK":["1"]}

**Comment by stealthv** [comment]
@robertsamm I tested with both of the data sets you listed and the extra text is displayed. Maybe your browser is holding onto old data?

**Comment by robertsamm** [comment]
Still missing the additional intro text. 

@hzhao392 There's def no other way my browser is holding onto the old data after clearing my browser history and using incognito mode?

![image](https://user-images.githubusercontent.com/67074735/110173357-74203400-7dcc-11eb-9ede-3aaa7aa19da2.png)

Moving to triage.

**Comment by robertsamm** [comment]
I see that this is working correctly now. I reloaded the markup incorrectly. Closing.
