### ISSUE TITLE
Module 2 - Addtl sleep intro text missing

### ISSUE THREAD

**Issue by robertsamm** [episphere/quest#297]
Additional sleep intro missing for SEX=3 AND SEX=6. Intro text below.

[DISPLAY IF SEX = 02, OR IF SEX = 03 AND SEX2 = 06 OR 07] If you are currently pregnant or have been pregnant in the last year, please think about the time before you got pregnant.

Tested with:
{"firstName":"Amelia","AGE":"55","SEX":["3"],"SEX2":["6"], "GEN":["2"],"WORK":["1"]}
{"firstName":"Amelia","AGE":"55","SEX":["3"],"SEX2":["6"], "GEN":["3"],"WORK":["1"]}

**Comment by stealthv** [comment]
@robertsamm I tested with these and it shows for me.
<img width="610" alt="Screen Shot 2021-02-23 at 4 48 16 PM" src="https://user-images.githubusercontent.com/394603/108912859-3155a380-75f7-11eb-8a6a-7a464b9fb86a.png">

**Comment by robertsamm** [comment]
Still not displaying on my end. Tested in incognito mode and cleared my browser history.

![image](https://user-images.githubusercontent.com/67074735/110172856-c3b23000-7dcb-11eb-953f-b43f015a4246.png)

Moving to triage.

**Comment by robertsamm** [comment]
This is working correctly now SEX=3 AND SEX2=6. Closing.
