### ISSUE TITLE
Module 2 - INTRONONCISWOM and HORNONCISWOM missing

### ISSUE THREAD

**Issue by robertsamm** [episphere/quest#299]
Both the intro text INTRONONCISWOM and question for HORNONCISWOM is missing for SEX=3, SEX2=6, GEN=2.

Both should display if: SEX= (01 “MALE” OR 03 “INTERSEX OR OTHER”) AND GEN= (02 “FEMALE”, 04 “TRANSGENDER FEMALE”, 05 “GENDERQUEER”, OR 06 “ADDITIONAL GENDER”)

Tested with:
{"firstName":"Amelia","AGE":"55","SEX":["3"],"SEX2":["6"], "GEN":["2"],"WORK":["1"]}
{"firstName":"Amelia","AGE":"55","SEX":["3"],"SEX2":["2"], "GEN":["4"],"WORK":["1"]}

**Comment by stealthv** [comment]
@robertsamm Seems to be working for me. Maybe an issue with the browser cache?
<img width="623" alt="Screen Shot 2021-02-23 at 5 00 06 PM" src="https://user-images.githubusercontent.com/394603/108913958-b42b2e00-75f8-11eb-8bde-1ae4e64e8fda.png">

**Comment by robertsamm** [comment]
Tested in incognito mode and still not seeing the INTRONONCISWOM intro or the HORNONCISWOM question for SEX=3, SEX2=6, GEN=2. Tested with: {"firstName":"Amelia","AGE":"55","SEX":["3"],"SEX2":["6"], "GEN":["2"],"WORK":["1"]}

Moving to triage.

**Comment by robertsamm** [comment]
I see that this is working correctly now. I reloaded the markup incorrectly. Closing.
