### ISSUE TITLE
Module 2- Stuck in pregnancy loop

### ISSUE THREAD

**Issue by ashreves** [episphere/quest#306]
I got caught in a loop in the pregnancy and it sent me back to the menstrual history questions. Amelia duplicated the sequence and had the same problem. 

Here's a screen recording of the problem:  https://drive.google.com/file/d/1orE_Jl1QFSUGsh81IuBNNVNlFJqu_12k/view

**Comment by stealthv** [comment]
I found the bug. This should be fixed now.

**Comment by ashreves** [comment]
Fixed, closing issue.
