### ISSUE TITLE
Error messages being removed in div removal

### ISSUE THREAD

**Issue by hzhao392** [episphere/quest#307]
https://github.com/episphere/quest/commit/07debe9b570c18f706b6be7999f1ddf6d04b4bcf#r48140072

https://files.gitter.im/602c0f2d6da03739846228f2/IqWp/image.png
https://files.gitter.im/602c0f2d6da03739846228f2/EQcW/image.png

**Comment by kundan22197** [comment]
Div is added only to display error messages, otherwise it is removed. The issue is fixed.
