### ISSUE TITLE
Module 3- Grid upper age limit

### ISSUE THREAD

**Issue by ashreves** [episphere/quest#311]
SECSMLF2 – SECSMLIF2H: Upper limit of grid should be current age. I tested with AGE=55 and was still shown row with upper limit AGE=59. 

Same with ALCLIFE1 Grid. Please check all grids.

**Comment by stealthv** [comment]
@hzhao392 any thoughts on this? This would require using a displayif and maybe piped text within the text of a grid row. As far as I can tell there is no way to do that.

**Comment by hzhao392** [comment]
@ashreves Quest current does not support this. We will need to discuss on how this is done.

**Comment by danielruss** [comment]
stale issue clossing
