### ISSUE TITLE
Module 3- Move grid text

### ISSUE THREAD

**Issue by ashreves** [episphere/quest#312]
SECSMLF2 – SECSMLIF2H Have question text on same screen as grid if possible. 

Same for ALCLIFE1 and other grids.

**Comment by stealthv** [comment]
This has been done for SECSMLF2 and SECSM.
This can't be done for ALCLIFE1 because that text uses piped text and displayif statements for the ages. Quest doesn't support doing that within the grid text.

**Comment by ashreves** [comment]
@stealthv If it can't be done, I'll close the issue. This might just be something we get feedback on while testing the PWA.
