### ISSUE TITLE
Module 3 - Text Appearance Issue TANBED5

### ISSUE THREAD

**Issue by ashreves** [episphere/quest#313]
This question response text does not appear correctly. The parenthesis should be included on the response line, not below. 
![image](https://user-images.githubusercontent.com/54043164/111176229-86922e80-857f-11eb-851c-1c9ed64bd51e.png)

**Comment by stealthv** [comment]
@hzhao392 This seems to be a parsing issue. Is there a way to escape the () inside the question text or do we need to use a different character?

**Comment by hzhao392** [comment]
```
[TANBED5?] How often do you usually use a tanning bed?
(1) every day or almost every day (20-31 days a month)
(2) a few days per week (5-19 days per month)
(3) once a week
(4) a few times per month (1-4 days per month)
(5) less than 12 times per year

```

Hi @kundan22197 , can you add an escape pattern for parentheses () and square brackets [] so questions like above will render properly.

**Comment by kundan22197** [comment]
fixed
