### ISSUE TITLE
Module 3- Information text EYECOLOR

### ISSUE THREAD

**Issue by ashreves** [episphere/quest#314]
Informational text should be on "HAZEL" text, not as separate "INFORMATIONAL TEXT" bubble.

![image](https://user-images.githubusercontent.com/54043164/111176374-a9244780-857f-11eb-8501-eaa3eff705ad.png)

**Comment by cyrjeant** [comment]
This should be fixed now

**Comment by ashreves** [comment]
Fixed, closing issue.
