### ISSUE TITLE
Module 3- Info Bubble Sizing Issue

### ISSUE THREAD

**Issue by ashreves** [episphere/quest#316]
Informational text incomplete. Missing part of last sentence. (3/11 update) I like the colored box change, but still cutting off part of the info text.

[Informational text when “regular basis” is selected: We understand that the meaning of "regular basis" might be different for different people. When you answer this question, please think about what "regular basis" means to you.]

ECIG3 and all informational texts for "regular basis."

![image](https://user-images.githubusercontent.com/54043164/111176835-0f10cf00-8580-11eb-9824-8e9165335a15.png)

**Comment by hzhao392** [comment]
@ashreves we cannot replicate this. Can you show us how you got this to display?

**Comment by kundan22197** [comment]
yeah, it is fixed now!
