### ISSUE TITLE
Display additional input fields

### ISSUE THREAD

**Issue by FrogGirl1123** [episphere/quest#32]
Need syntax and mechanism to display additional input fields for items like email address or phone numbers.  Also need to be able to specify the maximum number of additional inputs. The specs request a + button the user could click to get an additional field.

User profile criteria are here https://nih.app.box.com/file/501193852134

I still need to update the mark up.

**Comment by danielruss** [comment]
I think this is working now.  However, User Profile is no longer using quest.  Okay to close?

**Comment by ruggz13** [comment]
Ok to close.
