### ISSUE TITLE
Error when using 77, 88, 99 in a multi-select that includes a textfield

### ISSUE THREAD

**Issue by stealthv** [episphere/quest#320]
If you have a multi-select question (checkboxes) and

- it includes an answer that has a corresponding textfield
- it has an answer with the value 77 (or 88 or 99)

Then when you select the 77 answer an exception is shown in the console. Also, checking this value in a later question will not work properly

Example:
```
[START]
Let's go

[Q1]
Select all that apply
[0] Option 0
[1] Option 1
[2] Option 2
[3] Other |__|OTHER_OPTION|
[88] None of the above

[RESULTS]
|displayif=equals(Q1,0)|You selected option 0|
|displayif=equals(Q1,1)|You selected option 1|
|displayif=equals(Q1,2)|You selected option 2|
|displayif=equals(Q1,3)|You selected other option|
|displayif=equals(Q1,77)|You selected none of the above|

[END]
All Done.
```

I am not aware of a workaround besides removing the text field.

**Comment by kundan22197** [comment]
Fixed
