### ISSUE TITLE
Module 4- no limit on digits

### ISSUE THREAD

**Issue by ashreves** [episphere/quest#324]
There does not seem to be a limit on digits for year fields (ex. Can enter 1, or 3939393 for HOMEADD1_1 enter House #). Please make sure there is a limit matching the specs file.

**Comment by stealthv** [comment]
@ashreves I don't understand. All of the year fields appear to have a limit specified. HOMEADD1_1 House # is not a year field and I don't see a limit for house number specified in the specs file.

**Comment by ashreves** [comment]
@stealthv Can you please add a limit for house number fields? No negative numbers and max number is 999999.

**Comment by stealthv** [comment]
@ashreves Sure thing.
I do want to point out that for the 'Apartment, suite, unit, building, etc.' field that is just free text so we can't put any limits on that but we will for street number and zip code.

**Comment by ashreves** [comment]
@stealthv DRINKSWTR2A and other questions about number of times per day should not allow negative number and should have a max of 999.

**Comment by stealthv** [comment]
Should be fixed

**Comment by danielruss** [comment]
stale issue .. closing
