### ISSUE TITLE
Module 4- Images blurry

### ISSUE THREAD

**Issue by ashreves** [episphere/quest#326]
The images are very blurry. Is there anything we can do to address this? Example is CURWORKT3.

**Comment by hzhao392** [comment]
Hi @ashreves , we would need images with higher resolutions. How did we get these images in the first place?

**Comment by ashreves** [comment]
@stealthv NORC provided JPEGS and links to the original files. They can be found in [this Box folder](https://nih.app.box.com/folder/134620554627) that I shared with DevOps.

**Comment by danielruss** [comment]
@hzhao392 The images look good on box. Are you sure it is a resolution error?

**Comment by hzhao392** [comment]
@danielruss 
the image that Alaina is talking about in CURWORKT3 is hosted here

https://github-production-user-asset-6210df.s3.amazonaws.com/64271614/86169815-34d86f80-bae8-11ea-98a6-1b3de33fedf0.png

it has a 230x172 resolution

**Comment by danielruss** [comment]
Is this still a problem?
