### ISSUE TITLE
WCAG section 508 issues

### ISSUE THREAD

**Issue by hzhao392** [episphere/quest#329]
@kundan22197  can you add the aria labels for input boxes? they are current not passing WCAG testing. Please test other input fields as well. Let me know if you need help setting up the WAVE tool.

![image](https://user-images.githubusercontent.com/57492029/114080708-ae706b80-9879-11eb-9585-98b963882cb5.png)

**Comment by kundan22197** [comment]
Fixed. Just check it and let me know if other changes are required.
