### ISSUE TITLE
Rendering problem when displayif on same line as question id

### ISSUE THREAD

**Issue by stealthv** [episphere/quest#331]
We ran into some questions that used to render correctly but now fail. The problem seems to be when the line that contains the question id also contains a displayif and the question has a field specified.

Here is an example:
```
[START]
Example of rending issue. The first question renders fine. The second one doesn't. The only difference is the displayif not being on the same line as the question id.

Click Next

[Q1]
This is the |displayif=equals(1,1)|first| question.
|__|__|


[Q2]This is the |displayif=equals(1,1)|second| question
|__|__|

[END]
All Done
```

The first question renders as expected  but the second question doesn't. It looks like this:
<img width="579" alt="Screen Shot 2021-05-04 at 2 12 18 PM" src="https://user-images.githubusercontent.com/394603/117049988-d7521800-ace2-11eb-9cb3-89af409ce340.png">

**Comment by danielruss** [comment]
@kundan22197   I thiink this is caused by confusion in the [Q2] question id.  Notice there is no space between [Q2] and this. @stealthv can you add a space and see if the problem goes away.

**Comment by stealthv** [comment]
@danielruss No, adding a space does not fix it.

**Comment by kundan22197** [comment]
Fixed
