### ISSUE TITLE
Calculate age from dob

### ISSUE THREAD

**Issue by FrogGirl1123** [episphere/quest#35]
Calculate age from DOB given and use for both validation (participant meets age requirements) and as piped in age in first question of Module 1.  

One option is to create a derived variable that is read into module 1, however, derived variable has to be updated over time.  I'll add the derived variable to the codebook in the mean time as a place holder.

**Comment by danielruss** [comment]
This is probably best handled by the questionnaire user.

**Comment by ruggz13** [comment]
Going with the general consensus of this is being push the Questionnaire user. Not core-Quest related
