### ISSUE TITLE
Other 55: Text box not storing numeric data

### ISSUE THREAD

**Issue by Davinkjohnson** [episphere/quest#356]
When textbox entered in select all that apply with other + textbox, user is not redirected to the follow-up questionsfor the non-other choices

We determined this was a Quest issue when testing in the renderer: When data is entered in text box, the numeric responses (including the 55 are not being stored).

**Comment by danielruss** [comment]
@Davinkjohnson  Was this issue resolved?  When I select 1,2,3,8 (20), I go to the correct questions?  If this was resolved, please close the issue.

**Comment by Davinkjohnson** [comment]
I had left this issue open as we tested and didn't see the error re-occur, but wanted to continue monitoring.

**Comment by Davinkjohnson** [comment]
Have not seen this issue in over 3 months. Closing now. (Open new issue if it re-occurs.)
