### ISSUE TITLE
Issue with renderer & displayif statements

### ISSUE THREAD

**Issue by boyd-mj** [episphere/quest#358]
@FrogGirl1123, @danielruss, @iqbal-singh, @Davinkjohnson 
We are encountering issues with displayif statements not functioning as expected in some cases. All of the cases we've encountered so far have involved displayif statements that reference variables from other modules. This is happening when the previous results option is used and added to JSON on the testing site. We initially encountered this when testing the ALCLIFE grids, which use AGE (all questions display regardless of what's entered), but have since encountered it with some Module 4 questions that rely on WORK & WORK6 among others. In some cases, no code changes have been made since we last tested so we wondering if this is an issue with the previous results function of the rendered, or possibly Quest? 

I'm out tomorrow, but @joshid-ims may be able to provide more details if needed in my absence.

**Comment by danielruss** [comment]
I think  I fixed the first issue here..  grids with displayif were not working.  The second issue is if you use information from another module, it cannot be used with display if.  working on that next

**Comment by danielruss** [comment]
actually it may work completely.  waiting for @iqbal-singh

**Comment by danielruss** [comment]
also fixed the problem where the previousResults where not being considered (for exists, doesNotExist, noneExists, valueEquals, valueIsOneOf).

**Comment by joshid-ims** [comment]
Thanks. We will test on Monday.

**Comment by danielruss** [comment]
@joshid-ims ...  waiting on @iqbal-singh  Nothing has been checked into production yet.

**Comment by danielruss** [comment]
@joshid-ims,   @iqbal-singh  finished his review.  Ready for testing

**Comment by joshid-ims** [comment]
Thanks. We will test this.

**Comment by danielruss** [comment]
stale issue...  closing...
