### ISSUE TITLE
Text box for write-in answers takes ~30 seconds to load

### ISSUE THREAD

**Issue by depietrodeanna** [episphere/quest#361]
Tester (using iPad) reported difficulty clicking on the check box to answer "something else" or "other" for applicable questions.  It seemed intuitive to click the box itself, but clicking on the actual text "something else" was needed to register a response. It took the text box ~30 seconds to activate for write-in answers. Can we increase speed? 

Secondary- is it possible to configure the answer options so the check box next to each "something else" option activates the write-in?

**Comment by danielruss** [comment]
@depietrodeanna What question was this?

**Comment by depietrodeanna** [comment]
@danielruss following up with the tester now

**Comment by danielruss** [comment]
@depietrodeanna  when you get the followup from the tester, if the problem still exists.  please make a comment and remove the "Waiting for Feedback" label

**Comment by depietrodeanna** [comment]
Tester does not recall specifics. I think we can close this issue for now and reopen if we hear that others are having similar problems @danielruss
