### ISSUE TITLE
Production Participant Issues with Questionnaire

### ISSUE THREAD

**Issue by FrogGirl1123** [episphere/quest#362]
Please see feedback from prod participant on issues with Module 1.  @danielruss I will reach out to you to discuss details.
[Participant_1_Feedback_Health Survey INFO_2021_1111.docx](https://github.com/episphere/quest/files/7563989/Participant_1_Feedback_Health.Survey.INFO_2021_1111.docx)

**Comment by danielruss** [comment]
Thank you @Davinkjohnson  for pointing out the problem.  When the user hit the tab key, the focus moves to the next item in the xor.  SO...  as soon as the user hits next, the handleXOR method clears the filled value and complains that nothing is selected.  

Bug fixed...  but had to return a empty value that was place in the results object.  To avoid this I added a line that prevents a blank value from being written into the object.  This may cause problems in other parts of the code..  Be wary of empty items being dropped.

**Comment by danielruss** [comment]
@Davinkjohnson  Ready for testing please close if it passes.
