### ISSUE TITLE
Issue with displayif or equals/doesNotEqual - Module 4

### ISSUE THREAD

**Issue by joshid-ims** [episphere/quest#365]
For the code below, displayifs in the question itself work but the same displayifs in the response option 5 do not work. 

[DRINKSWTR2F?,displayif=equals(DRINKSWTR1,55)] In a <b>usual week</b>, about how often do you use tap water from your home to make |displayif=doesNotEqual(DRINKSWTR1_OTH,"")|<b>{$DRINKSWTR1_OTH}</b>||displayif=equals(DRINKSWTR1_OTH,"")|other beverages|?
(0) times/day |__|__|id=DRINKSWTR2F_NUM min=0 max=999|
(1) 5-6 times/week
(2) 3-4 times/week
(3) 1-2 times/week
(4) Less than once a week
(5) I drink tap water in |displayif=doesNotEqual(DRINKSWTR1_OTH,"")|<b>{$DRINKSWTR1_OTH}</b>||displayif=equals(DRINKSWTR1_OTH,"")|other beverages| but don’t know how often

![image](https://user-images.githubusercontent.com/64986739/144911537-e471a550-4c9d-41c9-8bd0-a40dc8c736dc.png)

**Comment by danielruss** [comment]
@joshid-ims  This is was quest coding coding error.  We handle displayif's is questions, response and  conditional text, but NOT condition text in a response.  I just pushed a fix.  If it works, please close.

**Comment by joshid-ims** [comment]
Working now.
