### ISSUE TITLE
#currentMonth function

### ISSUE THREAD

**Issue by joshid-ims** [episphere/quest#378]
#currentMonth (in numbers 1-12, not text like Jan, Feb, etc. ) function like #currentYear is required to code Biospecimen questionnaire.

**Comment by danielruss** [comment]
2 macros:
#currentMonth returns a digit from 1->12
#currentMonthStr returns Jan, Feb, Mar,...,Dec

**Comment by joshid-ims** [comment]
Daniel, can you please post a ink to WiKi where this multiplication function is documented there?

**Comment by danielruss** [comment]
https://github.com/episphere/quest/wiki/Updated-displayif-function#handling-simple-math
