### ISSUE TITLE
valueOrDefault does not work with double quotes

### ISSUE THREAD

**Issue by joshid-ims** [episphere/quest#385]
In a question like this:
```
[CIG3?,displayif=equals(TOBACCO,0)]
How old were you when you started smoking cigarettes on a |popup|regular basis|Informational Text|We understand that the meaning of 'regular basis' might be different for different people. When you answer this question, please think about what 'regular basis' means to you.|?

Age started smoking cigarettes on a regular basis |__|__|id=CIG3_AGE min=valueOrDefault("CIG2",0) max=sum(isDefined(AGE,age),1)|

[44*] Never
```
data-min for valueOrDefault does not work correctly. Gives this error:

![image](https://user-images.githubusercontent.com/64986739/161280081-b418bf23-c4d8-4c72-8af4-21a3129386d6.png)

**Comment by danielruss** [comment]
when parsing the number arguments (i.e.  |__|__|arg1=lala arg2=min("a","b") ) double quotes are now converted to single quotes.

**Comment by joshid-ims** [comment]
Now I get this error 

![image](https://user-images.githubusercontent.com/64986739/161310597-daa0e758-5aed-44bb-91a5-f715a136ce8d.png)

**Comment by danielruss** [comment]
Works for me.  What responses are you selecting?

**Comment by joshid-ims** [comment]
0 for Tobacco, then 50 to 99. AGE defined as 25 through json memory.

**Comment by danielruss** [comment]
Works for me.  Maybe a phone call?

**Comment by joshid-ims** [comment]
sure

**Comment by danielruss** [comment]
please close if it is working
