### ISSUE TITLE
Error does not show up for wrong data entered

### ISSUE THREAD

**Issue by joshid-ims** [episphere/quest#386]
For min and max limits the errors for incorrect (out of limits) values do not show up. 

Question example:
```
Age started smoking cigarettes on a regular basis |__|__|id=CIG3_AGE min=valueOrDefault("CIG2",0) max=sum(isDefined(AGE,age),1)|
```

**Comment by danielruss** [comment]
I think this is related to #385.  These should both be fixed now.
