### ISSUE TITLE
Removing single quotes around displayif not working

### ISSUE THREAD

**Issue by boyd-mj** [episphere/quest#387]
@danielruss we have tested this (removing quotes around displayif statements that includes an "and" and thus spacing) and the displayifs are not functioning as expected in either the main renderer or your personal renderer. I will have someone post additional details as soon as possible, but wanted to alert you since this is related to finishing Module 4. 

@guinevere83 or @huip-ims please add details for Daniel

**Comment by guinevere83** [comment]
Sure. Seems like the changes for summary screens are showing 2nd Address, 3rd Address etc. regardless of if there were NR values for those addresses. Previously, they wouldn't display:

![image](https://user-images.githubusercontent.com/75336502/162243215-4070261c-06c4-4932-8eb3-44d070978469.png)

For the childhood address summary, it's causing stray code to show up like so:

![image](https://user-images.githubusercontent.com/75336502/162243826-8137b256-6582-4090-9401-3b7c3214fa32.png)

**Comment by danielruss** [comment]
ok.  This is in module 4?

**Comment by huip-ims** [comment]
Daniel, you're correct. It's in module 4.

**Comment by danielruss** [comment]
pushed a fix.

**Comment by boyd-mj** [comment]
@guinevere83 please retest this section

**Comment by guinevere83** [comment]
![image](https://user-images.githubusercontent.com/75336502/162279245-01a6f3c8-2685-4812-906a-e5de5ef3cc02.png)

This looks to be resolved. Thanks!
