### ISSUE TITLE
Grid column width

### ISSUE THREAD

**Issue by huip-ims** [episphere/quest#392]
@danielruss @boyd-mj Hi Daniel - In the biospecimen survey, there are some grids with very cramped columns. Is there a way to specify the column width in grids? See screenshot attached.

![grid_columns](https://user-images.githubusercontent.com/82978291/165306650-4cd82001-8885-4e23-81dc-746d7d3f4633.png)

**Comment by danielruss** [comment]
I'll take a look.  I warned the PI's that grids are not ideal for an online survey.  They are great for a paper survey, not for online survey.

**Comment by boyd-mj** [comment]
@huip-ims I'm not sure they appear this way in the PWA. If it's only our renderer, then we can work around this.
