### ISSUE TITLE
CID 112151599 Saving as both integer and string

### ISSUE THREAD

**Issue by FrogGirl1123** [episphere/quest#406]
CID 112151599, "Have you had a menstrual period in the last 60 days?" saves replies as a mix of integers and strings.  Both Yes and No, as all response CIDs, need to be saved as integers.  When two formats are used it causes structural issues on the back end.

**Comment by danielruss** [comment]
@naiyume   I don't believe this is a quest issue.  Quest save both as strings.  Can you check the PWA "write results to firebase" code.

**Comment by FrogGirl1123** [comment]
Connect ID 6748294551 is an example of the integer and Connect ID 6697891999 is an example of the string.

**Comment by anthonypetersen** [comment]
@FrogGirl1123 looking at the database this feels like a case of someone manually making that value an integer.. I see 10 other participants that have "yes" for that question and they are all saved in string format.

Daniel is correct though, Quest is saving everything as strings.

**Comment by FrogGirl1123** [comment]
@anthonypetersen and @danielruss that would explain why it's a unique case.  I guess we can close this.  Once we clear dev it shouldn't be an issue anymore.  @danielruss can the Quest or the PWA for that matter save responses as integers?  It would be nice if at some point (maybe it will have to be in BQ2) we could have all the CID responses in the survey data as integers to match the rest of the Connect data.

**Comment by danielruss** [comment]
@FrogGirl1123  hmmm...  possibly..   String are nice because they are generic.  You would force me to have to figure out whether something whether something should be a number or string.  `|__|__|`  , `()` or `[]`. 

Of course you have the data dictionary, you can look it up and convert the string to number. 

How important is it that I store the value as a number?
