### ISSUE TITLE
Runaway loop numbering extensions

### ISSUE THREAD

**Issue by FrogGirl1123** [episphere/quest#411]
When quest adds the loop and count extensions to the CIDs for responses in question loops, the number of extensions "runs away" for example for D_726699695.D_142912472_1_1.D_206625031_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1, D_726699695.D_142912472_1_1.D_261863326_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1 .  While the source question has only the expected _1_1 the XOR responses (in this case age vs year of diagnosis).  May be more related to XOR than harmonized responses.

**Comment by danielruss** [comment]
@FrogGirl1123  which module contains D_726699695.D_142912472.D_206625031?  Did you have to do anything special to get this to occur?

**Comment by danielruss** [comment]
@FrogGirl1123 I think is is fixed.
