### ISSUE TITLE
Loop Issue for Sibling and Child Cancer Diagnosis Loops

### ISSUE THREAD

**Issue by FrogGirl1123** [episphere/quest#413]
Loops for siblings and children of the participant add a _#_# to the concept ID for the diagnosis for each loop/sibling/child that the question is asked for (e.g. _1_1 would be for answers for the second sibling for which information is given).

In the testing last week, when year was given for the age of diagnosis for skin cancer for a sibling it was stored like this:
D_726699695.D_278159347_1_1.D_261863326_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1

where 726699695 is the module CID, 278159347 is the skin cancer CID and 278159347 is the year of diagnosis CID.

I'm seeing the same issue for Breast Cancer (907590067), Cervical Cancer (860112841), Another Cancer (247160067) for Siblings, and Child Brain Cancer (601211723). I haven't check the rest of the child loops, but I assume it's present. 

This is not an issue for the first iteration of the loop.

It does appear to be a harmonization issue (all Year at Diagnosis have the CID of 261863326 and all Age at Diagnosis have a CID of 206625031) although the test data was from the Oct 8 and Oct 9 testing which was supposed to be using reverted non-harmonized version of the transformed Module 1 markup.

Data is being saved for the variables with the _1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1 extension.  I'm going to check against the test data to make sure the correct values are saved under each variable and will update the issue.  I'm waiting on access to the test data folder.

Please determine and resolve the cause of the loop labeling issue.

**Comment by danielruss** [comment]
I think this was fixed closing either way it is stale...
