### ISSUE TITLE
Using hidden variables in loops and entering in a particular iteration in loop

### ISSUE THREAD

**Issue by joshid-ims** [episphere/quest#414]
This is for Module 4 edge case scenario. Daniel working on it. 
@danielruss @boyd-mj @FrogGirl1123 @Davinkjohnson

**Comment by boyd-mj** [comment]
@FrogGirl1123 just a heads up that Deepti was able to implement Daniel's fix in a test scenario. We are currently working on a time estimate to implement these changes throughout the module so that you can determine whether we should proceed. I plan to have that to you by COB tomorrow.

**Comment by joshid-ims** [comment]
@danielruss Hey Daniel, I am not sure why this is evaluated as false in spite of these values:

exists('HOMEADD1_2_SHOWN') and  noneExist('STNUM1','FULLST1','APT1','CITY1','CITY_FOLLOWUP1','ST1','ST_FOLLOWUP1','ZIP1','ZIP_FOLLOWUP1','COUNTRY1','COUNTRY_FOLLOWUP1') and valueEquals('HOMEADDOTH1',1)  ==> false


Response stored in LF: Module4 {"HOMEADD1_1":{"STNUM":"9137","FULLST":"Sybert Dr","CITY":"Ellicott City","ST":"MD - Maryland","ZIP":"21043","COUNTRY":"India","HOMEADD1_1":"true"},"HOMEADDOTH1":"1","HOMEADD1_2":{"HOMEADD1_2":"true"},"HOMEADDOTH2":"1","HOMEADD1_3":{"STNUM2":"77","FULLST2":"Downing","CITY2":"Pune","ST2":"MH","ZIP2":"400029","COUNTRY2":"India","HOMEADD1_3":"true"},"HOMEADDOTH3":"0"}

All 3 conditions are true.

**Comment by joshid-ims** [comment]
Had a call with Kelsey and Julie last week. They were going to discuss internally how exactly it should work. 

No loop for asking addresses for sure though. 

Found while testing internally. 

@danielruss 
Hey Daniel, I am not sure why this is evaluated as false in spite of these values:

exists('HOMEADD1_2_SHOWN') and  noneExist('STNUM1','FULLST1','APT1','CITY1','CITY_FOLLOWUP1','ST1','ST_FOLLOWUP1','ZIP1','ZIP_FOLLOWUP1','COUNTRY1','COUNTRY_FOLLOWUP1') and valueEquals('HOMEADDOTH1',1)  ==> false

Response stored in LF: Module4 {"HOMEADD1_1":{"STNUM":"9137","FULLST":"Sybert Dr","CITY":"Ellicott City","ST":"MD - Maryland","ZIP":"21043","COUNTRY":"India","HOMEADD1_1":"true"},"HOMEADDOTH1":"1","HOMEADD1_2":{"HOMEADD1_2":"true"},"HOMEADDOTH2":"1","HOMEADD1_3":{"STNUM2":"77","FULLST2":"Downing","CITY2":"Pune","ST2":"MH","ZIP2":"400029","COUNTRY2":"India","HOMEADD1_3":"true"},"HOMEADDOTH3":"0"}

Daniel suggested some code. @danielruss can you please email it to me?

**Comment by joshid-ims** [comment]
This is how the output is and data is being stored with the changes Daniel suggested. This is only for HOMEADDR section. 

![image](https://user-images.githubusercontent.com/64986739/194583043-3b642741-979c-4329-a880-2a9cc3c3144e.png)

@cusackjm is this ok? 
@FrogGirl1123

**Comment by cusackjm** [comment]
I like that. Is it possible to have a semi colon after "nth address"? like:

Current Address: 123 street, state, zip

**Comment by cusackjm** [comment]
@joshid-ims thats ok

**Comment by joshid-ims** [comment]
Ok, I will add that. But are the DD changes and data storage in the back end ok?

**Comment by cusackjm** [comment]
@FrogGirl1123 are the changes to the data storage ok?

**Comment by joshid-ims** [comment]
Hey @danielruss , for some reason, the hidden variable is not working. 

anything wrong here?

|displayif=someExist("STNUM","FULLST","APT","CITY","CITY_FOLLOWUP","ST","ST_FOLLOWUP","ZIP","ZIP_FOLLOWUP","COUNTRY","COUNTRY_FOLLOWUP"):|{$STRNAME} {$STRTNAME} {$STNUM} {$FULLST} {$APT} {$CITY} {$CITY_FOLLOWUP} {$ST} {$ST_FOLLOWUP} {$ZIP} {$ZIP_FOLLOWUP} {$COUNTRY} {$COUNTRY_FOLLOWUP}||displayif=exists("HOMEADD1_1_SHOWN") and  noneExist("STNUM","FULLST","APT","CITY","CITY_FOLLOWUP","ST","ST_FOLLOWUP","ZIP","ZIP_FOLLOWUP","COUNTRY","COUNTRY_FOLLOWUP"):| Current Address|

Address displays if it is specified but not when it is left blank. 

I have used this: |hidden|id=HOMEADD1_1|

get this:

![image](https://user-images.githubusercontent.com/64986739/194928756-0eb5ac31-6bc3-41cd-8b11-d606e07eee85.png)

**Comment by danielruss** [comment]
@joshid-ims The code I sent to you awhile ago appears to have an extra right parentheses ")" in HOMEADD4_1.   From the error you sent, I'm not sure that is the problem.   I also changed the first iteration of the "loop" to STNUM1, FULLST1 ...

**Comment by joshid-ims** [comment]
@danielruss let me email you the whole code I am using. The first appearance of the hidden variable is where it hangs (Quest output Screen goes blank).

**Comment by danielruss** [comment]
@joshid-ims  I used your code in quest, but it works for me.

```
{"name":"Module4"}

[INTROM4] The questions in this section are about places where you have lived and worked. Where we live and our daily commute to and from our homes, work, and school can affect our health in a number of ways.
[INTRORH] <b>Residential History</b></br>
The next questions ask about where you live now and where you have lived in the past. The first questions are about the home(s) where you live most of the time. Questions about seasonal and vacation homes are at the end of this section. It is important that you share exact addresses, if possible. If you cannot remember your full address, please share as much information as you can.
You can include rural routes (RR) in your answers, but please do <b>not</b> include post office (PO) boxes. 

[HOMEADD1_1?] What is the full street address of the place where you live now?
Street number |__|__|id=STNUM min=0 max=999999|
Full Street name |__|id=FULLST|
Apartment, suite, unit, building, etc. |__|__|id=APT|
City |__|id=CITY|
State/Province |__|id=ST|
Zip code |__|id=ZIP|
Country |__|id=COUNTRY|
|hidden|id=HOMEADD1_1|

[HOMEADD2_1?,displayif=or(or(isNotDefined(CITY,false),isNotDefined(ST,false)),or(isNotDefined(ZIP,false),isNotDefined(COUNTRY,false)))] Please provide the following information:
City: |displayif=exists("CITY")|{$CITY}|
|__|id=CITY_FOLLOWUP displayif=doesNotExist("CITY")|

State/Province: |displayif=exists("ST")| {$ST}|
|__|id=ST_FOLLOWUP displayif=doesNotExist("ST")|

Zip code: |displayif=exists("ZIP") | {$ZIP}|
|__|id=ZIP_FOLLOWUP displayif=doesNotExist("ZIP")|

Country: |displayif=exists("COUNTRY")| {$COUNTRY}|
|__|id=COUNTRY_FOLLOWUP displayif=doesNotExist("COUNTRY")|
[77*] Don't know

[HOMEADD3_1?,displayif=noneExist("STNUM","FULLST") and someExist("CITY_FOLLOWUP","ST_FOLLOWUP","ZIP_FOLLOWUP","COUNTRY_FOLLOWUP","CITY","ST","ZIP","COUNTRY")] Please provide the cross streets of the intersection closest to this address:

Full Street name #1 |__|id=STRNAME1|
Full Street name #2 |__|id=STRTNAME1|
[77*] Don't know

[HOMEADD4_1] Here is the information you gave us for this location:|displayif=or(equals(isNotDefined(STNUM,""),false),or(equals(isNotDefined(FULLST,""),false),or(equals(isNotDefined(APT,""),false),or(equals(isNotDefined(CITY,""),false),or(equals(isNotDefined(CITY_FOLLOWUP,""),false),or(equals(isNotDefined(ST,""),false),or(equals(isNotDefined(ST_FOLLOWUP,""),false),or(equals(isNotDefined(ZIP,""),false),or(equals(isNotDefined(ZIP_FOLLOWUP,""),false),or(equals(isNotDefined(COUNTRY,""),false),equals(isNotDefined(COUNTRY_FOLLOWUP,""),false)))))))))))| {$STRNAME1} {$STRTNAME1} {$STNUM} {$FULLST} {$APT} {$CITY} {$CITY_FOLLOWUP} {$ST} {$ST_FOLLOWUP} {$ZIP} {$ZIP_FOLLOWUP} {$COUNTRY} {$COUNTRY_FOLLOWUP}|
|displayif=noneExist("STNUM","FULLST","APT","CITY","CITY_FOLLOWUP","ST","ST_FOLLOWUP","ZIP","ZIP_FOLLOWUP","COUNTRY","COUNTRY_FOLLOWUP")|Current Address|


If this information is <b>not</b> correct, please click the “Back” button to edit your answers before moving on.


[HOMEADDOTH1?] Within the <b>past 20 years</b>, have you lived anywhere else for <b>at least two years</b>?
(1) Yes -> HOMEADD1_2
(0) No 
[HOMEADDSUM_1?] Please review the list below and tell us if it includes all of the addresses where you have lived for at least two years in the last 20 years

Current Address: {$STRNAME} {$STRTNAME} {$STNUM} {$FULLST} {$APT} {$CITY} {$CITY_FOLLOWUP} {$ST} {$ST_FOLLOWUP} {$ZIP} {$ZIP_FOLLOWUP} {$COUNTRY} {$COUNTRY_FOLLOWUP} 

(1) These are all my addresses -> HOMEMOVEIN1
(0) I have another address
<#NR -> HOMEMOVEIN1>

[NEXT] next addr...


[HOMEMOVEIN1] move in...

[END] all done..
```

**Comment by danielruss** [comment]
@joshid-ims  

> displayif=exists("HOMEADD1_1_SHOWN") ...

However look how you set the id on the hidden element...

> |hidden|id=HOMEADD1_1|

You need either `displayif=exists("HOMEADD1_1.HOMEADD1_1")` or `|hidden|id=HOMEADD1_1_SHOWN|`

**Comment by joshid-ims** [comment]
Thanks, let me try that. But I had it that way in the original code you sent (I think).

**Comment by joshid-ims** [comment]
@danielruss I am not sure why, when data stored is as:

![image](https://user-images.githubusercontent.com/64986739/195380575-4e178a22-cffd-4905-b487-b28d57a35d55.png)

This condition is being evaluated as True:

![image](https://user-images.githubusercontent.com/64986739/195380820-817c5159-fd30-4c53-aeeb-198130b16790.png)

when they all exist.

**Comment by joshid-ims** [comment]
NVM, found the extra spaces before the variables.

**Comment by danielruss** [comment]
@joshid-ims ok to close?

**Comment by joshid-ims** [comment]
This is in internal IMS testing.

**Comment by danielruss** [comment]
@joshid-ims   Status??  ok to close...

**Comment by joshid-ims** [comment]
I think so.
