### ISSUE TITLE
exists function does not handle complex objects correctly

### ISSUE THREAD

**Issue by danielruss** [episphere/quest#416]
in the following example, _exists("D_728155643.D_728155643")_ returns true even if I still live here is not selected because if "D_728155643" exists, the function returns true.  need to fix around line 55 in questionnaire.js

```
[X] LALA

[D_728155643?] What year did you move out of|

If you still live at this address, select “I still live here.”
Year moved out |__|__|__|__|id=D_943813942|

[678602069*] I still live here

[END] all done |displayif=valueEquals("D_728155643.D_728155643","678602069")| I still live here ||displayif=exists("D_943813942")|{$D_943813942}|
```

**Comment by KELSEYDOWLING7** [comment]
@danielruss would you be able to give some context to the fix? I'll need Jake to adjust the flattening of these 33 variables on order for me to see the backend data
