### ISSUE TITLE
How to calculate months using month function

### ISSUE THREAD

**Issue by joshid-ims** [episphere/quest#419]
In the question COV22, since we do not have MONTH and YEAR separate values, I fo not know how to code the bolded equation using the |month| function's ID. 

```
[SRVCOV_COV3_V1R0!,displayif=greaterThanOrEqual(SRVCOV_COV2_V1R0,#loop)] When was the <b>{##}</b> time that you had COVID-19? If you are not sure, please make your best guess.

|month|id=SRVCOV_COV3_MY_V1R0 min=valueOrDefault("SRVCOV_COV3_MY_V1R0#prev","2020-03") max=#currentYear-#currentMonth|

[SRVCOV_COV22_V1R0?] How long did it take you to recover to your usual state of health from the date you first realized you had COVID-19?

Months |__|__|id=SRVCOV_COV22_MONTHS_V1R0 min=0 **max=(#currentYear-_value("SRVCOV_COV3_YEAR_V1R0_1_1"))*12 + (#currentMonth-_value("SRVCOV_COV3_MONTH_V1R0_1_1"))**|
Days |__|__|__|id=SRVCOV_COV22_DAYS_V1R0 min=1 max=365|
```

@JulieCusack If this is not possible, this question COV22 will need to be asked in a different way.

**Comment by danielruss** [comment]
the format of the month is YYYY-MM.  Do you want a function that takes two month and subtracts? 
like monthDiff(YYYY-MM) is how many months ago  and monthDiff(YYYY-MM,YYYY-MM) is the difference between two months (not including days so July 2020-June 2020 = 1 )

**Comment by joshid-ims** [comment]
I guess what NCI wants looking at the question COV22 is difference between two months.

**Comment by joshid-ims** [comment]
@danielruss any updates?

**Comment by joshid-ims** [comment]
@cusackjm

**Comment by cusackjm** [comment]
@joshid-ims can you program it how COV27 is? 
![image](https://user-images.githubusercontent.com/85582895/223753678-6caef632-15d1-491a-a5fb-1d76547fb9e0.png)

**Comment by joshid-ims** [comment]
COV27 is asking about a date. COV22 is asking about duration. So needs some calculations.

**Comment by cusackjm** [comment]
@joshid-ims sorry I read that wrong, is the previous code from blood/urine/mtw no longer working? Otherwise, I can discuss asking the question differently with Neal

**Comment by joshid-ims** [comment]
The previous code uses Month and Year functions which are not used anymore as we are using calendar widget.

Yes, asking question differently is an option.

**Comment by cusackjm** [comment]
@joshid-ims I have updated the qx document with the following edits: 
![image](https://user-images.githubusercontent.com/85582895/223807947-1dc8b3c8-2838-430d-8a03-99bee15dd288.png)
(keep COV3 as the YYYY/MM calendar picker)
![image](https://user-images.githubusercontent.com/85582895/223807893-3eb1b651-9086-480c-851a-0bd7a3ce8778.png)
(Keep COV22 question text and response types as is, but remove the range checks)

**Comment by joshid-ims** [comment]
Thanks!

**Comment by danielruss** [comment]
@joshid-ims   Sorry it took so long.  

```
[Q1] Pick 2 dates
first month |month|id=m1|
second month |month|id=m2|

[Q2]  This is a question.

|displayif=yearMonth("m2")-yearMonth("m1")>2| m1 is at least two months before m2|
|displayif=yearMonth("m1")-yearMonth("m2")>2| m2 is at least two months before m1|
|displayif=abs(yearMonth("m1")-yearMonth("m2"))>2| m1 and m2 are at least 2 months apart|
```

**Comment by joshid-ims** [comment]
I guess with the changes in the document, this is not not required anymore.
