### ISSUE TITLE
Variables in ValueIsOneOf function are not getting converted

### ISSUE THREAD

**Issue by joshid-ims** [episphere/quest#422]
@danielruss 

This question is not converting variables SEX and GEN correctly. This is working unconverted but not when converted. I had tried quotes around numbers as you had suggested first too. That did not work so tried removing quotes. They are converted in another question where only equals and or is used. 

[SRVSCR_BRSTSCREEN_V1R0?,displayif="ValueIsOneOf("SEX",0,2) or ValueIsOneOf("GEN",2,3,4,5,55)"] <b>Breast Cancer Screening</b>
Have you <b>ever</b> had any of these procedures to check for breast cancer or other conditions? Select all that apply. 
[0] <b>Mammogram</b>
An x-ray of the breast. Involves standing in front of mammography machine that 	compresses your breasts between 2 plates.
[1] <b>Breast MRI</b>
An MRI (Magnetic Resonance Imaging) of the breast. Detailed pictures of the inside of your breast are taken while you were laying down in an MRI machine. Usually requires getting a dye through a needle in your arm.
[2] <b>Breast Ultrasound</b>
An ultrasound of the breast. A healthcare provider moved a wand-like device called a transducer over your skin to make the images of your breasts.
[3] <b>Breast Biopsy</b>
Small amounts of the breast are removed with a biopsy needle or during 	surgery. The breast tissue or cells are then looked at under a microscope to check for cancer or other problems.
[88*] I have not had any of these screening tests  -> SRVSCR_OVSCREEN_V1R0
<#NR -> SRVSCR_OVSCREEN_V1R0>

**Comment by boyd-mj** [comment]
@joshid-ims is the code not converting as expected? If so, this is probably a question for Kirk, who may not have access to this Github.

**Comment by kirksnyder** [comment]
We may (or may not) have a transformer issue, but the first problem to address is that the untransformed code is raising an error in Quest:
`[SRVSCR_BRSTSCREEN_V1R0?,displayif="ValueIsOneOf("SEX",0,2) or ValueIsOneOf("GEN",2,3,4,5,55)"]`

Here's the screenshot @joshid-ims sent me:
![MicrosoftTeams-image](https://github.com/episphere/quest/assets/14188539/58aa0216-d314-4b02-b60a-5624bd350b38)

**Comment by danielruss** [comment]
Dont capitalize the "V". The function is "valueIsOneOf" not "ValueIsOneOf"

**Comment by joshid-ims** [comment]
We get this: 

![image](https://github.com/episphere/quest/assets/64986739/9ec34386-7354-461c-bb44-5239771261e1)

**Comment by joshid-ims** [comment]
[SRVSCR_BRSTSCREEN_V1R0?,displayif="valueIsOneOf("SEX","0","2") or valueIsOneOf("GEN","2","3","4","5","55")"] <b>Breast Cancer Screening</b>
Have you <b>ever</b> had any of these procedures to check for breast cancer or other conditions? Select all that apply. 
[0] <b>Mammogram</b>
An x-ray of the breast. Involves standing in front of mammography machine that 	compresses your breasts between 2 plates.
[1] <b>Breast MRI</b>
An MRI (Magnetic Resonance Imaging) of the breast. Detailed pictures of the inside of your breast are taken while you were laying down in an MRI machine. Usually requires getting a dye through a needle in your arm.
[2] <b>Breast Ultrasound</b>
An ultrasound of the breast. A healthcare provider moved a wand-like device called a transducer over your skin to make the images of your breasts.
[3] <b>Breast Biopsy</b>
Small amounts of the breast are removed with a biopsy needle or during 	surgery. The breast tissue or cells are then looked at under a microscope to check for cancer or other problems.
[88*] I have not had any of these screening tests  -> SRVSCR_OVSCREEN_V1R0
<#NR -> SRVSCR_OVSCREEN_V1R0>

**Comment by danielruss** [comment]
Try with single quotes before valueIsOneOf and after last closing parenthesis:

`displayif='valueIsOneOf("SEX","0","2") or valueIsOneOf("GEN","2","3","4","5","55")'`

**Comment by joshid-ims** [comment]
This code is still not working. Giving same error as Bad displayif function. 


[SRVSCR_BRSTSCREEN_V1R0?,**displayif='valueIsOneOf("SEX","0","2") or valueIsOneOf("GEN","2","3","4","5","55")']** <b>Breast Cancer Screening</b>
Have you <b>ever</b> had any of these procedures to check for breast cancer or other conditions? Select all that apply. 
[0] <b>Mammogram</b>
An x-ray of the breast. Involves standing in front of mammography machine that compresses your breasts between 2 plates.
[1] <b>Breast MRI</b>
An MRI (Magnetic Resonance Imaging) of the breast. Detailed pictures of the inside of your breast are taken while you were laying down in an MRI machine. Usually requires getting a dye through a needle in your arm.
[2] <b>Breast Ultrasound</b>
An ultrasound of the breast. A healthcare provider moved a wand-like device called a transducer over your skin to make the images of your breasts.
[3] <b>Breast Biopsy</b>
Small amounts of the breast are removed with a biopsy needle or during 	surgery. The breast tissue or cells are then looked at under a microscope to check for cancer or other problems.
[88*] I have not had any of these screening tests  -> SRVSCR_OVSCREEN_V1R0
<#NR -> SRVSCR_OVSCREEN_V1R0>

[SRVSCR_BRSTTISS_V1R0?,displayif=**'valueIsOneOf("GEN","2","3","4","5","55") or equals(SEX,2)'**] Have you <b>ever</b> had breasts or breast tissue?
(1)	Yes
(0)	No
(77) 	Don’t know

**Comment by boyd-mj** [comment]
@danielruss any ideas on the above?
