### ISSUE TITLE
Unexpected values stored for questions with a text box

### ISSUE THREAD

**Issue by huip-ims** [episphere/quest#425]
@danielruss Hi Daniel - While doing some testing using the renderer, we noticed some unexpected behavior involving questions with a text box. In the example markdown code below:
1. If you click on the radio button ‘No’ (option 0) for COV19C6A and then click on the text box (i.e., move the cursor to within the text box), then click the ‘NEXT’ button, the response stored for COV19C6A is ‘1’ instead. But, the skip pattern behaves as though the ‘0’ response was stored and skips to question EDU.
2. However, if you then click on the ‘BACK’ button, it will show that radio button ‘No’ (0) was selected for COV19C6A, which was the original selection, but this is not the value being stored.

It seems by just moving the cursor to within a text box, it changes the response value being stored but the skip pattern still follows the original radio button selection.  This happens for all questions with a text box.  Is this the expected behavior for questions with a text box?

[SRVCOV_COV19C6A_V1R0?] Since your COVID-19 diagnosis, have you experienced any other symptoms?
(0) No -> EDU
(1) Yes, |__|id=SRVCOV_COV19C6ADESC_V1R0| -> SRVCOV_COV19C6B_V1R0
< #NR -> EDU>

[SRVCOV_COV19C6B_V1R0] Are you still experiencing these other symptoms?
(1) Yes
(0) No

[EDU?] What is the highest level of school that you have completed?
(0) Grade school (grades 1-8)
(1) Some high school (grades 9-11), no diploma
(2) High school graduate or GED
(3) Some college, no degree
(4) Technical or trade school after high school
(5) Associate’s degree
(6) College graduate (Bachelor’s degree)
(7) Advanced degree (Master’s, Doctorate, etc.)
(55) Other: Please describe |__|id=EDU_TB|

[END] You have answered all of the questions in this survey. To submit your answers, select the “Submit Survey” button.

**Comment by danielruss** [comment]
@huip-ims  I dont see this behavior.  What browser are you using?

In the meantime, this is the expected behavior (not your behavior and not what I see in Chrome 114.0.5735.198, Mac OS-arm64): When you click on NO... No is selected.  Clicking inside the text box should only add the focus to the text box.  If however you type something, YES should then be selected.  If you delete what you typed, Yes should remain selected.   What I see is that Yes is unselected (although it is written into the results).  I cannot explain why you see NO in the results.  

I assume there was a reason for the unselect.  I will look into the code/history for comments.

**Comment by huip-ims** [comment]
@danielruss Daniel - Several testers at IMS are seeing the behavior I described in my comment. We are using Google Chrome (Version 114.0.5735.199 (Official Build) (64-bit)). I just did the same test in the renderer using Microsoft Edge, and I also see the same strange behavior.

**Comment by danielruss** [comment]
@huip-ims I pushed a fix that does not unselect the radio button.  Please check with the test module above using [the developer tool](https://episphere.github.io/quest/)

**Comment by danielruss** [comment]
@huip-ims   I have reproduced your initial bug....  dont bother testing

**Comment by danielruss** [comment]
@huip-ims I think I fix it this time...  Please check...  One side effect,  if you have an empty box, it will ask you to fill it in.

**Comment by huip-ims** [comment]
@danielruss Thanks Daniel. From my initial text, it appears to be fixed. I'll ask Gwen to test the entire survey and will let you know if we have additional questions.
