### ISSUE TITLE
Quests Errors Captured in DataDog

### ISSUE THREAD

**Issue by anthonypetersen** [episphere/quest#429]
![image](https://github.com/episphere/quest/assets/18222069/78d06a18-bc25-4f5a-a4ef-1d4273b55031)

![image](https://github.com/episphere/quest/assets/18222069/5fff5f8c-fa21-4a94-b2b1-f0a87a940368)

![image](https://github.com/episphere/quest/assets/18222069/c06135f7-81c6-4e2a-b9d1-3eba396ed007)

**Comment by danielruss** [comment]
@anthonypetersen  this  was rolled back and fixed correct?

**Comment by anthonypetersen** [comment]
Yes, I'll close this.
