### ISSUE TITLE
Skipping an entire survey

### ISSUE THREAD

**Issue by huip-ims** [episphere/quest#432]
Hi Daniel,

A participant is only eligible to take the Menstrual Cycle survey if the participant provided a response of (SrvBlU_MENST60_v2r0=1) in the Blood/Urine survey. Currently, we are using Displayif statements in the Menstrual Cycle markdown to block all the questions if SrvBlU_MENST60_v2r0 is not 1, but the participant still has to click the "Submit" button at the end to move forward even though no questions were asked. Is there a more efficient way to skip the entire survey?

Thanks,
Pete

**Comment by cusackjm** [comment]
@huip-ims I think I created confusion in editing the survey instructions. I reverted those edits, please see the updated questionnaire document.

**Comment by danielruss** [comment]
@huip-ims Quest does not currently have this functionality.  Awhile ago, I was thinking of adding a SKIP-IF  like this < if(condition) -> END >  

so you can have a question like...
```
[START] Hi There, we would like to ask you a few questions about your post-graduate experience.
< if(valueOrDefault(LevelOfEducation,1)>16) -> Q1 >
[SKIPQ] Thank you but you did not go to graduate school
<-> END>
[Q1] Why did you choose to wait your time? |___|
.... 
```

**Comment by cusackjm** [comment]
@huip-ims IMS does not need to program the survey trigger in the markdown. Once directions are removed, we will not have this issue. Triggers are handled by NCI

**Comment by huip-ims** [comment]
@cusackjm Thanks Julie for the clarification. I will update the markdown accordingly.
