### ISSUE TITLE
Conditional text boxes

### ISSUE THREAD

**Issue by huip-ims** [episphere/quest#451]
@anthonypetersen @joshid-ims Hi Tony - For Spanish M4, there are some conditional text boxes. The function we used previously is no longer working in the renderer. For HOMEADD1_1, it asks for the full address. And, for HOMEADD2_1, only the text boxes for CITY, STATE, ZIP, or COUNTRY should show if not answered in the lead-in question. However, all text boxes are showing now for HOMEADD2_1, regardless of the responses in the lead-in question. Can you help us resolve this?  See below for code we used before that worked.

`[HOMEADD1_1?]¿Cuál es la dirección completa del lugar donde vive actualmente? 
Número de la calle  |__|id=STNUM min=0 max=999999|
Nombre completo de la calle  |__|id=FULLST|
Apartamento, <i>suite</i>, unidad, edificio, etc. 	 |__|id=APT|
Ciudad  |__|id=CITY|
Estado o provincia  |__|id=ST|
Código postal  |__|id=ZIP|
País  |__|id=COUNTRY|

[HOMEADD2_1?,displayif=or(or(isNotDefined(CITY,false),isNotDefined(ST,false)),or(isNotDefined(ZIP,false),isNotDefined(COUNTRY,false)))] Suministre la siguiente información: 
Ciudad: |displayif=exists("CITY")|{$CITY}|
|__|id=CITY_FOLLOWUP displayif=doesNotExist("CITY")|

Estado o provincia: |displayif=exists("ST")| {$ST}|
|__|id=ST_FOLLOWUP displayif=doesNotExist("ST")|

Código postal: |displayif=exists("ZIP") | {$ZIP}|
|__|id=ZIP_FOLLOWUP displayif=doesNotExist("ZIP")|

País: |displayif=exists("COUNTRY")| {$COUNTRY}|
|__|id=COUNTRY_FOLLOWUP displayif=doesNotExist("COUNTRY")|
[77*] No sé`

**Comment by anthonypetersen** [comment]
appears to be same issue as https://github.com/episphere/questionnaire/issues/385
