### ISSUE TITLE
Wiki- grid and multiple questions on same screen

### ISSUE THREAD

**Issue by ashreves** [episphere/quest#59]
From the wiki, it is not clear how grids should be programmed, or instances when multiple questions need to appear on a single screen. I know this is definitely something that will arise in module 2 with the physical activity questions. If you want this to be added as an issue later, than this can be deleted.

**Comment by ruggz13** [comment]
I think grids won't be a part of Quest. Grids will be unrolled and become loops into separate questions

**Comment by ruggz13** [comment]
Grids are now in the wiki
