### ISSUE TITLE
Demo Demographics

### ISSUE THREAD

**Issue by jonasalmeida** [episphere/quest#73]
reproducible with <a href="https://episphere.github.io/quest/?questionnaires/demo.txt">episphere.github.io/quest/?questionnaires/demo.txt</a>

<img width="808" alt="Screen Shot 2020-05-13 at 4 17 36 PM" src="https://user-images.githubusercontent.com/204769/81861698-a65b5f00-9536-11ea-95e9-1728a9c34349.png">

**Comment by danielruss** [comment]
The regex for input[type=text] was modified to allow adding arguments to the input tag.  The problem was if there were 2 input[type=text] tags the regex would catch BOTH tags.  

changed the input regex to |__|Xy+X|  where X is NOT a space and y is NOT a |
