### ISSUE TITLE
Module 2- PREG3

### ISSUE THREAD

**Issue by joshid-ims** [episphere/quest#75]
PREG3 does not go to next question.

**Comment by ruggz13** [comment]
Is this a markdown issue? @danielruss

**Comment by danielruss** [comment]
I'll run Module 2.

**Comment by danielruss** [comment]
[PREG?] Are you currently pregnant?
(1)Yes -> PREG3
(2)No -> PREG2
<#NR -> PREG2>

[PREG2?]Have you ever been pregnant?
(1)Yes  -> PREG3
(2)No -> FERT1
<#NR -> FERT1>

[PREG3?] How many times have you been pregnant? Please include all live births, as well as pregnancies that ended as stillbirths, miscarriages, ectopic or tubal pregnancies, or termination. Twins, triplets, or higher multiples count as one pregnancy. 
|__|__| #Pregnancies

[PREGCONFIRM] You told us that you have been pregnant {$PREG3} time|displayif=greaterThan(PREG3,1)|s|, including all live births, as well as pregnancies that ended as stillbirths, miscarriages, ectopic or tubal pregnancies, or termination.

If this is <b>not</b> correct, please select the “Back” button to update your response. If this is correct, please select the “Next” button to move forward. 

<loop max=25>
[PREG4?,displayif=greaterThanOrEqual(PREG3,#loop)?] How old were you when your #loop|displayif=or(equals(#loop,1),equals(#loop,21))|st||displayif=or(equals(#loop,2),equals(#loop,22))|nd||displayif=or(equals(#loop,3),equals(#loop,23))|rd||displayif=and(greaterThanOrEqual(#loop,4),and(doesNotEqual(#loop,21),and(doesNotEqual(#loop,22),doesNotEqual(#loop,23))))|th| pregnancy began? 
|__|__| Age
[PREG5?,displayif=greaterThanOrEqual(PREG3,#loop)?] What was the outcome of this pregnancy?
(1)Live birth: single infant -> PREG7
(2)Live birth: twins, triplets, or higher multiples -> PREG6
(3)Stillbirth (pregnancy loss after 20 weeks) -> PREGSUMMARY
(4)Live birth and stillbirth (loss of one or more of multiples) -> PREG6
(5)Miscarriage (pregnancy loss before 20 weeks) -> PREGSUMMARY
(6)Termination -> PREGSUMMARY
(7)Ectopic or tubal pregnancy (fertilized egg implants outside of the uterus) -> PREGSUMMARY
(99)Prefer not to answer -> PREGSUMMARY
< -> PREGSUMMARY >

[PREG6?,displayif=greaterThanOrEqual(PREG3,#loop)?]How many infants were delivered |displayif=equals(PREG5,4)|Include live births and stillbirths in your response.|
(1|twins)Two (Twins)
(2|triplets)Three (Triplets)
(3|more)Four or more
< ->PREG7 >

[PREG7?,displayif=greaterThanOrEqual(PREG3,#loop)?] What was the method of delivery?
(1)Cesarean
(2)Vaginal
< -> PREG8 >

[PREG8?,displayif=greaterThanOrEqual(PREG3,#loop)] Did you breast feed|displayif=equals(PREG5,1)| this child||displayif=equals(PREG5,2)| these children|? If you are currently breastfeeding, select yes. 
(1) Yes -> PREG9
(0) No

[PREG9?,displayif=greaterThanOrEqual(PREG3,#loop)] How many months did you breastfeed|displayif=equals(PREG5,1)| this child||displayif=equals(PREG5,2)| these children|? If you are currently breastfeeding, please tell us the number of months you have been breastfeeding so far. 
|__|__|id=PREG9_months|

[PREGSUMMARY,displayif=greaterThanOrEqual(PREG3,#loop)] Here’s a summary of the information you shared about this pregnancy. If any of the information is incorrect, please select the “Back” button to update your responses. If all of the information is correct, please select the “Next” button to move forward.

Age when pregnancy began: {$PREG4}
|displayif=equals(isDefined(PREG5,99),1)|Outcome of pregnancy: Live birth: single infant||displayif=equals(isDefined(PREG5,99),2)|Outcome of pregnancy: twins, triplets, or higher multiples||displayif=equals(isDefined(PREG5,99),3)|Outcome of pregnancy: Stillbirth||displayif=equals(isDefined(PREG5,99),4)|Outcome of pregnancy: Live birth and stillbirth||displayif=equals(isDefined(PREG5,99),5)|Outcome of pregnancy: Miscarriage||displayif=equals(isDefined(PREG5,99),6)|Outcome of pregnancy: Termination||displayif=equals(isDefined(PREG5,99),7)|Outcome of pregnancy: Ectopic or tubal pregnancy|
|displayif=equals(isDefined(PREG6,0),1)|Number of infants: 2||displayif=equals(isDefined(PREG6,0),2)|Number of infants: 3||displayif=equals(isDefined(PREG6,0),3)|Number of infants: 4 or more||displayif=equals(PREG5,1)|Number of infants: 1|
|displayif=equals(isDefined(PREG7,0),1)|Method of delivery:  Cesarean ||displayif=equals(isDefined(PREG7,0),2)|Method of delivery:  Vaginal |
|displayif=equals(isDefined(PREG8,-1),1)|Did you breastfeed: Yes||displayif=equals(isDefined(PREG8,-1),0)|Did you breastfeed: No|
|displayif=equals(isDefined(PREG8,-1),1)|Number of months of breastfeeding: {$PREG9_months}|

</loop>

[FERT1,end] Done

**Comment by danielruss** [comment]
I have attached the PREGNANCY loop.  It works for me, but you should definitely test it out.

**Comment by danielruss** [comment]
I had to cut this section out because there are errors in the early part of Module 2 that don't let me make it to the pregnancy section.

**Comment by danielruss** [comment]
@joshid-ims @meekk1 can one of you update module two with my markdown.  If it works, please close the issue.

**Comment by danielruss** [comment]
I just noticed that you cannot see some of the code.  I'll create a GIST and attach the link

**Comment by danielruss** [comment]
https://gist.github.com/danielruss/1c8dd8407b98b8567ddd0969be38f9cb

**Comment by meekk1** [comment]
That works, thanks. Closing.
