### ISSUE TITLE
IF/ELSE on conditional Display

### ISSUE THREAD

**Issue by danielruss** [episphere/quest#82]
See Question [SLEEP1A] in module 2.

**Comment by danielruss** [comment]
by using multiple conditional piped text, the user can produce the text.  This enhance would make it simpler for the questionnaire use, but is low priority.

**Comment by danielruss** [comment]
maybe a good syntax would be |displayif==xx|text if true|text if false|

**Comment by ruggz13** [comment]
So instead of |displayif=equals(SLEEPSCH,1)| the nights before workdays| |displayif=or(equals(SLEEPSCHA,0),equals(SLEEPSCHA, undefined))|most days|

|displayif==xx|text if true|text if false| ? @danielruss

**Comment by danielruss** [comment]
yes that is the idea.

**Comment by ruggz13** [comment]
what would the condition be? just |displayif=equals(SLEEPSCH,1)|the nights before workdays||most days|

**Comment by hzhao392** [comment]
will discuss with IMS

**Comment by hzhao392** [comment]
removing module 2 tag from this since it would apply to all IF/ELSE

**Comment by danielruss** [comment]
stale issue ... closing
