### ISSUE TITLE
Enter takes you backward instead of forwards

### ISSUE THREAD

**Issue by ashreves** [episphere/quest#90]
If you type an age and then hit enter it takes you back to the condition you selected (the prior screen) rather than forward. If instead of hitting enter you click 'next' it takes you forward to the appropriate place. Seems to be a universal problem on 'enter'.

On further testing, this occurs for any open text response (e.g. WORK3) where I hit enter rather than click next.

**Comment by ruggz13** [comment]
fixed 'enter' bug
