### ISSUE TITLE
Range checks for age/year

### ISSUE THREAD

**Issue by ashreves** [episphere/quest#91]
Range checks for age and year don't seem to be working. Allowed in put year before born, could say parents age was younger than participant, etc.  The content of the range check is not right but also the way it is functioning is not right (how it only appears if you enter not if you click 'next' and how the red outline of the boxes doesn't appear at a time that makes sense to the person. Also, the wording they put leaves something to be desired. Perhaps reference the Qualtrics error messages as an example?

See all age questions.

**Comment by ruggz13** [comment]
All age verifications should be fixed now
