### ISSUE TITLE
Piped text

### ISSUE THREAD

**Issue by ashreves** [episphere/quest#92]
Piped text throughout the module is not working in any question. This needs to be corrected and verified throughout the entire module.

See SIB2 and ISIB3. Instead of filling in with the relevant text, the question shows all possible option. [SIB2 shows [oldest/next oldest] and SIB3 [he/she/your sibling]. The text should be piped in based on prior responses, as noted on the word document.

**Comment by ruggz13** [comment]
Went through and correct all of the changes for this
