### ISSUE TITLE
Browser testing needed

### ISSUE THREAD

**Issue by ashreves** [episphere/quest#97]
Instrument doesn't work in MS Edge or Firefox on my Dell PC laptop. Needs thorough browser testing.

**Comment by ruggz13** [comment]
Some changes were made, need updates on this. @ashreves @danielruss

**Comment by ruggz13** [comment]
@ashreves if more testing could be done, that would be great

**Comment by ashreves** [comment]
@ruggz13 Does not work on Edge.

**Comment by ashreves** [comment]
@ruggz13 Just opened in Firefox and it seems to work, but not sure how to test prior Firefox versions

**Comment by ruggz13** [comment]
What doesn't work in Edge? Bhaumik just tested it and said it was working @ashreves

**Comment by ruggz13** [comment]
Maybe you are using an outdated version of Edge

**Comment by ashreves** [comment]
@ashreves I'm using Microsoft Edge 44.17763.831.0

@bhaumik55231 is this the same version that are you using?

**Comment by bhaumik55231** [comment]
@ashreves I'm using 83.0.478.61

**Comment by ashreves** [comment]
@bhaumik55231 @ruggz13 that explains the issue. I do worry that our participants filling out surveys at home will have similar issues. 

Is there anyway to enables pop up saying that browser needs to be updated to view the questionnaire? After I entered my name and age, it brought me to a completely blank screen.

**Comment by ashreves** [comment]
According to Nick, the following devices/browsers will need to be tested:
Macs: Microsoft Edge, Safari, Google Chrome, FireFox
PCs: Microsoft Edge, Google Chrome, FireFox
iPhones: Safari, Google Chrome, FireFox
Android: Google Chrome, whatever other browser it has
Tablets: Safari, Google Chrome

Alaina and Amelia will conduct testing on PCs, iPhones, and Tablets. Someone from DevOps with an Android phone and Mac computer will need to do the other device testing.

**Comment by hzhao392** [comment]
Will be tested in PWA
