### ISSUE TITLE
Requested format for responses not clear

### ISSUE THREAD

**Issue by ashreves** [episphere/quest#98]
When entering a phone number, it asked for the "requested format" but there is no indication of what that means. Same for SSN. Please describe what format is requested and try to accept multiple versions of the text. (ex. for SSN, allow for digit only entry instead of forcing participants to type dashes)

**Comment by ruggz13** [comment]
Done... Phone numbers now have a placeholder for formats. Same with SSN. Allow for given format or without dashes
